window.sizeChanges = {
	'Ajeet Singh Chana': '58px',
	'Amruth Arunkumar': '58px',
	'Mathew Niznansky': '58px',
	'Matthew Krawczyk': '58px',
	'Nicholas Patterson': '58px',
	'Aris Efstathopoulos': '56px',
	'Kevin Jacob Rajesh': '56px',
	'Sebastian Ciuperca': '56px',
	'Nicolas de Lottinville': '54px',
	'Hisham Ahmed Khan': '52px',
	'Jensen Belen-Brown': '52px',
	'Koda Arthur Cobierski': '50px',
	'Thomas van Leeuwen': '50px',
	'Arjun Soundar Hariram': '48px',
	'Zhivko Radkov Dimitrov': '46px',
}

window.competitors = [
{ name: 'Aaron Elliott Kriss', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Aaron King', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Abdullah Gulab', wca_id: '2014GULA02', title: 'DELEGATE' },
{ name: 'Adam Vanderwal', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Adi Gausman', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Adrian Panszczyk', wca_id: '2015PANS01', title: 'COMPETITOR' },
{ name: 'Ajeet Singh Chana', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Alan Jia', wca_id: '2017JIAA01', title: 'COMPETITOR' },
{ name: 'Alex Chernish', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Alex Jung', wca_id: '2018JUNG02', title: 'COMPETITOR' },
{ name: 'Alyssa Esparaz', wca_id: '2014ESPA01', title: 'STAFF' },
{ name: 'Amruth Arunkumar', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Andrew Song', wca_id: '2019SONG28', title: 'COMPETITOR' },
{ name: 'Andry Rakoto', wca_id: '2016RAKO02', title: 'COMPETITOR' },
{ name: 'Anthony Nguyen', wca_id: '2018NGUY40', title: 'COMPETITOR' },
{ name: 'Aris Efstathopoulos', wca_id: '2019EFST01', title: 'COMPETITOR' },
{ name: 'Arjun Soundar Hariram', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Arturo Pico', wca_id: '2018PICO02', title: 'COMPETITOR' },
{ name: 'Aryan Ved', wca_id: '2018VEDA02', title: 'COMPETITOR' },
{ name: 'Avner Bernstein', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Ayan Iqbal', wca_id: '2018IQBA02', title: 'COMPETITOR' },
{ name: 'Bart Podhorski', wca_id: '2019PODH01', title: 'COMPETITOR' },
{ name: 'Ben Madison', wca_id: '2016MADI02', title: 'COMPETITOR' },
{ name: 'Ben Rockman', wca_id: '2014ROCK01', title: 'STAFF' },
{ name: 'Benjamin Kyle', wca_id: '2016KYLE01', title: 'COMPETITOR' },
{ name: 'Benson Lau', wca_id: '2019LAUB01', title: 'COMPETITOR' },
{ name: 'Bill Wang', wca_id: '2010WANG68', title: 'COMPETITOR' },
{ name: 'Blaeden Kohout', wca_id: '2019KOHO01', title: 'COMPETITOR' },
{ name: 'Blaize Kohout', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Brady Metherall', wca_id: '2009METH01', title: 'STAFF' },
{ name: 'Braeden Klaehn', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Braeden Malda', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Brennen Lin', wca_id: '2016LINB01', title: 'COMPETITOR' },
{ name: 'Brody Oleksyn', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Bryce Oleksyn', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Carson Carrasco', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Charles Goertz', wca_id: '2017GOER01', title: 'COMPETITOR' },
{ name: 'Cheng Han Huo', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Christian Eifert', wca_id: '2019EIFE01', title: 'COMPETITOR' },
{ name: 'Cole Woodcock', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Colin Gawthroupe', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Connor DeLuca', wca_id: '2012DELU01', title: 'COMPETITOR' },
{ name: 'Dave Campbell', wca_id: '2005CAMP01', title: 'COMPETITOR' },
{ name: 'Dave Deriches', wca_id: '2018DERI02', title: 'COMPETITOR' },
{ name: 'Derek Kong', wca_id: '2017KONG08', title: 'STAFF' },
{ name: 'Derek Walker', wca_id: '2019WALK02', title: 'COMPETITOR' },
{ name: 'Edmund Yong', wca_id: '2018YONG03', title: 'COMPETITOR' },
{ name: 'Elias Arovuo', wca_id: '2018AROV01', title: 'COMPETITOR' },
{ name: 'Emma Kennedy', wca_id: '2019KENN02', title: 'COMPETITOR' },
{ name: 'Erik Lee', wca_id: '2018LEEE05', title: 'COMPETITOR' },
{ name: 'Ethan Campbell', wca_id: '2019CAMP02', title: 'COMPETITOR' },
{ name: 'Ethan Erez', wca_id: '2017EREZ01', title: 'COMPETITOR' },
{ name: 'Ethan Greenberg', wca_id: '2015GREE11', title: 'COMPETITOR' },
{ name: 'Ethan Honest', wca_id: '2019HONE03', title: 'COMPETITOR' },
{ name: 'Ethan Yeung', wca_id: '2019YEUN02', title: 'COMPETITOR' },
{ name: 'Evan Gerber', wca_id: '2019GERB01', title: 'COMPETITOR' },
{ name: 'Fatima Gulab', wca_id: '2015GULA01', title: 'STAFF' },
{ name: 'Flora Chan', wca_id: '2019CHAN12', title: 'COMPETITOR' },
{ name: 'Fred Xiang', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Gavin Chen', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Geoffrey Stefanov', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Geoffrey Stevens', wca_id: '2017STEV03', title: 'COMPETITOR' },
{ name: 'Henry Hughes', wca_id: '2015HUGH02', title: 'STAFF' },
{ name: 'Henry Siebertz', wca_id: '2017SIEB02', title: 'COMPETITOR' },
{ name: 'Henry Sun', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Hisham Ahmed Khan', wca_id: '2019KHAN14', title: 'COMPETITOR' },
{ name: 'Hudson Tranmer', wca_id: '2019TRAN03', title: 'COMPETITOR' },
{ name: 'Huy Nguyen', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Iain Holla', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Io McKay', wca_id: '2018MCKA01', title: 'COMPETITOR' },
{ name: 'Ishan Saini', wca_id: '2019SAIN08', title: 'COMPETITOR' },
{ name: 'Jack Costa', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Jack Engledow', wca_id: '2013ENGL01', title: 'COMPETITOR' },
{ name: 'Jack Walsh', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Jacob Eoin Gipp', wca_id: '2016GIPP01', title: 'COMPETITOR' },
{ name: 'James Hocevar', wca_id: '2016HOCE02', title: 'COMPETITOR' },
{ name: 'Jared Kiers', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Jensen Belen-Brown', wca_id: '2016BELE02', title: 'COMPETITOR' },
{ name: 'Jerry Guo', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Jim Wang', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Joaquin Abarca', wca_id: '2017ABAR02', title: 'COMPETITOR' },
{ name: 'Joe Vander Veen', wca_id: '2013VEEN01', title: 'COMPETITOR' },
{ name: 'Joey Saia', wca_id: '2017SAIA01', title: 'COMPETITOR' },
{ name: 'John Short', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Jonathan Esparaz', wca_id: '2013ESPA01', title: 'STAFF' },
{ name: 'Joon Song', wca_id: '2019SONG21', title: 'COMPETITOR' },
{ name: 'Joshua Sandifer', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Julien Aram', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Justin Tong', wca_id: '2019TONG07', title: 'COMPETITOR' },
{ name: 'Kabir Bedi', wca_id: '2018BEDI01', title: 'COMPETITOR' },
{ name: 'Kairui Huang', wca_id: '2015HUAN51', title: 'COMPETITOR' },
{ name: 'Katie Crouse', wca_id: '2019CROU01', title: 'COMPETITOR' },
{ name: 'Kendall Frey', wca_id: '2019FREY02', title: 'COMPETITOR' },
{ name: 'Kevin Tang', wca_id: '2017TANG21', title: 'STAFF' },
{ name: 'Kieran Savoy', wca_id: '2019SAVO02', title: 'COMPETITOR' },
{ name: 'Koda Arthur Cobierski', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Kyle Keating', wca_id: '2015KEAT01', title: 'COMPETITOR' },
{ name: 'Kyria Sztainbok', wca_id: '2018SZTA01', title: 'STAFF' },
{ name: 'Larry Shi', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Leo Min-Bedford', wca_id: '2014MINB01', title: 'COMPETITOR' },
{ name: 'LianCheng Guo', wca_id: '2016GUOL01', title: 'COMPETITOR' },
{ name: 'Louis Cormier', wca_id: '2010CORM02', title: 'COMPETITOR' },
{ name: 'Lucas Jacobs', wca_id: '2018JACO10', title: 'COMPETITOR' },
{ name: 'Lucas Nieuwland', wca_id: '2018NIEU01', title: 'COMPETITOR' },
{ name: 'Luke Byleveld', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Maheer Huq', wca_id: '2017HUQM01', title: 'NEW COMPETITOR' },
{ name: 'Marco Yang', wca_id: '2017YANG62', title: 'STAFF' },
{ name: 'Mark Leistra', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Mathew Niznansky', wca_id: '2018NIZN01', title: 'COMPETITOR' },
{ name: 'Matthew Krawczyk', wca_id: '2017KRAW02', title: 'COMPETITOR' },
{ name: 'Matthew Lee', wca_id: '2017LEEM03', title: 'COMPETITOR' },
{ name: 'Matthew Liu', wca_id: '2018LIUM06', title: 'COMPETITOR' },
{ name: 'Matthew Yu', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Max Xiong ', wca_id: '2015XION03', title: 'COMPETITOR' },
{ name: 'Michael Bradley', wca_id: '2018BRAD08', title: 'COMPETITOR' },
{ name: 'Michael Lit', wca_id: '2018LITM01', title: 'COMPETITOR' },
{ name: 'Michael Zheng', wca_id: '2015ZHEN17', title: 'STAFF' },
{ name: 'Nate Bachynski', wca_id: '2018BACH05', title: 'COMPETITOR' },
{ name: 'Nathan Pedro', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Nathaniel Vernon', wca_id: '2019VERN01', title: 'COMPETITOR' },
{ name: 'Nestor Sokhan', wca_id: '2016SOKH01', title: 'COMPETITOR' },
{ name: 'Newton Nguyen', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Nicholas Patterson', wca_id: '2016PATT02', title: 'COMPETITOR' },
{ name: 'Nicolas de Lottinville', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Nima Bolourchian', wca_id: '2017BOLO01', title: 'STAFF' },
{ name: 'Noah Bernstein', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Owain Buchnea', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Owen Guo', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Peter Ryland', wca_id: '2018RYLA01', title: 'COMPETITOR' },
{ name: 'Philip Chiang', wca_id: '2016CHIA07', title: 'STAFF' },
{ name: 'Ranran Zhao ', wca_id: '2017ZHAO44', title: 'COMPETITOR' },
{ name: 'Rares Bostan', wca_id: '2011BOST01', title: 'COMPETITOR' },
{ name: 'Ray Vince Ong', wca_id: '2012ONGR01', title: 'STAFF' },
{ name: 'Riley Brambell', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Roan Paone', wca_id: '2017PAON01', title: 'COMPETITOR' },
{ name: 'Ryan Minjun Cho', wca_id: '2014CHOR01', title: 'STAFF' },
{ name: 'Ryan Pin Harry', wca_id: '2015HARR01', title: 'COMPETITOR' },
{ name: 'Ryan Wu', wca_id: '2017WURY01', title: 'STAFF' },
{ name: 'Sami Mokatren', wca_id: '2019MOKA01', title: 'COMPETITOR' },
{ name: 'Sarah Strong', wca_id: '2007STRO01', title: 'DELEGATE' },
{ name: 'Sebastian Ciuperca', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Sebastian Virág', wca_id: '2019VIRA01', title: 'COMPETITOR' },
{ name: 'Shameel Abdullah', wca_id: '2008ABDU01', title: 'COMPETITOR' },
{ name: 'Shanglin Ye', wca_id: '2013YESH01', title: 'STAFF' },
{ name: 'Shashwat Pratap', wca_id: '2015PRAT03', title: 'COMPETITOR' },
{ name: 'Stanley Wang', wca_id: '2017WANS05', title: 'COMPETITOR' },
{ name: 'Stefano Coulter', wca_id: '2018COUL01', title: 'COMPETITOR' },
{ name: 'Tarandeep Mittal', wca_id: '2014MITT02', title: 'STAFF' },
{ name: 'Thomas van Leeuwen', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Thompson Clarke', wca_id: '2008CLAR01', title: 'COMPETITOR' },
{ name: 'Tin Huang', wca_id: '2019HUAN05', title: 'COMPETITOR' },
{ name: 'Tommy Madison', wca_id: '2017MADI01', title: 'COMPETITOR' },
{ name: 'Trystan Hem', wca_id: '2018HEMT01', title: 'COMPETITOR' },
{ name: 'Vera Beal', wca_id: '2018BEAL02', title: 'COMPETITOR' },
{ name: 'Vincent Ren', wca_id: '2019RENV01', title: 'COMPETITOR' },
{ name: 'Vladimir Fokow ', wca_id: '2018FOKO01', title: 'COMPETITOR' },
{ name: 'William Deinzer', wca_id: '2018DEIN01', title: 'COMPETITOR' },
{ name: 'William Fehr', wca_id: '2018FEHR01', title: 'COMPETITOR' },
{ name: 'Xiangji Kong', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Yair Korokhov', wca_id: '2015KORO03', title: 'COMPETITOR' },
{ name: 'Yibo Zhao', wca_id: '2019ZHAO46', title: 'COMPETITOR' },
{ name: 'Yiming Lu', wca_id: '2019LUYI03', title: 'COMPETITOR' },
{ name: 'Yu Fu', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Zachary Ludwig', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Zein Salloum', wca_id: '2019SALL02', title: 'COMPETITOR' },
{ name: 'Zhivko Radkov Dimitrov', wca_id: '2017DIMI01', title: 'COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'NEW COMPETITOR' },
{ name: 'Richard Yi', wca_id: '', title: 'VOLUNTEER' },
{ name: 'Wendy Nieuwland', wca_id: '', title: 'VOLUNTEER' },
{ name: 'Michelle Walker', wca_id: '', title: 'VOLUNTEER' },
{ name: 'Michael Strong', wca_id: '', title: 'VOLUNTEER' },
{ name: 'Carla Abarca', wca_id: '',  title: 'VOLUNTEER' },
{ name: 'Chris Thomson', wca_id: '',  title: 'SCORETAKER' },
{ name: '_____________', wca_id: '',  title: 'VOLUNTEER' },
{ name: '_____________', wca_id: '',  title: 'VOLUNTEER' },
{ name: '_____________', wca_id: '',  title: 'VOLUNTEER' },
{ name: '_____________', wca_id: '',  title: 'VOLUNTEER' },
]
