window.sizeChanges = {
	'Ajeet Singh Chana': '58px',
	'Amruth Arunkumar': '58px',
	'Mathew Niznansky': '58px',
	'Matthew Krawczyk': '58px',
	'Nicholas Patterson': '58px',
	'Aris Efstathopoulos': '56px', 
	'Kevin Jacob Rajesh': '56px', 
	'Sebastian Ciuperca': '56px', 
	'Nicolas de Lottinville': '54px', 
	'Hisham Ahmed Khan': '52px', 
	'Jensen Belen-Brown': '52px', 
	'Koda Arthur Cobierski': '50px', 
	'Thomas van Leeuwen': '50px', 
	'Arjun Soundar Hariram': '48px', 
	'Zhivko Radkov Dimitrov': '46px',
}

window.competitors = [
{ name: 'Aaron Elliott Kriss', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Aaron King', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Abdullah Gulab', id: '2014GULA02', country: 'Pakistan', title: 'DELEGATE' },
{ name: 'Adam Vanderwal', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Adi Gausman', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Ajeet Singh Chana', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Alan Jia', id: '2017JIAA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Alex Chernish', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Alex Jung', id: '2018JUNG02', country: 'Korea', title: 'COMPETITOR' },
{ name: 'Alyssa Esparaz', id: '2014ESPA01', country: 'Canada', title: 'STAFF' },
{ name: 'Amruth Arunkumar', id: '', country: 'India', title: 'NEW COMPETITOR' },
{ name: 'Andrew Song', id: '2019SONG28', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Andry Rakoto', id: '2016RAKO02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Anthony Nguyen', id: '2018NGUY40', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Aris Efstathopoulos', id: '', country: 'Greece', title: 'NEW COMPETITOR' },
{ name: 'Arjun Soundar Hariram', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Arturo Pico', id: '2018PICO02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Avner', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Ayan Iqbal', id: '2018IQBA02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Bart Podhorski', id: '2019PODH01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ben Madison', id: '2016MADI02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ben Rockman', id: '2014ROCK01', country: 'Canada', title: 'STAFF' },
{ name: 'Benjamin Kyle', id: '2016KYLE01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Benson Lau', id: '2019LAUB01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Bill Wang', id: '2010WANG68', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Blaeden Kohout', id: '2019KOHO01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Blaize Kohout', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Brady Metherall', id: '2009METH01', country: 'Canada', title: 'STAFF' },
{ name: 'Braeden Klaehn', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Braeden Malda', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Brennen Lin', id: '2016LINB01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Brody Oleksyn', id: '', country: 'USA', title: 'NEW COMPETITOR' },
{ name: 'Bryce Oleksyn', id: '', country: 'USA', title: 'NEW COMPETITOR' },
{ name: 'Carson Carrasco', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Charles Goertz', id: '2017GOER01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Cheng Han Huo', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Christian Eifert', id: '2019EIFE01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Cole Woodcock', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Colin Gawthroupe', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Connor DeLuca', id: '2012DELU01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Dave Campbell', id: '2005CAMP01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Dave Deriches', id: '2018DERI02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Derek Kong', id: '2017KONG08', country: 'Canada', title: 'STAFF' },
{ name: 'Derek Walker', id: '2019WALK02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Edmund Yong', id: '2018YONG03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Elias Arovuo', id: '2018AROV01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Emma Kennedy', id: '2019KENN02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Erik Lee', id: '2018LEEE05', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ethan Campbell', id: '2019CAMP02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ethan Erez', id: '2017EREZ01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ethan Greenberg', id: '2015GREE11', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ethan Honest', id: '2019HONE03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ethan Yeung', id: '2019YEUN02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Fatima Gulab', id: '2015GULA01', country: 'Pakistan', title: 'STAFF' },
{ name: 'Flora Chan', id: '2019CHAN12', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Gavin Chen', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Geoffrey Stefanov', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Geoffrey Stevens', id: '2017STEV03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Henry Hughes', id: '2015HUGH02', country: 'Canada', title: 'STAFF' },
{ name: 'Henry Siebertz', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Henry Sun', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Hisham Ahmed Khan', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Hudson Tranmer', id: '2019TRAN03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Huy Nguyen', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Iain Holla', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Io McKay', id: '2018MCKA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ishan Saini', id: '2019SAIN08', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jack Costa', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Jack Engledow', id: '2013ENGL01', country: 'USA', title: 'COMPETITOR' },
{ name: 'Jack Walsh', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Jacob Eoin Gipp', id: '2016GIPP01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'James Hocevar', id: '2016HOCE02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jensen Belen-Brown', id: '2016BELE02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jerry Guo', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Jim Wang', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Joe Vander Veen', id: '2013VEEN01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'John Short', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Jonathan Esparaz', id: '2013ESPA01', country: 'Canada', title: 'STAFF' },
{ name: 'Joon Song', id: '2019SONG21', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Joshua Sandifer', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Julien Aram', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Kabir Bedi', id: '2018BEDI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Kairui Huang', id: '2015HUAN51', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Katie Crouse', id: '2019CROU01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Kendall Frey', id: '2019FREY02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Kevin Jacob Rajesh', id: '', country: 'India', title: 'NEW COMPETITOR' },
{ name: 'Kevin Tang', id: '2017TANG21', country: 'Canada', title: 'STAFF' },
{ name: 'Kieran Savoy', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Koda Arthur Cobierski', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Kyle Keating', id: '2015KEAT01', country: 'USA', title: 'COMPETITOR' },
{ name: 'Kyria Sztainbok', id: '2018SZTA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Larry Shi', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Leo Min-Bedford', id: '2014MINB01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'LianCheng Guo', id: '2016GUOL01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Louis Cormier', id: '2010CORM02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Lucas Jacobs', id: '2018JACO10', country: 'Saint Kitts and Nevis', title: 'COMPETITOR' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Luke Byleveld', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Maheer Huq', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Marco Yang', id: '2017YANG62', country: 'Canada', title: 'STAFF' },
{ name: 'Mark Leistra', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Mathew Niznansky', id: '2018NIZN01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Matthew Krawczyk', id: '2017KRAW02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Matthew Liu', id: '2018LIUM06', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Matthew Yu', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Max Xiong ', id: '2015XION03', country: 'China', title: 'COMPETITOR' },
{ name: 'Michael Bradley', id: '2018BRAD08', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Michael Lit', id: '2018LITM01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Michael Zheng', id: '2015ZHEN17', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Nate Bachynski', id: '2018BACH05', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Nathan Pedro', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Nathaniel Vernon', id: '2019VERN01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Newton Nguyen', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Nicholas Patterson', id: '2016PATT02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Nicolas de Lottinville', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', country: 'Canada', title: 'STAFF' },
{ name: 'Noah Bernstein', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Owain Buchnea', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Owen Guo', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Peter Ryland', id: '2018RYLA01', country: 'Australia', title: 'COMPETITOR' },
{ name: 'Philip Chiang', id: '2016CHIA07', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ranran Zhao ', id: '2017ZHAO44', country: 'China', title: 'COMPETITOR' },
{ name: 'Ray Vince Ong', id: '2012ONGR01', country: 'Canada', title: 'STAFF' },
{ name: 'Riley Brambell', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Roan Paone', id: '2017PAON01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ryan Minjun Cho', id: '2014CHOR01', country: 'Canada', title: 'STAFF' },
{ name: 'Ryan Pin Harry', id: '2015HARR01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ryan Wu', id: '2017WURY01', country: 'Canada', title: 'STAFF' },
{ name: 'Sami Mokatren', id: '2019MOKA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Sarah Strong', id: '2007STRO01', country: 'Canada', title: 'DELEGATE' },
{ name: 'Sebastian Ciuperca', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Sebastian Virág', id: '2019VIRA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Shameel Abdullah', id: '2008ABDU01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Shanglin Ye', id: '2013YESH01', country: 'Canada', title: 'STAFF' },
{ name: 'Shashwat Pratap', id: '2015PRAT03', country: 'India', title: 'COMPETITOR' },
{ name: 'Stanley Wang', id: '2017WANS05', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Stefano Coulter', id: '2018COUL01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Tarandeep Mittal', id: '2014MITT02', country: 'Canada', title: 'STAFF' },
{ name: 'Thomas van Leeuwen', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Tin Huang', id: '2019HUAN05', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Tommy Madison', id: '2017MADI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Trystan Hem', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Vera Beal', id: '2018BEAL02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Vincent Ren', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Vladimir Fokow ', id: '2018FOKO01', country: 'Belarus', title: 'COMPETITOR' },
{ name: 'William Deinzer', id: '2018DEIN01', country: 'USA', title: 'COMPETITOR' },
{ name: 'William Fehr', id: '2018FEHR01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Xiangji Kong', id: '', country: 'China', title: 'NEW COMPETITOR' },
{ name: 'Yair Korokhov', id: '2015KORO03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Yibo Zhao', id: '2019ZHAO46', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Yiming Lu', id: '2019LUYI03', country: 'China', title: 'COMPETITOR' },
{ name: 'Zachary Ludwig', id: '', country: 'Canada', title: 'NEW COMPETITOR' },
{ name: 'Zein Salloum', id: '2019SALL02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Zhivko Radkov Dimitrov', id: '2017DIMI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Richard Yi', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Wendy Nieuwland', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Michelle Walker', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Michael Strong', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
]
