window.sizeChanges = {
	'Maddox Stoughton': '58px', 
	'Alexander Adamski': '56px', 
	'Jack Joseph Sliwka': '56px',
	'Finlay Bouffard Lima': '54px',
	'Zachary Flansburgh': '54px',
	'Chandler Scheurkogel': '50px',
	'Docité Oren Schandry': '50px',
	'Shakohentehtha Elijah': '48px',
	'Kiawentsiawehon Elijah': '46px',
	'Aarush Anantha Prakash': '44px',
}

window.competitors = [
{ name: 'Aarush Anantha Prakash', id: '', title: 'NEW COMPETITOR' },
{ name: 'Adam Zhou', id: '', title: 'NEW COMPETITOR' },
{ name: 'Aidan O\'Brien', id: '', title: 'NEW COMPETITOR' },
{ name: 'Aiden Valentino', id: '2019VALE20', title: 'COMPETITOR' },
{ name: 'Albert G. Tahan', id: '2018TAHA01', title: 'COMPETITOR' },
{ name: 'Alex Maass', id: '2011MAAS01', title: 'COMPETITOR' },
{ name: 'Alexander Adamski', id: '', title: 'NEW COMPETITOR' },
{ name: 'Alli Swanchak', id: '', title: 'NEW COMPETITOR' },
{ name: 'Andrea Mitchell', id: '2018MITC05', title: 'COMPETITOR' },
{ name: 'Andrew Miller', id: '2019MILL06', title: 'COMPETITOR' },
{ name: 'Annabelle Sun', id: '', title: 'NEW COMPETITOR' },
{ name: 'Brady Williams', id: '', title: 'NEW COMPETITOR' },
{ name: 'Brandon Davis', id: '', title: 'NEW COMPETITOR' },
{ name: 'Brandon Davis', id: '2019DAVI16', title: 'COMPETITOR' },
{ name: 'Brandt Davis', id: '', title: 'NEW COMPETITOR' },
{ name: 'Brennen Lin', id: '2016LINB01', title: 'COMPETITOR' },
{ name: 'Brody Oleksyn', id: '2019OLEK01', title: 'COMPETITOR' },
{ name: 'Bryce Oleksyn', id: '2019OLEK02', title: 'COMPETITOR' },
{ name: 'Caleb Kearney', id: '2018KEAR02', title: 'COMPETITOR' },
{ name: 'Cali Oleksyn', id: '', title: 'NEW COMPETITOR' },
{ name: 'Chandler Scheurkogel', id: '2019SCHE06', title: 'COMPETITOR' },
{ name: 'Colden Buzzell', id: '', title: 'NEW COMPETITOR' },
{ name: 'Colin Miller', id: '', title: 'NEW COMPETITOR' },
{ name: 'Colin Miller', id: '2019MILL07', title: 'COMPETITOR' },
{ name: 'Derek Bennett', id: '2017BENN10', title: 'COMPETITOR' },
{ name: 'Docité Oren Schandry', id: '2019SCHA03', title: 'COMPETITOR' },
{ name: 'Edward Caine', id: '', title: 'NEW COMPETITOR' },
{ name: 'Elijah Essig', id: '', title: 'NEW COMPETITOR' },
{ name: 'Ethan Cobos', id: '2019COBO01', title: 'ORGANIZER' },
{ name: 'Ethan Coolidge', id: '2017COOL02', title: 'COMPETITOR' },
{ name: 'Evan Liu', id: '2009LIUE01', title: 'DELEGATE' },
{ name: 'Everett Gorman', id: '2019GORM04', title: 'COMPETITOR' },
{ name: 'Finlay Bouffard Lima', id: '', title: 'NEW COMPETITOR' },
{ name: 'Forrest Li', id: '', title: 'NEW COMPETITOR' },
{ name: 'Heath Flick', id: '', title: 'NEW COMPETITOR' },
{ name: 'Henry Cabezas', id: '', title: 'NEW COMPETITOR' },
{ name: 'Holden Lester', id: '2019LEST02', title: 'COMPETITOR' },
{ name: 'Hunter Otis', id: '', title: 'NEW COMPETITOR' },
{ name: 'Jack Herrick', id: '', title: 'NEW COMPETITOR' },
{ name: 'Jack Joseph Sliwka', id: '', title: 'NEW COMPETITOR' },
{ name: 'Jack Nguyen', id: '', title: 'NEW COMPETITOR' },
{ name: 'Jack Ryan', id: '2015RYAN02', title: 'COMPETITOR' },
{ name: 'Jacky Chen', id: '', title: 'NEW COMPETITOR' },
{ name: 'Jeremy Norbut', id: '', title: 'NEW COMPETITOR' },
{ name: 'Jess Mitchell', id: '2018MITC03', title: 'COMPETITOR' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', title: 'COMPETITOR' },
{ name: 'Joseph Tahan', id: '', title: 'NEW COMPETITOR' },
{ name: 'Kai Savage', id: '', title: 'NEW COMPETITOR' },
{ name: 'Kallen Miller', id: '', title: 'NEW COMPETITOR' },
{ name: 'Kiawentsiawehon Elijah', id: '', title: 'NEW COMPETITOR' },
{ name: 'Kobe Balin', id: '2012BALI01', title: 'COMPETITOR' },
{ name: 'Liam Forth', id: '2018FORT04', title: 'COMPETITOR' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', title: 'COMPETITOR' },
{ name: 'Maddox Stoughton', id: '', title: 'NEW COMPETITOR' },
{ name: 'Matthew Ficarra', id: '', title: 'NEW COMPETITOR' },
{ name: 'Matthew Jacobs', id: '2016JACO04', title: 'COMPETITOR' },
{ name: 'Matthew Rich', id: '2015RICH02', title: 'COMPETITOR' },
{ name: 'Nathan Smith', id: '', title: 'NEW COMPETITOR' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', title: 'COMPETITOR' },
{ name: 'Noah Melita', id: '2018MELI05', title: 'COMPETITOR' },
{ name: 'Oliver Bender', id: '', title: 'NEW COMPETITOR' },
{ name: 'Owen Donnelly', id: '', title: 'NEW COMPETITOR' },
{ name: 'Patrick Ponce', id: '2012PONC02', title: 'COMPETITOR' },
{ name: 'Ryan Pin Harry', id: '2015HARR01', title: 'COMPETITOR' },
{ name: 'Ryan Wu', id: '2017WURY01', title: 'COMPETITOR' },
{ name: 'Samuel Knoll', id: '2015KNOL01', title: 'COMPETITOR' },
{ name: 'Samuel O\'Sullivan', id: '2018OSUL02', title: 'COMPETITOR' },
{ name: 'Sarah Strong', id: '2007STRO01', title: 'DELEGATE' },
{ name: 'Shakohentehtha Elijah', id: '2019ELIJ01', title: 'COMPETITOR' },
{ name: 'Simon Aguilar', id: '', title: 'NEW COMPETITOR' },
{ name: 'Tara Lenzo', id: '2018LENZ01', title: 'COMPETITOR' },
{ name: 'Thayne Carlo', id: '', title: 'NEW COMPETITOR' },
{ name: 'Thayne Carlo', id: '2017CARL07', title: 'COMPETITOR' },
{ name: 'Tony Lenzo', id: '2018LENZ02', title: 'COMPETITOR' },
{ name: 'Tyler Lenzo', id: '', title: 'NEW COMPETITOR' },
{ name: 'Tyler Malloy', id: '', title: 'NEW COMPETITOR' },
{ name: 'Vladimir Sahagun', id: '2015SAHA01', title: 'COMPETITOR' },
{ name: 'Zachary Flansburgh', id: '', title: 'NEW COMPETITOR' },
{ name: 'Wendy Nieuwland', id: '', title: 'VOLUNTEER' },
{ name: 'Sophie Pedzich', id: '',  title: 'VOLUNTEER' },
{ name: 'Emi Perdan', id: '',  title: 'VOLUNTEER' },
{ name: 'Christine Cobos', id: '',  title: 'VOLUNTEER' },
{ name: 'Aidan Russel', id: '',  title: 'VOLUNTEER' },
{ name: 'Rachel Brophy', id: '',  title: 'VOLUNTEER' },
{ name: '_____________', id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', id: '',  title: 'COMPETITOR' },
{ name: '_____________', id: '',  title: 'COMPETITOR' },
{ name: '_____________', id: '',  title: 'COMPETITOR' },
{ name: '_____________', id: '',  title: 'COMPETITOR' },
{ name: '_____________', id: '',  title: 'COMPETITOR' },
{ name: '_____________', id: '',  title: 'COMPETITOR' },
{ name: '_____________', id: '',  title: 'VOLUNTEER' },
{ name: '_____________', id: '',  title: 'VOLUNTEER' },
{ name: '_____________', id: '',  title: 'VOLUNTEER' },
{ name: '_____________', id: '',  title: 'VOLUNTEER' },
]
