window.size58 = []
window.size56 = ['Alexander Marmora', 'Owen Bailey-Braun', 'Sebastian Johnston']
window.size54 = []
window.size52 = ['Cristoff Joseph Barlis', 'Jensen Belen-Brown', 'Christopher Saint-Dic']
window.size50 = ['Docité Oren Schandry'] 
window.size48 = [] 
window.size46 = ['Brandon Arnoldo Taylor', 'Émilie Millar Desjardins', 'Zhivko Radkov Dimitrov'] 
window.size44 = [] 
window.size42 = ['Diego Rodriguez-Ramirez']

window.competitors = [
{ name: 'Abdullah Gulab', id: '2014GULA02', country: 'Pakistan', title: 'STAFF' },
{ name: 'Ajay Saini', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Alain Cormier', id: '2011CORM02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Alexander Marmora', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Andrei Almeyda', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Aryan Ved', id: '2018VEDA02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ben Rockman', id: '2014ROCK01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Blake Thompson', id: '2010THOM03', country: 'USA', title: 'STAFF' },
{ name: 'Brady Metherall', id: '2009METH01', country: 'Canada', title: 'STAFF' },
{ name: 'Brandon Arnoldo Taylor', id: '2019TAYL03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Brant Holbein', id: '2014HOLB01', country: 'Canada', title: 'ORGANIZER' },
{ name: 'Brennen Lin', id: '2016LINB01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Chi Wang', id: 'New Competitor', country: 'China', title: 'COMPETITOR' },
{ name: 'Craig Bouchard', id: '2005BOUC01', country: 'Canada', title: 'STAFF' },
{ name: 'Cristoff Joseph Barlis', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Dave Deriches', id: '2018DERI02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Diego Rodriguez-Ramirez', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Docité Oren Schandry', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Émilie Millar Desjardins', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ethan Erez', id: '2017EREZ01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Geoffrey Stevens', id: '2017STEV03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jensen Belen-Brown', id: '2016BELE02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jonathan Esparaz', id: '2013ESPA01', country: 'Canada', title: 'STAFF' },
{ name: 'Joshua Feran', id: '2011FERA01', country: 'USA', title: 'STAFF' },
{ name: 'Joshua Graham', id: '2013GRAH01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Joshua Jones', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Krish Ved', id: '2018VEDK01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Leo Min-Bedford', id: '2014MINB01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Louis Cormier', id: '2010CORM02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Louise Cormier', id: '2013CORM01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Luka Bailey-Braun', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Mannix Freyseng', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Marcus Mosley', id: '2016MOSL01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Matthew Krawczyk', id: '2017KRAW02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Nazar Sushkov', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', country: 'Canada', title: 'STAFF' },
{ name: 'Owen Bailey-Braun', id: '2019BAIL01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Peter Douthwright', id: '2007DOUT01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ray Vince Ong', id: '2012ONGR01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Roan Paone', id: '2017PAON01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ryan Wu', id: '2017WURY01', country: 'Canada', title: 'STAFF' },
{ name: 'Sam Mogil', id: '2018MOGI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Sarah Strong', id: '2007STRO01', country: 'Canada', title: 'DELEGATE' },
{ name: 'Sebastian Johnston', id: 'New Competitor', country: 'USA', title: 'COMPETITOR' },
{ name: 'Shanglin Ye', id: '2013YESH01', country: 'Canada', title: 'STAFF' },
{ name: 'Tin Huang', id: '2019HUAN05', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Tristan Raycroft', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Vivian Kay', id: '2019KAYV01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'William Fehr', id: '2018FEHR01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Yash Sarap', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Zhivko Radkov Dimitrov', id: '2017DIMI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Chris Thomson', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Wendy Nieuwland', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Kianna Holbein', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Parantap Bhat', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Colby White', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Samuel Bylerian', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Elodie Roy', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Christopher Saint-Dic', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Ethan Howard', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Lorie Rodrique', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'COMPETITOR' },
{ name: '_____________', id: '', country: '', title: 'COMPETITOR' },
{ name: '_____________', id: '', country: '', title: 'COMPETITOR' },
{ name: '_____________', id: '', country: '', title: 'COMPETITOR' },
{ name: '_____________', id: '', country: '', title: 'COMPETITOR' },
{ name: '_____________', id: '', country: '', title: 'COMPETITOR' },
{ name: '_____________', id: '', country: '', title: 'COMPETITOR' },
{ name: '_____________', id: '', country: '', title: 'COMPETITOR' },
{ name: '_____________', id: '', country: '', title: 'COMPETITOR' },
{ name: '_____________', id: '', country: '', title: 'COMPETITOR' },
{ name: '_____________', id: '', country: '', title: 'COMPETITOR' },
{ name: '_____________', id: '', country: '', title: 'COMPETITOR' },
]
