window.size58 = []
window.size56 = ['Alexander Marmora', 'Owen Bailey-Braun', 'Sebastian Johnston']
window.size54 = []
window.size52 = ['Cristoff Joseph Barlis', 'Jensen Belen-Brown', 'Christopher Saint-Dic', 'Hisham Ahmed Khan']
window.size50 = ['Docité Oren Schandry'] 
window.size48 = [] 
window.size46 = ['Brandon Arnoldo Taylor', 'Émilie Millar Desjardins', 'Zhivko Radkov Dimitrov', 'Sebastian Desaulniers', 'Devin Russell MacInnis'] 
window.size44 = [] 
window.size42 = ['Diego Rodriguez-Ramirez']

window.competitors = [
{ name: 'Aiden Brazeau', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Alan Jia', id: '2017JIAA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Alex Jung', id: '2018JUNG02', country: 'Korea', title: 'COMPETITOR' },
{ name: 'Alex Knegt', id: '2018KNEG01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Andrea Mitchell', id: '2018MITC05', country: 'USA', title: 'COMPETITOR' },
{ name: 'Andrii Denysenko ', id: '2017DENY01', country: 'Ukraine', title: 'COMPETITOR' },
{ name: 'Arhaan Sareen', id: '2017SARE03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ben Bergen', id: '2015BERG10', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ben Madison', id: '2016MADI02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ben Worden', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Brady Metherall', id: '2009METH01', country: 'Canada', title: 'STAFF' },
{ name: 'Brady Walintschek', id: '2019WALI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Brant Holbein', id: '2014HOLB01', country: 'Canada', title: 'STAFF' },
{ name: 'Brian Ignacio', id: '2019IGNA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Briar Barron', id: '2016BARR15', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Colin Cayen', id: '2015CAYE02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Daniel Daoust', id: '2017DAOU01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Daniel Papernov', id: '2019PAPE01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Daniel Pavelich', id: '2015PAVE01', country: 'USA', title: 'COMPETITOR' },
{ name: 'Danny Li', id: '2018LIDA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Dave Campbell', id: '2005CAMP01', country: 'Canada', title: 'DELEGATE' },
{ name: 'Dave Deriches', id: '2018DERI02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'David Drobner', id: '2018DROB01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Derek Walker', id: '2019WALK02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Devin Russell MacInnis', id: '2017MACI07', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Docité Oren Schandry', id: '2019SCHA03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Emile Compion', id: '2007COMP01', country: 'South Africa', title: 'STAFF' },
{ name: 'Erik Lee', id: '2018LEEE05', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ethan Erez', id: '2017EREZ01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Gabrielle Morasse', id: '2013MORA08', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Hisham Ahmed Khan', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ian Yeh', id: '2017YEHI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jason Nguyen', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jensen Belen-Brown', id: '2016BELE02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jess Mitchell', id: '2018MITC03', country: 'USA', title: 'COMPETITOR' },
{ name: 'Jesse Hek', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Joseph Rouben', id: '2018ROUB01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Joshua Graham', id: '2013GRAH01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Josiah Smits', id: '2018SMIT30', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Kairui Huang', id: '2015HUAN51', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Kevin Xu', id: '2018XUKE03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Liam Hohertz', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Liam Orovec', id: '2014OROV01', country: 'Canada', title: 'DELEGATE' },
{ name: 'LianCheng Guo', id: '2016GUOL01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Louis Cormier', id: '2010CORM02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Mathew Niznansky', id: '2018NIZN01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Matthew Jennings', id: '2018JENN02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Matthew Krawczyk', id: '2017KRAW02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Matthew Lee', id: '2017LEEM03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Matthew Liu', id: '2018LIUM06', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Max Murphy', id: '2016MURP05', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Max Xiong ', id: '2015XION03', country: 'China', title: 'COMPETITOR' },
{ name: 'Michael Bradley', id: '2018BRAD08', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Michael Russell', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Nazar Sushkov', id: '2019SUSH02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Nicholas Patterson', id: '2016PATT02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', country: 'Canada', title: 'STAFF' },
{ name: 'Omar Ellabban', id: '2018ELLA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Owen Bailey-Braun', id: '2019BAIL01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Peter Douthwright', id: '2007DOUT01', country: 'Canada', title: 'STAFF' },
{ name: 'Peter Stevens', id: '2019STEV01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Richard Madison', id: '2017MADI03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Roan Paone', id: '2017PAON01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ryan Hinds', id: '2018HIND01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ryan Minjun Cho', id: '2014CHOR01', country: 'Canada', title: 'STAFF' },
{ name: 'Ryan Pin Harry', id: '2015HARR01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ryan Wu', id: '2017WURY01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Sam Mogil', id: '2018MOGI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Samuel Moran', id: '2015MORA08', country: 'USA', title: 'COMPETITOR' },
{ name: 'Sarah Strong', id: '2007STRO01', country: 'Canada', title: 'DELEGATE' },
{ name: 'Saro Vanayan', id: '2019VANA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Sascha Pugar', id: '2015PUGA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Sebastian Desaulniers', id: '2018DESA05', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Thomas Imada', id: '2018IMAD01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Tin Huang', id: '2019HUAN05', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Tommy Madison', id: '2017MADI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Vera Beal', id: '2018BEAL02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Wenda Jiang ', id: '2013JIAN11', country: 'China', title: 'COMPETITOR' },
{ name: 'William Fehr', id: '2018FEHR01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Alec McDonald', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Chris Thomson', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Dana Banihani', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Daniel Von Euw', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Nate Tan', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Sara Jung', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Wendy Nieuwland', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Catharine Benzie', id: '', country: '', title: 'VENDOR' },
{ name: 'Sarah\'s Dad', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
]
