window.sizeChanges = {
	'Jude Wheeler-Dee': '58px',
	'Maddox Stoughton': '58px', 
	'Mathew Niznansky': '58px',
	'Alexander Adamski': '56px', 
	'Jack Joseph Sliwka': '56px', 
	'Myles David Suchma': '56px',
	'Owen Bailey-Braun': '56px',
	'Finlay Bouffard Lima': '54px', 
	'Zachary Flansburgh': '54px', 
	'Jensen Belen-Brown': '52px',
	'Chandler Scheurkogel': '50px', 
	'Docité Oren Schandry': '50px', 
	'Matthew Karunakaran': '50px', //
	'Viswathiha Mylashan': '50px', //
	'Ronan William Odell': '50px', //
	'Pramathaditya Pathak': '50px', //
	'Koda Arthur Cobierski': '48px',
	'Massimo Corrado Caia': '48px',
	'Shakohentehtha Elijah': '48px', 
	'Devin Russell MacInnis': '46px', //
	'Kiawentsiawehon Elijah': '46px', 
	'Zhivko Radkov Dimitrov': '46px', 
	'Aarush Anantha Prakash': '44px',
	'Branavan Keethabaskaran': '40px', //
	'Vaishnav SriSai Ravulaparthi' : '38px', //
	'Mohammedreza Moghaddam': '36px', //
}

window.competitors = [
{ name: 'Abdullah Gulab', id: '2014GULA02', title: 'DELEGATE' },
{ name: 'Christian Aiello', id: '2017AIEL01', title: 'COMPETITOR' },
{ name: 'Ian Yeh', id: '2017YEHI01', title: 'COMPETITOR' },
{ name: 'Kai Savage', id: '2020SAVA04', title: 'COMPETITOR' },
{ name: 'Matthew Garcia', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Owen Bailey-Braun', id: '2019BAIL01', title: 'COMPETITOR' },
{ name: 'Sebastian Virág', id: '2019VIRA01', title: 'COMPETITOR' },
{ name: 'Catharine Benzie', id: '', title: 'VENDOR & SPONSOR' },
{ name: 'Adithya Medihala', id: '2019MEDI16', title: 'COMPETITOR' },
{ name: 'Colin Gawthroupe', id: '2019GAWT01', title: 'COMPETITOR' },
{ name: 'Isaac Lau', id: '2016LAUI01', title: 'COMPETITOR' },
{ name: 'Keegan Phillips', id: '2019PHIL06', title: 'COMPETITOR' },
{ name: 'Matthew Karunakaran', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Owen Muldoon', id: '2018MULD01', title: 'COMPETITOR' },
{ name: 'Setu Marathe', id: '2017MARA04', title: 'COMPETITOR' },
{ name: 'Emile Compion', id: '2007COMP01', title: 'VENDOR & SPONSOR' },
{ name: 'Aiden Yim', id: '2019YIMA01', title: 'COMPETITOR' },
{ name: 'Dave Deriches', id: '2018DERI02', title: 'COMPETITOR' },
{ name: 'Jack Costa', id: '2019COST11', title: 'COMPETITOR' },
{ name: 'Kevin Xu', id: '2018XUKE03', title: 'COMPETITOR' },
{ name: 'Matthew Lee', id: '2017LEEM03', title: 'COMPETITOR' },
{ name: 'Parker Piekosz', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Sébastien Bernard', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Wendy Niuewland', id: '', title: 'VOLUNTEER' },
{ name: 'Alan Diaz', id: '2018DIAZ29', title: 'COMPETITOR' },
{ name: 'David Burchill', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Jack Smith', id: '2019SMIT10', title: 'COMPETITOR' },
{ name: 'Koda Arthur Cobierski', id: '2019COBI01', title: 'COMPETITOR' },
{ name: 'Max Murphy', id: '2016MURP05', title: 'STAFF' },
{ name: 'Prahaas Kotni', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Shanglin Ye', id: '2013YESH01', title: 'STAFF' },
{ name: 'Michelle Walker', id: '', title: 'VOLUNTEER' },
{ name: 'Alex Ning', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Derek Kong', id: '2017KONG08', title: 'STAFF' },
{ name: 'Jacky Chen', id: '2020CHEN04', title: 'COMPETITOR' },
{ name: 'Krish Ved', id: '2018VEDK01', title: 'COMPETITOR' },
{ name: 'Max Xiong ', id: '2015XION03', title: 'COMPETITOR' },
{ name: 'Pramathaditya Pathak', id: '2018PATH02', title: 'COMPETITOR' },
{ name: 'Shelby Russell', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Carla Abarca', id: '', title: 'VOLUNTEER' },
{ name: 'Alyssa Esparaz', id: '2014ESPA01', title: 'STAFF' },
{ name: 'Derrick Ha', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'James Hocevar', id: '2016HOCE02', title: 'COMPETITOR' },
{ name: 'Larry Shi', id: '2019SHIL03', title: 'COMPETITOR' },
{ name: 'Michael Bradley', id: '2018BRAD08', title: 'COMPETITOR' },
{ name: 'Prosper Huang', id: '2018HUAP02', title: 'COMPETITOR' },
{ name: 'Stanley Wang', id: '2017WANS05', title: 'COMPETITOR' },
{ name: 'Tanya Fehr', id: '', title: 'VOLUNTEER' },
{ name: 'Andrew Yeung', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Devin Russell MacInnis', id: '2017MACI07', title: 'COMPETITOR' },
{ name: 'James Wang', id: '2019WANJ15', title: 'COMPETITOR' },
{ name: 'Leon Qian', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Michael Zheng', id: '2015ZHEN17', title: 'STAFF' },
{ name: 'Ray Vince Ong', id: '2012ONGR01', title: 'COMPETITOR' },
{ name: 'Stefano Coulter', id: '2018COUL01', title: 'COMPETITOR' },
{ name: 'Neil Hanlon', id: '',  title: 'VOLUNTEER' },
{ name: 'Andry Rakoto', id: '2016RAKO02', title: 'COMPETITOR' },
{ name: 'Docité Oren Schandry', id: '2019SCHA03', title: 'COMPETITOR' },
{ name: 'Jensen Belen-Brown', id: '2016BELE02', title: 'COMPETITOR' },
{ name: 'Liam Forth', id: '2018FORT04', title: 'COMPETITOR' },
{ name: 'Minjae Kim', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Rene Desaulniers', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Tarandeep Mittal', id: '2014MITT02', title: 'STAFF' },
{ name: '_____________', id: '',  title: 'VOLUNTEER' },
{ name: 'Aryan Ved', id: '2018VEDA02', title: 'COMPETITOR' },
{ name: 'Dylan Yihan Dai', id: '2018DAID01', title: 'COMPETITOR' },
{ name: 'Jess Mitchell', id: '2018MITC03', title: 'COMPETITOR' },
{ name: 'Liam Savarino', id: '2018SAVA01', title: 'COMPETITOR' },
{ name: 'Mohammedreza Moghaddam', id: '2019MOGH01', title: 'COMPETITOR' },
{ name: 'Richard Li', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Thomas Imada', id: '2018IMAD01', title: 'COMPETITOR' },
{ name: '_____________', id: '',  title: 'VOLUNTEER' },
{ name: 'Atharva Medihala', id: '2019MEDI09', title: 'COMPETITOR' },
{ name: 'Elliot Mauricette', id: '2019MAUR04', title: 'COMPETITOR' },
{ name: 'Jesse Wang', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Lin Salvo', id: '2019SALV05', title: 'COMPETITOR' },
{ name: 'Myles David Suchma', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Roan Paone', id: '2017PAON01', title: 'COMPETITOR' },
{ name: 'Tin Huang', id: '2019HUAN05', title: 'COMPETITOR' },
{ name: '_____________', id: '',  title: 'VOLUNTEER' },
{ name: 'Austin Collins', id: '2019COLL08', title: 'COMPETITOR' },
{ name: 'Emily Hu', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Jessica Ying', id: '2017YING02', title: 'COMPETITOR' },
{ name: 'Louis Cormier', id: '2010CORM02', title: 'COMPETITOR' },
{ name: 'Nathan Terpstra', id: '2019TERP03', title: 'COMPETITOR' },
{ name: 'Robert Nelson', id: '2011NELS01', title: 'COMPETITOR' },
{ name: 'Toyo Witzmann', id: '2018WITZ01', title: 'COMPETITOR' },
{ name: '_____________', id: '',  title: 'VOLUNTEER' },
{ name: 'Branavan Keethabaskaran', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Emmanuel Intac', id: '2018INTA01', title: 'COMPETITOR' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', title: 'COMPETITOR' },
{ name: 'Louise Cormier', id: '2013CORM01', title: 'COMPETITOR' },
{ name: 'Nathan Wang', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Ronan William Odell', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Tristan Beaulne', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Brandon Chu', id: '2018CHUB06', title: 'COMPETITOR' },
{ name: 'Ethan Yeung', id: '2019YEUN02', title: 'COMPETITOR' },
{ name: 'Joey Saia', id: '2017SAIA01', title: 'COMPETITOR' },
{ name: 'Lucas Jacobs', id: '2018JACO10', title: 'COMPETITOR' },
{ name: 'Nicole Wang', id: '2018WANN03', title: 'COMPETITOR' },
{ name: 'Rose Zheng', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Vaishnav SriSai Ravulaparthi', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Brennen Lin', id: '2016LINB01', title: 'COMPETITOR' },
{ name: 'Evan Rowland', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'John Travolo', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', title: 'ORGANIZER' },
{ name: 'Nihaas Kotni', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Ryan Wu', id: '2017WURY01', title: 'STAFF' },
{ name: 'Viswathiha Mylashan', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Brian Fudem', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Garrett Banks', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Jonathan Esparaz', id: '2013ESPA01', title: 'STAFF' },
{ name: 'Marco Yang', id: '2017YANG62', title: 'STAFF' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', title: 'COMPETITOR' },
{ name: 'Rymand Moarefi', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'William Fehr', id: '2018FEHR01', title: 'STAFF' },
{ name: 'Caleb Chang', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Harry George', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Jonathan Ferraioli', id: '2017FERR12', title: 'COMPETITOR' },
{ name: 'Marko Young', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Noah Tremblay', id: '2019TREM02', title: 'COMPETITOR' },
{ name: 'Samson Wu', id: '2015WUSA01', title: 'COMPETITOR' },
{ name: 'Youssef Ali', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Callum Smith', id: '2019SMIT09', title: 'COMPETITOR' },
{ name: 'Hongda Wu', id: '2017WUHO01', title: 'COMPETITOR' },
{ name: 'Joon Song', id: '2019SONG21', title: 'STAFF' },
{ name: 'Massimo Corrado Caia', id: '2019CAIA01', title: 'COMPETITOR' },
{ name: 'Omar Ellabban', id: '2018ELLA01', title: 'COMPETITOR' },
{ name: 'Sarah Strong', id: '2007STRO01', title: 'DELEGATE' },
{ name: 'Zhivko Radkov Dimitrov', id: '2017DIMI01', title: 'COMPETITOR' },
{ name: 'Chang Shi ', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Iain Holla', id: '2019HOLL05', title: 'COMPETITOR' },
{ name: 'Jude Wheeler-Dee', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Mathew Niznansky', id: '2018NIZN01', title: 'COMPETITOR' },
{ name: 'Orion Donovan', id: '2016DONO02', title: 'COMPETITOR' },
{ name: 'Scotty Watkins', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Chris Thomson', id: '', title: 'SCORETAKER' },

]
