window.sizeChanges = {
	'Ajeet Singh Chana': '58px',
	'Amruth Arunkumar': '58px',
	'Mathew Niznansky': '58px',
	'Matthew Krawczyk': '58px',
	'Nicholas Patterson': '58px',
	'Aris Efstathopoulos': '56px',
	'Kevin Jacob Rajesh': '56px',
	'Sebastian Ciuperca': '56px',
	'Noah Quentin Iddison': '50px',
	'Nicolas de Lottinville': '52px',
	'Mirab Aleem Siddiqui': '52px',
	'Hisham Ahmed Khan': '52px',
	'Jensen Belen-Brown': '52px',
	'Thomas van Leeuwen': '50px',
	'Koda Arthur Cobierski': '48px',
	'Massimo Corrado Caia': '48px',
	'Arjun Soundar Hariram': '48px',
	'Kayden James Cosman' : '46px',
	'Zhivko Radkov Dimitrov': '46px',
	'David Ignacio Gonzalez Lugo': '46px',
}

window.competitors = [
{ name: 'Aadi Chopra', id: '2019CHOP01', title: 'COMPETITOR' },
{ name: 'Abdullah Gulab', id: '2014GULA02', title: 'DELEGATE' },
{ name: 'Adrian Arrojo', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Ajeet Singh Chana', id: '2019CHAN56', title: 'COMPETITOR' },
{ name: 'Alan Jia', id: '2017JIAA01', title: 'COMPETITOR' },
{ name: 'Alex Chernish', id: '2019CHER20', title: 'COMPETITOR' },
{ name: 'Alex Jung', id: '2018JUNG02', title: 'COMPETITOR' },
{ name: 'Andrew Pokornik', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Andrew Poon', id: '2016POON02', title: 'COMPETITOR' },
{ name: 'Andrew Song', id: '2019SONG28', title: 'COMPETITOR' },
{ name: 'Arhaan Sareen', id: '2017SARE03', title: 'COMPETITOR' },
{ name: 'Aryan Sehgal', id: '2015SEHG01', title: 'COMPETITOR' },
{ name: 'Bart Podhorski', id: '2019PODH01', title: 'COMPETITOR' },
{ name: 'Benjamin Bryer', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Brennen Lin', id: '2016LINB01', title: 'COMPETITOR' },
{ name: 'Brody Clark', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Christian Eifert', id: '2019EIFE01', title: 'COMPETITOR' },
{ name: 'Ciara Doody', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Darian Rezvan', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Dave Deriches', id: '2018DERI02', title: 'COMPETITOR' },
{ name: 'David Ignacio Gonzalez Lugo', id: '2016LUGO02', title: 'COMPETITOR' },
{ name: 'David John', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Derek Walker', id: '2019WALK02', title: 'COMPETITOR' },
{ name: 'Dominic Majkic', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Edwin Deng', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Elias Arovuo', id: '2018AROV01', title: 'COMPETITOR' },
{ name: 'Elijah Dyck', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Elijah Gonzales', id: '2016GONZ35', title: 'COMPETITOR' },
{ name: 'Emma Kennedy', id: '2019KENN02', title: 'COMPETITOR' },
{ name: 'Emmanuel Intac', id: '2018INTA01', title: 'COMPETITOR' },
{ name: 'Ethan Campbell', id: '2019CAMP02', title: 'COMPETITOR' },
{ name: 'Ethan Erez', id: '2017EREZ01', title: 'COMPETITOR' },
{ name: 'Ethan Yeung', id: '2019YEUN02', title: 'COMPETITOR' },
{ name: 'Frank Perdikakis', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Harsha Paladugu', id: '2017PALA08', title: 'COMPETITOR' },
{ name: 'Hayden Kim', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Hudson Tranmer', id: '2019TRAN03', title: 'COMPETITOR' },
{ name: 'Iain So', id: '2019SOIA01', title: 'COMPETITOR' },
{ name: 'Jacob Jones', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'James Hocevar', id: '2016HOCE02', title: 'COMPETITOR' },
{ name: 'Jared Kiers', id: '2019KIER03', title: 'COMPETITOR' },
{ name: 'Jensen Belen-Brown', id: '2016BELE02', title: 'COMPETITOR' },
{ name: 'Jim Wang', id: '2019WANJ20', title: 'COMPETITOR' },
{ name: 'Jimmy Sijie Zhang', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', title: 'COMPETITOR' },
{ name: 'Joey Saia', id: '2017SAIA01', title: 'COMPETITOR' },
{ name: 'John Boersema', id: '2017BOER01', title: 'COMPETITOR' },
{ name: 'Joon Song', id: '2019SONG21', title: 'COMPETITOR' },
{ name: 'Joshua Sandifer', id: '2019SAND16', title: 'COMPETITOR' },
{ name: 'Josiah Smits', id: '2018SMIT30', title: 'COMPETITOR' },
{ name: 'Justin Raimbault', id: '2018RAIM02', title: 'COMPETITOR' },
{ name: 'Kabir Bedi', id: '2018BEDI01', title: 'COMPETITOR' },
{ name: 'Katie Crouse', id: '2019CROU01', title: 'COMPETITOR' },
{ name: 'Kayden James Cosman', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Kevin Xu', id: '2018XUKE03', title: 'COMPETITOR' },
{ name: 'Kirk J. Rees', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Kyle Corbin', id: '2018CORB01', title: 'COMPETITOR' },
{ name: 'Kyria Sztainbok', id: '2018SZTA01', title: 'STAFF' },
{ name: 'Larry Shi', id: '2019SHIL03', title: 'COMPETITOR' },
{ name: 'Leo Min-Bedford', id: '2014MINB01', title: 'COMPETITOR' },
{ name: 'Leo Stewart', id: '2018STEW09', title: 'COMPETITOR' },
{ name: 'Liam Forth', id: '2018FORT04', title: 'COMPETITOR' },
{ name: 'LianCheng Guo', id: '2016GUOL01', title: 'COMPETITOR' },
{ name: 'Lin Salvo', id: '2019SALV05', title: 'COMPETITOR' },
{ name: 'Louis Cormier', id: '2010CORM02', title: 'COMPETITOR' },
{ name: 'Lucas Jacobs', id: '2018JACO10', title: 'COMPETITOR' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', title: 'COMPETITOR' },
{ name: 'Mark Leistra', id: '2019LEIS02', title: 'COMPETITOR' },
{ name: 'Mason Day', id: '2018DAYM01', title: 'COMPETITOR' },
{ name: 'Massimo Corrado Caia', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Mathew Niznansky', id: '2018NIZN01', title: 'COMPETITOR' },
{ name: 'Matthew Krawczyk', id: '2017KRAW02', title: 'COMPETITOR' },
{ name: 'Matthew Lee', id: '2017LEEM03', title: 'COMPETITOR' },
{ name: 'Matthew Obrovac', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Matthew Yu', id: '2019YUMA03', title: 'COMPETITOR' },
{ name: 'Max Xiong', id: '2015XION03', title: 'COMPETITOR' },
{ name: 'Matteo Sorge', id: '2019SORG01', title: 'COMPETITOR' },
{ name: 'Merick Jeffares', id: '2018JEFF02', title: 'COMPETITOR' },
{ name: 'Mirab Aleem Siddiqui', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Mustafa Ahmed', id: '2019AHME12', title: 'COMPETITOR' },
{ name: 'Nathan Pedro', id: '2019PEDR03', title: 'COMPETITOR' },
{ name: 'Nathan Terpstra', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Nathaniel Vernon', id: '2019VERN01', title: 'COMPETITOR' },
{ name: 'Nicholas Patterson', id: '2016PATT02', title: 'COMPETITOR' },
{ name: 'Nicholas Seto', id: '2018SETO01', title: 'COMPETITOR' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', title: 'COMPETITOR' },
{ name: 'Nitya Shah', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Noah Quentin Iddison', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Owain Buchnea', id: '2019BUCH07', title: 'COMPETITOR' },
{ name: 'Rex Li', id: '2019LIRE01', title: 'COMPETITOR' },
{ name: 'Roan Paone', id: '2017PAON01', title: 'COMPETITOR' },
{ name: 'Ryan Pin Harry', id: '2015HARR01', title: 'COMPETITOR' },
{ name: 'Ryan Salonen', id: '2018SALO03', title: 'COMPETITOR' },
{ name: 'Ryan Simon', id: '2018SIMO09', title: 'COMPETITOR' },
{ name: 'Ryan Wu', id: '2017WURY01', title: 'STAFF' },
{ name: 'Samuel Bryer', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Sarah Strong', id: '2007STRO01', title: 'DELEGATE' },
{ name: 'Saro Vanayan', id: '2019VANA01', title: 'COMPETITOR' },
{ name: 'Sebastian Virág', id: '2019VIRA01', title: 'COMPETITOR' },
{ name: 'Setu Marathe', id: '2017MARA04', title: 'COMPETITOR' },
{ name: 'Shanglin Ye', id: '2013YESH01', title: 'COMPETITOR' },
{ name: 'Stefano Coulter', id: '2018COUL01', title: 'COMPETITOR' },
{ name: 'Thomas Imada', id: '2018IMAD01', title: 'COMPETITOR' },
{ name: 'Tin Huang', id: '2019HUAN05', title: 'COMPETITOR' },
{ name: 'Thomas Introcaso', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Toyo Witzmann', id: '2018WITZ01', title: 'COMPETITOR' },
{ name: 'Tristan Guichelaar', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Trystan Hem', id: '2018HEMT01', title: 'COMPETITOR' },
{ name: 'Willem McLellan', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'William Deinzer', id: '2018DEIN01', title: 'COMPETITOR' },
{ name: 'William Fehr', id: '2018FEHR01', title: 'COMPETITOR' },
{ name: 'William Weber', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Wyatt Atchison', id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Chris Thomson', id: '', title: 'SCORETAKER' },
{ name: 'Catharine Benzie', id: '', title: 'VENDOR & SPONSOR' },
{ name: 'Emile Compion', id: '', title: 'VENDOR & SPONSOR' },
{ name: 'Wendy Nieuwland', id: '', title: 'VOLUNTEER' },
{ name: 'Michelle Walker', id: '', title: 'VOLUNTEER' },
{ name: 'Carla Abarca', id: '', title: 'VOLUNTEER' },
{ name: 'Steven Kong', id: '', title: 'VOLUNTEER' },
{ name: 'Aaron Albrecht', id: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '',  title: 'VOLUNTEER' },
{ name: '_____________', id: '',  title: 'VOLUNTEER' },
{ name: '_____________', id: '',  title: 'VOLUNTEER' },
{ name: '_____________', id: '',  title: 'VOLUNTEER' },
{ name: '_____________', id: '',  title: 'VOLUNTEER' },
{ name: '_____________', id: '',  title: 'VOLUNTEER' },
{ name: '_____________', id: '',  title: 'COMPETITOR' },
{ name: '_____________', id: '',  title: 'COMPETITOR' },
{ name: '_____________', id: '',  title: 'COMPETITOR' },
{ name: '_____________', id: '',  title: 'COMPETITOR' },
{ name: '_____________', id: '',  title: 'COMPETITOR' },
{ name: '_____________', id: '',  title: 'COMPETITOR' },
{ name: '_____________', id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', id: '',  title: 'NEW COMPETITOR' },
]
