window.sizeChanges = {
	'Ajeet Singh Chana': '58px',
	'Amruth Arunkumar': '58px',
	'Mathew Niznansky': '58px',
	'Matthew Krawczyk': '58px',
	'Nicholas Patterson': '58px',
	'Aris Efstathopoulos': '56px',
	'Kevin Jacob Rajesh': '56px',
	'Sebastian Ciuperca': '56px',
	'Noah Quentin Iddison': '50px',
	'Nicolas de Lottinville': '52px',
	'Mirab Aleem Siddiqui': '52px',
	'Hisham Ahmed Khan': '52px',
	'Jensen Belen-Brown': '52px',
	'Thomas van Leeuwen': '50px',
	'Koda Arthur Cobierski': '48px',
	'Massimo Corrado Caia': '48px',
	'Arjun Soundar Hariram': '48px',
	'Kayden James Cosman' : '46px',
	'Zhivko Radkov Dimitrov': '46px',
	'David Ignacio Gonzalez Lugo': '46px',
}

window.competitors = [
{ name: 'Aadi Chopra', wca_id: '2019CHOP01', title: 'COMPETITOR' },
{ name: 'Abdullah Gulab', wca_id: '2014GULA02', title: 'DELEGATE' },
{ name: 'Adithya Medihala', wca_id: '', title: 'NEW COMPETITOR' },
{ name: 'Adrian Arrojo', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Ajeet Singh Chana', wca_id: '2019CHAN56', title: 'COMPETITOR' },
{ name: 'Alan Jia', wca_id: '2017JIAA01', title: 'COMPETITOR' },
{ name: 'Alex Chernish', wca_id: '2019CHER20', title: 'COMPETITOR' },
{ name: 'Alex Jung', wca_id: '2018JUNG02', title: 'COMPETITOR' },
{ name: 'Andrew Pokornik', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Andrew Poon', wca_id: '2016POON02', title: 'COMPETITOR' },
{ name: 'Andrew Song', wca_id: '2019SONG28', title: 'COMPETITOR' },
{ name: 'Arhaan Sareen', wca_id: '2017SARE03', title: 'COMPETITOR' },
{ name: 'Aryan Sehgal', wca_id: '2015SEHG01', title: 'COMPETITOR' },
{ name: 'Atharva Medihala', wca_id: '2019MEDI09', title: 'COMPETITOR' },
{ name: 'Bart Podhorski', wca_id: '2019PODH01', title: 'COMPETITOR' },
{ name: 'Benjamin Bryer', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Brennen Lin', wca_id: '2016LINB01', title: 'COMPETITOR' },
{ name: 'Brody Clark', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Christian Eifert', wca_id: '2019EIFE01', title: 'COMPETITOR' },
{ name: 'Ciara Doody', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Darian Rezvan', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Dave Deriches', wca_id: '2018DERI02', title: 'COMPETITOR' },
{ name: 'David Ignacio Gonzalez Lugo', wca_id: '2016LUGO02', title: 'COMPETITOR' },
{ name: 'David John', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Derek Walker', wca_id: '2019WALK02', title: 'COMPETITOR' },
{ name: 'Dominic Majkic', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Edwin Deng', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Elias Arovuo', wca_id: '2018AROV01', title: 'COMPETITOR' },
{ name: 'Elijah Dyck', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Elijah Gonzales', wca_id: '2016GONZ35', title: 'COMPETITOR' },
{ name: 'Emma Kennedy', wca_id: '2019KENN02', title: 'COMPETITOR' },
{ name: 'Emmanuel Intac', wca_id: '2018INTA01', title: 'COMPETITOR' },
{ name: 'Ethan Campbell', wca_id: '2019CAMP02', title: 'COMPETITOR' },
{ name: 'Ethan Erez', wca_id: '2017EREZ01', title: 'COMPETITOR' },
{ name: 'Ethan Yeung', wca_id: '2019YEUN02', title: 'COMPETITOR' },
{ name: 'Frank Perdikakis', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Harsha Paladugu', wca_id: '2017PALA08', title: 'COMPETITOR' },
{ name: 'Hayden Kim', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Hudson Tranmer', wca_id: '2019TRAN03', title: 'COMPETITOR' },
{ name: 'Iain So', wca_id: '2019SOIA01', title: 'COMPETITOR' },
{ name: 'Jacob Jones', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'James Hocevar', wca_id: '2016HOCE02', title: 'COMPETITOR' },
{ name: 'Jared Kiers', wca_id: '2019KIER03', title: 'COMPETITOR' },
{ name: 'Jensen Belen-Brown', wca_id: '2016BELE02', title: 'COMPETITOR' },
{ name: 'Jim Wang', wca_id: '2019WANJ20', title: 'COMPETITOR' },
{ name: 'Jimmy Sijie Zhang', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Joaquin Abarca', wca_id: '2017ABAR02', title: 'COMPETITOR' },
{ name: 'Joey Saia', wca_id: '2017SAIA01', title: 'COMPETITOR' },
{ name: 'John Boersema', wca_id: '2017BOER01', title: 'COMPETITOR' },
{ name: 'Joon Song', wca_id: '2019SONG21', title: 'COMPETITOR' },
{ name: 'Joshua Sandifer', wca_id: '2019SAND16', title: 'COMPETITOR' },
{ name: 'Josiah Smits', wca_id: '2018SMIT30', title: 'COMPETITOR' },
{ name: 'Justin Raimbault', wca_id: '2018RAIM02', title: 'COMPETITOR' },
{ name: 'Kabir Bedi', wca_id: '2018BEDI01', title: 'COMPETITOR' },
{ name: 'Katie Crouse', wca_id: '2019CROU01', title: 'COMPETITOR' },
{ name: 'Kayden James Cosman', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Kevin Xu', wca_id: '2018XUKE03', title: 'COMPETITOR' },
{ name: 'Kirk J. Rees', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Kyle Corbin', wca_id: '2018CORB01', title: 'COMPETITOR' },
{ name: 'Kyria Sztainbok', wca_id: '2018SZTA01', title: 'STAFF' },
{ name: 'Larry Shi', wca_id: '2019SHIL03', title: 'COMPETITOR' },
{ name: 'Leo Min-Bedford', wca_id: '2014MINB01', title: 'COMPETITOR' },
{ name: 'Leo Stewart', wca_id: '2018STEW09', title: 'COMPETITOR' },
{ name: 'Liam Forth', wca_id: '2018FORT04', title: 'COMPETITOR' },
{ name: 'LianCheng Guo', wca_id: '2016GUOL01', title: 'COMPETITOR' },
{ name: 'Lin Salvo', wca_id: '2019SALV05', title: 'COMPETITOR' },
{ name: 'Louis Cormier', wca_id: '2010CORM02', title: 'COMPETITOR' },
{ name: 'Lucas Jacobs', wca_id: '2018JACO10', title: 'COMPETITOR' },
{ name: 'Lucas Nieuwland', wca_id: '2018NIEU01', title: 'COMPETITOR' },
{ name: 'Mark Leistra', wca_id: '2019LEIS02', title: 'COMPETITOR' },
{ name: 'Mason Day', wca_id: '2018DAYM01', title: 'COMPETITOR' },
{ name: 'Massimo Corrado Caia', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Mathew Niznansky', wca_id: '2018NIZN01', title: 'COMPETITOR' },
{ name: 'Matthew Krawczyk', wca_id: '2017KRAW02', title: 'COMPETITOR' },
{ name: 'Matthew Lee', wca_id: '2017LEEM03', title: 'COMPETITOR' },
{ name: 'Matthew Obrovac', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Matthew Yu', wca_id: '2019YUMA03', title: 'COMPETITOR' },
{ name: 'Max Xiong', wca_id: '2015XION03', title: 'COMPETITOR' },
{ name: 'Matteo Sorge', wca_id: '2019SORG01', title: 'COMPETITOR' },
{ name: 'Merick Jeffares', wca_id: '2018JEFF02', title: 'COMPETITOR' },
{ name: 'Mirab Aleem Siddiqui', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Mustafa Ahmed', wca_id: '2019AHME12', title: 'COMPETITOR' },
{ name: 'Nathan Pedro', wca_id: '2019PEDR03', title: 'COMPETITOR' },
{ name: 'Nathan Terpstra', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Nathaniel Vernon', wca_id: '2019VERN01', title: 'COMPETITOR' },
{ name: 'Nicholas Patterson', wca_id: '2016PATT02', title: 'COMPETITOR' },
{ name: 'Nicholas Seto', wca_id: '2018SETO01', title: 'COMPETITOR' },
{ name: 'Nima Bolourchian', wca_id: '2017BOLO01', title: 'COMPETITOR' },
{ name: 'Nitya Shah', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Noah Quentin Iddison', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Owain Buchnea', wca_id: '2019BUCH07', title: 'COMPETITOR' },
{ name: 'Rex Li', wca_id: '2019LIRE01', title: 'COMPETITOR' },
{ name: 'Roan Paone', wca_id: '2017PAON01', title: 'COMPETITOR' },
{ name: 'Ryan Pin Harry', wca_id: '2015HARR01', title: 'COMPETITOR' },
{ name: 'Ryan Salonen', wca_id: '2018SALO03', title: 'COMPETITOR' },
{ name: 'Ryan Simon', wca_id: '2018SIMO09', title: 'COMPETITOR' },
{ name: 'Ryan Wu', wca_id: '2017WURY01', title: 'STAFF' },
{ name: 'Samuel Bryer', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Sarah Strong', wca_id: '2007STRO01', title: 'DELEGATE' },
{ name: 'Saro Vanayan', wca_id: '2019VANA01', title: 'COMPETITOR' },
{ name: 'Sebastian Virág', wca_id: '2019VIRA01', title: 'COMPETITOR' },
{ name: 'Setu Marathe', wca_id: '2017MARA04', title: 'COMPETITOR' },
{ name: 'Shanglin Ye', wca_id: '2013YESH01', title: 'COMPETITOR' },
{ name: 'Stefano Coulter', wca_id: '2018COUL01', title: 'COMPETITOR' },
{ name: 'Thomas Imada', wca_id: '2018IMAD01', title: 'COMPETITOR' },
{ name: 'Tin Huang', wca_id: '2019HUAN05', title: 'COMPETITOR' },
{ name: 'Thomas Introcaso', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Toyo Witzmann', wca_id: '2018WITZ01', title: 'COMPETITOR' },
{ name: 'Tristan Guichelaar', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Trystan Hem', wca_id: '2018HEMT01', title: 'COMPETITOR' },
{ name: 'Willem McLellan', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'William Deinzer', wca_id: '2018DEIN01', title: 'COMPETITOR' },
{ name: 'William Fehr', wca_id: '2018FEHR01', title: 'COMPETITOR' },
{ name: 'William Weber', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Wyatt Atchison', wca_id: 'New Competitor', title: 'NEW COMPETITOR' },
{ name: 'Chris Thomson', wca_id: '', title: 'SCORETAKER' },
{ name: 'Catharine Benzie', wca_id: '', title: 'VENDOR & SPONSOR' },
{ name: 'Emile Compion', wca_id: '', title: 'VENDOR & SPONSOR' },
{ name: 'Wendy Nieuwland', wca_id: '', title: 'VOLUNTEER' },
{ name: 'Michelle Walker', wca_id: '', title: 'VOLUNTEER' },
{ name: 'Carla Abarca', wca_id: '', title: 'VOLUNTEER' },
{ name: 'Steven Kong', wca_id: '', title: 'VOLUNTEER' },
{ name: 'Ethan Calleja', wca_id: '', title: 'VOLUNTEER' },
{ name: 'Aaron Albrecht', wca_id: '', title: 'VOLUNTEER' },
{ name: '_____________', wca_id: '',  title: 'VOLUNTEER' },
{ name: '_____________', wca_id: '',  title: 'VOLUNTEER' },
{ name: '_____________', wca_id: '',  title: 'VOLUNTEER' },
{ name: '_____________', wca_id: '',  title: 'VOLUNTEER' },
{ name: '_____________', wca_id: '',  title: 'VOLUNTEER' },
{ name: '_____________', wca_id: '',  title: 'VOLUNTEER' },
{ name: '_____________', wca_id: '',  title: 'COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'NEW COMPETITOR' },
{ name: '_____________', wca_id: '',  title: 'NEW COMPETITOR' },
]
