window.competitors = [
{ name: 'Abdullah Gulab', id: '2014GULA02', country: 'Pakistan', title: 'STAFF' },
{ name: 'Abishua Thomas', id: '2013THOM03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Adrian Panszczyk', id: '2015PANS01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Adrian Stan', id: '2016STAN12', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Adyan Hossain', id: '2018HOSS01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Alan Jia', id: '2017JIAA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Alyssa Esparaz', id: '2014ESPA01', country: '' ,title: 'VOLUNTEER' },
{ name: 'Andrew Dai', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Arturo Pico', id: '2018PICO02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ben Madison', id: '2016MADI02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Bill Wang', id: '2010WANG68', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Brady Metherall', id: '2009METH01', country: 'Canada', title: 'STAFF' },
{ name: 'Brennen Lin', id: '2016LINB01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Caden Ly', id: '2016LYCA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Chris Thomson', id: '', country: '' ,title: 'VOLUNTEER' },
// { name: 'Christopher Pakenham', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' }, size 48
{ name: 'Colin Cayen', id: '2015CAYE02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Colleen Geerlinks', id: '2014GEER01', country: 'Canada', title: 'STAFF' },
{ name: 'Darren Tang', id: '2018TANG01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Dave Campbell', id: '2005CAMP01', country: 'Canada', title: 'DELEGATE' },
{ name: 'Derek Kong', id: '2017KONG08', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Derek Shen', id: '2016SHEN12', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Dimitri Huinink', id: '2018HUIN01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Dwayne Almeida', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Dylan Yihan Dai', id: '2018DAID01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Elijah Gonzales', id: '2016GONZ35', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Emile Compion', id: '2007COMP01', country: 'South Africa', title: 'STAFF' },
{ name: 'Evan Simanovskis', id: '2018SIMA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Finn Noel', id: '2017NOEL05', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Gabrielle Morasse', id: '2013MORA08', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ian Yeh', id: '2017YEHI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ibraheem Ahmed', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ibrahim Quraishi', id: '2018QURA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Isaac Lau', id: '2016LAUI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jack Boos', id: '2016BOOS01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jacob Eoin Gipp', id: '2016GIPP01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jake Lance', id: '2014LANC01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'James Hocevar', id: '2016HOCE02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jeffrey Draper', id: '2014DRAP01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jeriel Thomas', id: '2013THOM04', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jonathan Esparaz', id: '2013ESPA01', country: 'Canada', title: 'STAFF' },
{ name: 'Jonathan Liu', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jonathan Tan', id: '2009XIAT02', country: 'Malaysia', title: 'STAFF' },
{ name: 'Leo Min-Bedford', id: '2014MINB01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Liam Savarino', id: '2018SAVA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Louis Cormier', id: '2010CORM02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Lucas Jacobs', id: '2018JACO10', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Malcolm Zuzarte', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Marco Yang', id: '2017YANG62', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Matteo Hosdil', id: '2017HOSD01', country: 'Canada', title: 'COMPETITOR' },
// { name: 'Matthew Krawczyk', id: '2017KRAW02', country: 'Canada', title: 'COMPETITOR' }, size 56
{ name: 'Matthew Lee', id: '2017LEEM03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Max Murphy', id: '2016MURP05', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Max Sun', id: '2017SUNM02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Max Xiong', id: '2015XION03', country: 'China', title: 'COMPETITOR' },
{ name: 'Michael Fisher', id: '2017FISH03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Michael Rose', id: '2011ROSE03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Michael Strong', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: 'Michael Zheng', id: '2018ZHEN04', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Nastia Patrice', id: '2017PATR03', country: 'Canada', title: 'COMPETITOR' },
// { name: 'Nicholas Patterson', id: '2016PATT02', country: 'Canada', title: 'COMPETITOR' },size 56
{ name: 'Nima Bolourchian', id: '2017BOLO01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Owen Berg', id: '2018BERG03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Paula Stan', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: 'Peter Douthwright', id: '2007DOUT01', country: 'Canada', title: 'STAFF' },
{ name: 'Richard Madison', id: '2017MADI03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Rishith Nellippillil', id: '2013NELL01', country: 'India', title: 'COMPETITOR' },
{ name: 'Roan Paone', id: '2017PAON01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ryan Minjun Cho', id: '2014CHOR01', country: 'Canada', title: 'STAFF' },
{ name: 'Ryan Wu', id: '2017WURY01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Sam Mogil', id: '2018MOGI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Sarah Strong', id: '2007STRO01', country: 'Canada', title: 'DELEGATE' },
{ name: 'Sascha Pugar', id: '2015PUGA01', country: 'Canada', title: 'COMPETITOR' },
// { name: 'Sawyer Featherston', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },size 54
// { name: 'Sebastian Desaulniers', id: '2018DESA05', country: 'Canada', title: 'COMPETITOR' }, size 48
{ name: 'Seth Huygen', id: '2018HUYG01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Siddharth Kanwar', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Thompson Clarke', id: '2008CLAR01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Tommy Madison', id: '2017MADI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Wendy Nieuwland', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: 'William Shen', id: '2016SHEN13', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Wilton Kahgee', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Yusuf Sheikh', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' }, 
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' }, 
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' },
];
