window.size58 = []
window.size56 = []
window.size54 = []
window.size52 = ['Jensen Belen-Brown']
window.size50 = ['Docité Oren Schandry']
window.size48 = ['Sebastian Desaulniers'] 
window.size46 = [] 
window.size44 = [] 
window.size42 = []

window.competitors = [{ name: 'Abdullah Gulab', id: '2014GULA02', country: 'Pakistan', title: 'STAFF' },
{ name: 'Alan Jia', id: '2017JIAA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Alyssa Esparaz', id: '2014ESPA01', country: 'Canada', title: 'STAFF' },
{ name: 'Anthony Huang', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Arhaan Sareen', id: '2017SARE03', country: 'Canada', title: 'STAFF' },
{ name: 'Arturo Pico', id: '2018PICO02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Benson Lau', id: '2019LAUB01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Brady Metherall', id: '2009METH01', country: 'Canada', title: 'STAFF' },
{ name: 'Brant Holbein', id: '2014HOLB01', country: 'Canada', title: 'STAFF' },
{ name: 'Brendan Chan', id: '2018CHAN32', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Brennen Lin', id: '2016LINB01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Briar Barron', id: '2016BARR15', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Chen-Pin Sun ', id: '2017SUNC03', country: 'Taiwan', title: 'COMPETITOR' },
{ name: 'Craig Bouchard', id: '2005BOUC01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Darren Tang', id: '2018TANG01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Dave Campbell', id: '2005CAMP01', country: 'Canada', title: 'DELEGATE' },
{ name: 'David Shei', id: '2016SHEI03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Derek Kong', id: '2017KONG08', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Docité Oren Schandry', id: '2019SCHA03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Emma Kennedy', id: '2019KENN02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ethan Campbell', id: '2019CAMP02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ethan Erez', id: '2017EREZ01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ethan Yeung', id: '2019YEUN02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Fred Quong', id: '2015QUON01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Hudson Tranmer', id: '2019TRAN03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ian Yeh', id: '2017YEHI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Isaac Lau', id: '2016LAUI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ivan Tang', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jensen Belen-Brown', id: '2016BELE02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jihoon Kwon', id: '2015KWON02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jonathan Esparaz', id: '2013ESPA01', country: 'Canada', title: 'STAFF' },
{ name: 'Jonathan Tan', id: '2009XIAT02', country: 'Malaysia', title: 'STAFF' },
{ name: 'Kairui Huang', id: '2015HUAN51', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Leo Min-Bedford', id: '2014MINB01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Leon Kalish', id: '2017KALI05', country: 'Canada', title: 'COMPETITOR' },
{ name: 'LianCheng Guo', id: '2016GUOL01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Linus Kunath', id: '2017KUNA01', country: 'Germany', title: 'COMPETITOR' },
{ name: 'Lucas Jacobs', id: '2018JACO10', country: 'Saint Kitts and Nevis', title: 'COMPETITOR' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Marco Yang', id: '2017YANG62', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Matthew Lee', id: '2017LEEM03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Maxen Morrison', id: '2018MORR04', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Michael Bradley', id: '2018BRAD08', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Nazar Sushkov', id: '2019SUSH02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Nicholas Leyesa', id: '2018LEYE01', country: 'USA', title: 'COMPETITOR' },
{ name: 'Nicholas Patterson', id: '2016PATT02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Nicholas Seto', id: '2018SETO01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Nicole Wang', id: '2018WANN03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', country: 'Canada', title: 'STAFF' },
{ name: 'Omar Ellabban', id: '2018ELLA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Roan Paone', id: '2017PAON01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Robert Chan', id: '2019CHAN25', country: 'USA', title: 'COMPETITOR' },
{ name: 'Ryan Minjun Cho', id: '2014CHOR01', country: 'Canada', title: 'STAFF' },
{ name: 'Ryan Pin Harry', id: '2015HARR01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ryan Wu', id: '2017WURY01', country: 'Canada', title: 'ORGANIZER' },
{ name: 'Sarah Strong', id: '2007STRO01', country: 'Canada', title: 'DELEGATE' },
{ name: 'Sascha Pugar', id: '2015PUGA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Sebastian Desaulniers', id: '2018DESA05', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Spencer Anderson', id: '2018ANDE06', country: 'USA', title: 'COMPETITOR' },
{ name: 'Stanley Wang', id: '2017WANS05', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Thompson Clarke', id: '2008CLAR01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Tin Huang', id: '2019HUAN05', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Vivian Kay', id: '2019KAYV01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Wenda Jiang ', id: '2013JIAN11', country: 'China', title: 'COMPETITOR' },
{ name: 'William Scully', id: '2019SCUL01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Isabel Yeh', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Wendy Nieuwland', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Rachel Wu', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Rayanne Wu', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'WeiWei Deng', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Zhi Wu', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Tiffany Feng', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Steven Liu', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
]
