window.size58 = []
window.size56 = []
window.size54 = ['Fabien Rakotonirina']
window.size52 = ['Nickolas Sweetland']
window.size50 = ['Pramathaditya Pathak', 'Yazan Al-Shawaqfeh']
window.size48 = ['Sebastian Desaulniers', 'Jensen Belen-Brown']
window.size46 = []
window.size44 = []
window.size42 = []

window.competitors = [
{ name: 'Aadi Chopra', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Abdullah Gulab', id: '2014GULA02', country: 'Pakistan', title: 'ORGANIZER' },
{ name: 'Alex Jung', id: '2018JUNG02', country: 'Korea', title: 'COMPETITOR' },
{ name: 'Alyssa Esparaz', id: '2014ESPA01', country: 'Canada', title: 'STAFF' },
{ name: 'Anda Su', id: '2014SUAN01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Andrea Mitchell', id: '2018MITC05', country: 'USA', title: 'COMPETITOR' },
{ name: 'Anne Bradford', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ansh Maru', id: '2017MARI10', country: 'USA', title: 'COMPETITOR' },
{ name: 'Anthony Nguyen', id: '2018NGUY40', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Austin Jordan Eng', id: '2016ENGA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ben Madison', id: '2016MADI02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ben Rockman', id: '2014ROCK01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Benson Lau', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Bernard Jia', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Bill Wang', id: '2010WANG68', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Brady McNicol', id: '2019MCNI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Brady Metherall', id: '2009METH01', country: 'Canada', title: 'STAFF' },
{ name: 'Brady Walintschek', id: '2019WALI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Brandon Chu', id: '2018CHUB06', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Brennen Lin', id: '2016LINB01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Brian Jin', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Briar Barron', id: '2016BARR15', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Brice Lan', id: '2017LANB01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Caleb Lee', id: '2018LEEC02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Calvin Dang', id: '2017DANG08', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Charles Gao', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Charles Goertz', id: '2017GOER01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Chen-Pin Sun ', id: '2017SUNC03', country: 'Taiwan', title: 'COMPETITOR' },
{ name: 'Clement Huang', id: '2018HUAN82', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Colleen Geerlinks', id: '2014GEER01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Daniel Phan', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Darren Tang', id: '2018TANG01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Dave Campbell', id: '2005CAMP01', country: 'Canada', title: 'DELEGATE' },
{ name: 'Dave Deriches', id: '2018DERI02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'David De Martin', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'David Drobner', id: '2018DROB01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'David Shei', id: '2016SHEI03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'David Tang', id: '2011TANG02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Devin MacInnis', id: '2017MACI07', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Dwayne Almeida', id: '2018ALME07', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Emile Compion', id: '2007COMP01', country: 'South Africa', title: 'STAFF' },
{ name: 'Ethan Erez', id: '2017EREZ01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ethan Tang', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ethan Yeung', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Evin Park', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Fabien Rakotonirina', id: '2017RAKO01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Fatima Gulab', id: '2015GULA01', country: 'Pakistan', title: 'COMPETITOR' },
{ name: 'Flora Chan', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Franklin Bai', id: '2017BAIF01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Fred Quong', id: '2015QUON01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Gabriel Austin', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Gavin Cole', id: '2016COLE04', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Geoffrey Stevens', id: '2017STEV03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Glenn Salvador', id: '2018SALV03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Harris Chan', id: '2007CHAN07', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Henry Hughes', id: '2015HUGH02', country: 'Canada', title: 'STAFF' },
{ name: 'Humza Qureshi', id: '2017QURE02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ian Yeh', id: '2017YEHI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ibrahim Quraishi', id: '2018QURA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ivan Krueger', id: '2016KRUE01', country: 'USA', title: 'COMPETITOR' },
{ name: 'Izaak VanSoelen', id: '2015VANS01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jack Boos', id: '2016BOOS01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jaden Soliven', id: '2017SOLI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jakub Balas', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jennifer Yu', id: '2018YUJE01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jensen Belen-Brown', id: '2016BELE02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jess Mitchell', id: '2018MITC03', country: 'USA', title: 'COMPETITOR' },
{ name: 'Joanne Zhou', id: '2017ZHOU50', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jonathan Chen', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Jonathan Esparaz', id: '2013ESPA01', country: 'Canada', title: 'ORGANIZER' },
{ name: 'Jonathan Tan', id: '2009XIAT02', country: 'Malaysia', title: 'COMPETITOR' },
{ name: 'Josh Bent', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Joshua Graham', id: '2013GRAH01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Josiah Smits', id: '2018SMIT30', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Julian Favell', id: '2013FAVE01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Justus Danielsen', id: '2016DANI08', country: 'USA', title: 'COMPETITOR' },
{ name: 'Kairui Huang', id: '2015HUAN51', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Kevin Tang', id: '2017TANG21', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Kevin Trinh', id: '2015TRIN04', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Kevin Xu', id: '2018XUKE03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Kyria Sztainbok', id: '2018SZTA01', country: 'Canada', title: 'STAFF' },
{ name: 'Leo Min-Bedford', id: '2014MINB01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Leo Stewart', id: '2018STEW09', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Liam Savarino', id: '2018SAVA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'LianCheng Guo', id: '2016GUOL01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Louis Cormier', id: '2010CORM02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Marco Yang', id: '2017YANG62', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Margaret Zhang', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Mark Antao', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Mason Day', id: '2018DAYM01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Matan Erez Keren', id: '2015KERE02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Matthew Krawczyk', id: '2017KRAW02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Matthew Lee', id: '2017LEEM03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Matthew Simpson', id: '2017SIMP04', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Max Sun', id: '2017SUNM02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Michael Colbert', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Michael Bradley', id: '2018BRAD08', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Michael Rose', id: '2011ROSE03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Michael Zheng', id: '2015ZHEN17', country: 'Canada', title: 'STAFF' },
{ name: 'Nahaeli Brunder', id: '2014BRUN02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Neel Shah', id: '2009SHAH04', country: 'Canada', title: 'STAFF' },
{ name: 'Nickolas Sweetland', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Nicole Wang', id: '2018WANN03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Omar Ellabban', id: '2018ELLA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ori Kaplan', id: '2019KAPL01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Owen Berg', id: '2018BERG03', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Palmer Berry', id: '2014BERR01', country: 'USA', title: 'COMPETITOR' },
{ name: 'Peter Douthwright', id: '2007DOUT01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Phillip Lewicki', id: '2012LEWI01', country: 'USA', title: 'COMPETITOR' },
{ name: 'Pramathaditya Pathak', id: '2018PATH02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Prosper Huang', id: '2018HUAP02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Quade Post', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Rachel Jin', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ranran Zhao ', id: '2017ZHAO44', country: 'China', title: 'COMPETITOR' },
{ name: 'Ray Vince Ong', id: '2012ONGR01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Richelle Bobadilla', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Rishith Nellippillil', id: '2013NELL01', country: 'India', title: 'COMPETITOR' },
{ name: 'Roan Paone', id: '2017PAON01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ronniel Ambat', id: '2018AMBA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ryan Minjun Cho', id: '2014CHOR01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Ryan Wu', id: '2017WURY01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Sam Mogil', id: '2018MOGI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Sameer Kumar', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Santiago Latino', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Sarah Strong', id: '2007STRO01', country: 'Canada', title: 'DELEGATE' },
{ name: 'Saro Vanayan', id: '2019CANA01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Sebastian Desaulniers', id: '2018DESA05', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Serena Hao', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Shanglin Ye', id: '2013YESH01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Stanley Wang', id: '2017WANS05', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Susan Krueger', id: '2018KRUE01', country: 'USA', title: 'COMPETITOR' },
{ name: 'Taha Ben Salah', id: '2015SALA03', country: 'Tunisia', title: 'COMPETITOR' },
{ name: 'Tarandeep Mehta', id: '2019MEHT01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Taylor Ellis', id: '2017ELLI04', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Thaddeus Krueger', id: '2016KRUE02', country: 'USA', title: 'COMPETITOR' },
{ name: 'Thomas Imada', id: '2018IMAD01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Thompson Clarke', id: '2008CLAR01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Tommy Madison', id: '2017MADI01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Tony Wang', id: '2011WANG06', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Toyo Witzmann', id: '2018WITZ01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Tsz Yeung Guan', id: '2018GUAN06', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Vera Beal', id: '2018BEAL02', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Vivian Kay', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'William Scully', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Yazan Al-Shawaqfeh', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Yonatan Jungreis', id: '2019JUNG01', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Yuxuan Li', id: 'New Competitor', country: 'Canada', title: 'COMPETITOR' },
{ name: 'Zonghan Qiao', id: 'New Competitor', country: 'China', title: 'COMPETITOR' },
{ name: 'Hayley Wong', id: '', country: '', title: 'VOLUNTEER' },
{ name: 'Joseph Ho', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
{ name: '_____________', id: '', country: '', title: 'VOLUNTEER' },
]
