window.competitors = [
{ name: 'Abdullah Gulab'},
{ name: 'Aiden Chan'},
{ name: 'Andrew Nguyen'},
{ name: 'Ben Bergen'},
{ name: 'Ben Rockman'},
{ name: 'Benson Lau'},
{ name: 'Brady Metherall'},
{ name: 'David Drobner'},
{ name: 'Joaquin Abarca'},
{ name: 'Jonathan Esparaz'},
{ name: 'Kevin Tang'},
{ name: 'Max Murphy'},
{ name: 'Max Sun'},
{ name: 'Nima Bolourchian'},
{ name: 'Owen Widdis'},
{ name: 'Ray Vince Ong'},
{ name: 'Roan Paone'},
{ name: 'Ryan Pin Harry'},
{ name: 'Ryan Wu'},
{ name: 'Sarah Strong'},
{ name: 'Sebastian Desaulniers'},
{ name: 'Thomas Imada'},
]
