window.mo3events =['6x6x6 Cube', '7x7x7 Cube', '3x3x3 Blindfolded', '4x4x4 Blindfolded', '5x5x5 Blindfolded', 'Mirror Blocks', 'Kilominx'];

window.cumulativeevents =['3x3x3 Blindfolded','5x5x5 Blindfolded'];

window.bo2events = ['3x3x3 Multi-Blind'];

window.competitors = [
{ line_1: '3x3x3 One-Handed', line_2: 'Round 1', line_3: 'Group 1 of 2'},
{ name: 'Bryce Davies', wca_id: '2019DAVI18', live_id: '4', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Group 1 of 2', cutoff: '1:30', limit: '2:30' }, 
{ name: 'Derek Lee Greenwood', wca_id: '2019GREE01', live_id: '5', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Group 1 of 2', cutoff: '1:30', limit: '2:30' },   
{ name: 'Greyson Kerr', wca_id: '2017KERR01', live_id: '37', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Group 1 of 2', cutoff: '1:30', limit: '2:30' },   
{ name: 'Michael Conard', wca_id: '2013CONA01', live_id: '16', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Group 1 of 2', cutoff: '1:30', limit: '2:30' },   
{ name: 'Noah Paredes', wca_id: '2016PARE03', live_id: '9', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Group 1 of 2', cutoff: '1:30', limit: '2:30' },   
{ name: 'Zachary Garber', wca_id: '2014GARB01', live_id: '3', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Group 1 of 2', cutoff: '1:30', limit: '2:30' },   
{ line_1: '3x3x3 One-Handed', line_2: 'Round 1', line_3: 'Group 2 of 2'},  
{ name: 'Andrey Kaipov', wca_id: 'New Competitor', live_id: '1', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Group 2 of 2', cutoff: '1:30', limit: '2:30' },   
{ name: 'Galen Patrick Andreacchi', wca_id: '2018ANDR15', live_id: '29', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Group 2 of 2', cutoff: '1:30', limit: '2:30' },   
{ name: 'Jesse Hartnett', wca_id: '2012HART03', live_id: '8', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Group 2 of 2', cutoff: '1:30', limit: '2:30' },   
{ name: 'Matt DeSanto', wca_id: '2014DESA02', live_id: '36', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Group 2 of 2', cutoff: '1:30', limit: '2:30' },   
{ name: 'Parker Sherman', wca_id: '2018SHER02', live_id: '7', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Group 2 of 2', cutoff: '1:30', limit: '2:30' },   
{ name: 'Stephen Griggs', wca_id: '2014GRIG01', live_id: '6', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Group 2 of 2', cutoff: '1:30', limit: '2:30' },   
{ name: 'Zac Carter', wca_id: '2018CART08', live_id: '27', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Group 2 of 2', cutoff: '1:30', limit: '2:30' },   
{ line_1: '3x3x3 One-Handed', line_2: 'Round 1', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '', cutoff: '1:30', limit: '2:30' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '', cutoff: '1:30', limit: '2:30' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '', cutoff: '1:30', limit: '2:30' },
{ line_1: '4x4x4 Cube', line_2: 'Round 1', line_3: 'Group 1 of 3'},
{ name: 'Greyson Kerr', wca_id: '2017KERR01', live_id: '37', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: 'Group 1 of 3', cutoff: '1:30', limit: '3:00' },   
{ name: 'Noah Paredes', wca_id: '2016PARE03', live_id: '9', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: 'Group 1 of 3', cutoff: '1:30', limit: '3:00' },   
{ name: 'Parker Sherman', wca_id: '2018SHER02', live_id: '7', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: 'Group 1 of 3', cutoff: '1:30', limit: '3:00' },   
{ name: 'Stephen Griggs', wca_id: '2014GRIG01', live_id: '6', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: 'Group 1 of 3', cutoff: '1:30', limit: '3:00' },   
{ name: 'Tyler Galbreath-Taylor', wca_id: '2018GALB01', live_id: '15', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: 'Group 1 of 3', cutoff: '1:30', limit: '3:00' },   
{ line_1: '4x4x4 Cube', line_2: 'Round 1', line_3: 'Group 2 of 3'},
{ name: 'Andy Guo', wca_id: '2019GUOA01', live_id: '22', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: 'Group 2 of 3', cutoff: '1:30', limit: '3:00' },   
{ name: 'Bryce Davies', wca_id: '2019DAVI18', live_id: '4', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: 'Group 2 of 3', cutoff: '1:30', limit: '3:00' },   
{ name: 'Isabella Cino', wca_id: '2018CINO01', live_id: '21', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: 'Group 2 of 3', cutoff: '1:30', limit: '3:00' },   
{ name: 'Jay Boegem', wca_id: '2019BOEG01', live_id: '12', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: 'Group 2 of 3', cutoff: '1:30', limit: '3:00' },   
{ name: 'Jesse Hartnett', wca_id: '2012HART03', live_id: '8', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: 'Group 2 of 3', cutoff: '1:30', limit: '3:00' },   
{ name: 'Zachary Garber', wca_id: '2014GARB01', live_id: '3', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: 'Group 2 of 3', cutoff: '1:30', limit: '3:00' },   
{ line_1: '4x4x4 Cube', line_2: 'Round 1', line_3: 'Group 3 of 3'},
{ name: 'Andrey Kaipov', wca_id: 'New Competitor', live_id: '1', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: 'Group 3 of 3', cutoff: '1:30', limit: '3:00' },   
{ name: 'Derek Lee Greenwood', wca_id: '2019GREE01', live_id: '5', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: 'Group 3 of 3', cutoff: '1:30', limit: '3:00' },   
{ name: 'Galen Patrick Andreacchi', wca_id: '2018ANDR15', live_id: '29', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: 'Group 3 of 3', cutoff: '1:30', limit: '3:00' },   
{ name: 'Matt DeSanto', wca_id: '2014DESA02', live_id: '36', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: 'Group 3 of 3', cutoff: '1:30', limit: '3:00' },   
{ name: 'Michael Conard', wca_id: '2013CONA01', live_id: '16', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: 'Group 3 of 3', cutoff: '1:30', limit: '3:00' },   
{ name: 'Zac Carter', wca_id: '2018CART08', live_id: '27', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: 'Group 3 of 3', cutoff: '1:30', limit: '3:00' },   
{ line_1: '4x4x4 Cube', line_2: 'Round 1', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: '', cutoff: '1:30', limit: '3:00' }, 
{ name: '', wca_id: '', live_id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: '', cutoff: '1:30', limit: '3:00' },  
{ name: '', wca_id: '', live_id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Round 1 of 2', group: '', cutoff: '1:30', limit: '3:00' },    
{ line_1: '3x3x3 Cube', line_2: 'Round 1', line_3: 'Group 1 of 3'},
{ name: 'Casey Moody', wca_id: '2019MOOD03', live_id: '39', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Erika Davies', wca_id: '2020DAVI05', live_id: '40', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Noah Paredes', wca_id: '2016PARE03', live_id: '9', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Parker Sherman', wca_id: '2018SHER02', live_id: '7', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Stephen Griggs', wca_id: '2014GRIG01', live_id: '6', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Tyler Galbreath-Taylor', wca_id: '2018GALB01', live_id: '15', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },   
{ line_1: '3x3x3 Cube', line_2: 'Round 1', line_3: 'Group 2 of 3'},
{ name: 'Andy Guo', wca_id: '2019GUOA01', live_id: '22', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Bryce Davies', wca_id: '2019DAVI18', live_id: '4', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Cat Madish', wca_id: '2019MADI01', live_id: '17', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Isabella Cino', wca_id: '2018CINO01', live_id: '21', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Jesse Hartnett', wca_id: '2012HART03', live_id: '8', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Paxton Cava', wca_id: 'New Competitor', live_id: '42', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Zachary Garber', wca_id: '2014GARB01', live_id: '3', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },   
{ line_1: '3x3x3 Cube', line_2: 'Round 1', line_3: 'Group 3 of 3'},
{ name: 'Andrey Kaipov', wca_id: 'New Competitor', live_id: '1', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Derek Lee Greenwood', wca_id: '2019GREE01', live_id: '5', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Greyson Kerr', wca_id: '2017KERR01', live_id: '37', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Jay Boegem', wca_id: '2019BOEG01', live_id: '12', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Matt DeSanto', wca_id: '2014DESA02', live_id: '36', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Michael Conard', wca_id: '2013CONA01', live_id: '16', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Zac Carter', wca_id: '2018CART08', live_id: '27', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },   
{ line_1: '3x3x3 Cube', line_2: 'Round 1', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: '', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: '', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: '', cutoff: '-', limit: '10:00' },   
{ line_1: 'Pyraminx', line_2: 'Round 1', line_3: 'Group 1 of 3'},
{ name: 'Andrey Kaipov', wca_id: 'New Competitor', live_id: '1', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Casey Moody', wca_id: '2019MOOD03', live_id: '39', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Galen Patrick Andreacchi', wca_id: '2018ANDR15', live_id: '29', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Greyson Kerr', wca_id: '2017KERR01', live_id: '37', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Isabella Cino', wca_id: '2018CINO01', live_id: '21', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Zachary Garber', wca_id: '2014GARB01', live_id: '3', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },   
{ line_1: 'Pyraminx', line_2: 'Round 1', line_3: 'Group 2 of 3'},
{ name: 'Jesse Hartnett', wca_id: '2012HART03', live_id: '8', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Matt DeSanto', wca_id: '2014DESA02', live_id: '36', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Michael Conard', wca_id: '2013CONA01', live_id: '16', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Parker Sherman', wca_id: '2018SHER02', live_id: '7', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Paxton Cava', wca_id: 'New Competitor', live_id: '42', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Tyler Galbreath-Taylor', wca_id: '2018GALB01', live_id: '15', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Zac Carter', wca_id: '2018CART08', live_id: '27', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },   
{ line_1: 'Pyraminx', line_2: 'Round 1', line_3: 'Group 3 of 3'},
{ name: 'Andy Guo', wca_id: '2019GUOA01', live_id: '22', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Bryce Davies', wca_id: '2019DAVI18', live_id: '4', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Cat Madish', wca_id: '2019MADI01', live_id: '17', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Derek Lee Greenwood', wca_id: '2019GREE01', live_id: '5', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Jay Boegem', wca_id: '2019BOEG01', live_id: '12', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Noah Paredes', wca_id: '2016PARE03', live_id: '9', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },   
{ name: 'Stephen Griggs', wca_id: '2014GRIG01', live_id: '6', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },   
{ line_1: 'Pyraminx', line_2: 'Round 1', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: '', cutoff: '-', limit: '10:00' },  
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: '', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyra.png', round: 'Final', group: '', cutoff: '-', limit: '10:00' },  
{ line_1: '4x4x4 Cube', line_2: 'Final', line_3: 'Group 1 of 1'},
{ name: '', wca_id: '', live_id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: 'Seed 1', cutoff: '-', limit: '10:00' },  
{ name: '', wca_id: '', live_id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: 'Seed 2', cutoff: '-', limit: '10:00' },  
{ name: '', wca_id: '', live_id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: 'Seed 3', cutoff: '-', limit: '10:00' },  
{ name: '', wca_id: '', live_id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: 'Seed 4', cutoff: '-', limit: '10:00' },  
{ name: '', wca_id: '', live_id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: 'Seed 5', cutoff: '-', limit: '10:00' },  
{ name: '', wca_id: '', live_id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: 'Seed 6', cutoff: '-', limit: '10:00' },  
{ name: '', wca_id: '', live_id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: 'Seed 7', cutoff: '-', limit: '10:00' },  
{ name: '', wca_id: '', live_id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: 'Seed 8', cutoff: '-', limit: '10:00' },  
{ line_1: '4x4x4 Cube', line_2: 'Final', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },  
{ name: '', wca_id: '', live_id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },  
{ name: '', wca_id: '', live_id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },  
{ line_1: '5x5x5 Cube', line_2: 'Round 1', line_3: 'Group 1 of 2'},
{ name: 'Andrey Kaipov', wca_id: 'New Competitor', live_id: '1', event: '5x5x5 Cube', logo: 'logo_555.png', round: 'Final', group: 'Group 1 of 2', cutoff: '2:15', limit: '4:30' },   
{ name: 'Jesse Hartnett', wca_id: '2012HART03', live_id: '8', event: '5x5x5 Cube', logo: 'logo_555.png', round: 'Final', group: 'Group 1 of 2', cutoff: '2:15', limit: '4:30' },   
{ name: 'Noah Paredes', wca_id: '2016PARE03', live_id: '9', event: '5x5x5 Cube', logo: 'logo_555.png', round: 'Final', group: 'Group 1 of 2', cutoff: '2:15', limit: '4:30' },   
{ name: 'Tyler Galbreath-Taylor', wca_id: '2018GALB01', live_id: '15', event: '5x5x5 Cube', logo: 'logo_555.png', round: 'Final', group: 'Group 1 of 2', cutoff: '2:15', limit: '4:30' },   
{ name: 'Zachary Garber', wca_id: '2014GARB01', live_id: '3', event: '5x5x5 Cube', logo: 'logo_555.png', round: 'Final', group: 'Group 1 of 2', cutoff: '2:15', limit: '4:30' },   
{ line_1: '5x5x5 Cube', line_2: 'Round 1', line_3: 'Group 2 of 2'},
{ name: 'Bryce Davies', wca_id: '2019DAVI18', live_id: '4', event: '5x5x5 Cube', logo: 'logo_555.png', round: 'Final', group: 'Group 2 of 2', cutoff: '2:15', limit: '4:30' },   
{ name: 'Greyson Kerr', wca_id: '2017KERR01', live_id: '37', event: '5x5x5 Cube', logo: 'logo_555.png', round: 'Final', group: 'Group 2 of 2', cutoff: '2:15', limit: '4:30' },   
{ name: 'Michael Conard', wca_id: '2013CONA01', live_id: '16', event: '5x5x5 Cube', logo: 'logo_555.png', round: 'Final', group: 'Group 2 of 2', cutoff: '2:15', limit: '4:30' },   
{ name: 'Stephen Griggs', wca_id: '2014GRIG01', live_id: '6', event: '5x5x5 Cube', logo: 'logo_555.png', round: 'Final', group: 'Group 2 of 2', cutoff: '2:15', limit: '4:30' },   
{ name: 'Zac Carter', wca_id: '2018CART08', live_id: '27', event: '5x5x5 Cube', logo: 'logo_555.png', round: 'Final', group: 'Group 2 of 2', cutoff: '2:15', limit: '4:30' },   
{ line_1: '5x5x5 Cube', line_2: 'Round 1', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: '5x5x5 Cube', logo: 'logo_555.png', round: 'Final', group: '', cutoff: '2:15', limit: '4:30' },
{ name: '', wca_id: '', live_id: '', event: '5x5x5 Cube', logo: 'logo_555.png', round: 'Final', group: '', cutoff: '2:15', limit: '4:30' },
{ name: '', wca_id: '', live_id: '', event: '5x5x5 Cube', logo: 'logo_555.png', round: 'Final', group: '', cutoff: '2:15', limit: '4:30' },   
{ line_1: '3x3x3 Cube', line_2: 'Final', line_3: 'Group 1 of 1'},
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 1', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 2', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 3', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 4', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 5', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 6', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 7', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 8', cutoff: '-', limit: '10:00' },  
{ line_1: '3x3x3 Cube', line_2: 'Final', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ line_1: 'Unofficial Mirror Blocks', line_2: 'Final', line_3: 'Group 1 of 2'},
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' }, 
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' }, 
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' }, 
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' }, 
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' }, 
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' }, 
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' }, 
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' }, 
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' },  
{ line_1: 'Unofficial Mirror Blocks', line_2: 'Final', line_3: 'Group 2 of 2'},
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Mirror Blocks', logo: 'logo_333_mirror.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ line_1: 'Unofficial Kilominx', line_2: 'Final', line_3: 'Group 1 of 2'},
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 1 of 2', cutoff: '-', limit: '5:00' },
{ line_1: 'Unofficial Kilominx', line_2: 'Final', line_3: 'Group 2 of 2'},
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: 'Group 2 of 2', cutoff: '-', limit: '5:00' },
{ line_1: 'Unofficial Kilominx', line_2: 'Final', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: '', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: '', cutoff: '-', limit: '5:00' },
{ name: '', wca_id: '', live_id: '', event: 'Kilominx', logo: 'logo_kilo.png', round: 'Final', group: '', cutoff: '-', limit: '5:00' },
]
