window.mo3events =['6x6x6 Cube', '7x7x7 Cube', '3x3x3 Blindfolded', '4x4x4 Blindfolded', '5x5x5 Blindfolded', 'Team Relay'];

window.cumulativeevents =['3x3x3 Blindfolded', '4x4x4 Blindfolded', '5x5x5 Blindfolded'];

window.bo1events = [];

window.bo2events = [];

window.bo3events = ['3x3x3 Multi-Blind'];

window.sizeChanges = {
	'David Ignacio Gonzalez Lugo': '38px',
}

window.competitors = [
{ line_1: '2x2x2 Cube', line_2: 'Round 1', line_3: 'Group 1 of 4'},
{ line_1: '3x3x3 Cube', line_2: 'Round 1', line_3: 'Group 3 of 5'},
{ name: 'Colden Buzzell', wca_id: 'New Competitor', live_id: '26', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 9', cutoff: '-', limit: '10:00' },
{ name: 'Jack Herrick', wca_id: 'New Competitor', live_id: '55', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Aarush Anantha Prakash', wca_id: 'New Competitor', live_id: '57', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Colin Miller', wca_id: '2019MILL07', live_id: '14', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 10', cutoff: '-', limit: '10:00' },
{ name: 'Jack Nguyen', wca_id: 'New Competitor', live_id: '25', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Adam Zhou', wca_id: 'New Competitor', live_id: '78', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Derek Bennett', wca_id: '2017BENN10', live_id: '18', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 11', cutoff: '-', limit: '10:00' },
{ name: 'Jacky Chen', wca_id: 'New Competitor', live_id: '58', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Aidan O\'Brien', wca_id: 'New Competitor', live_id: '16', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Edward Caine', wca_id: 'New Competitor', live_id: '3', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 12', cutoff: '-', limit: '10:00' },
{ name: 'Joseph Tahan', wca_id: 'New Competitor', live_id: '23', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Aiden Valentino', wca_id: '2019VALE20', live_id: '11', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Elijah Essig', wca_id: 'New Competitor', live_id: '20', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 13', cutoff: '-', limit: '10:00' },
{ name: 'Kai Savage', wca_id: 'New Competitor', live_id: '30', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Alexander Adamski', wca_id: 'New Competitor', live_id: '21', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Finlay Bouffard Lima', wca_id: 'New Competitor', live_id: '66', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 14', cutoff: '-', limit: '10:00' },
{ name: 'Kallen Miller', wca_id: 'New Competitor', live_id: '47', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Alli Swanchak', wca_id: 'New Competitor', live_id: '38', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Hunter Otis', wca_id: 'New Competitor', live_id: '35', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube', line_2: 'Round 2', line_3: 'Group 2 of 2'},
{ name: 'Kiawentsiawehon Elijah', wca_id: 'New Competitor', live_id: '42', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Andrea Mitchell', wca_id: '2018MITC05', live_id: '77', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Joseph Tahan', wca_id: 'New Competitor', live_id: '23', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 15', cutoff: '-', limit: '10:00' },
{ name: 'Maddox Stoughton', wca_id: 'New Competitor', live_id: '12', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Andrew Miller', wca_id: '2019MILL06', live_id: '19', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Kai Savage', wca_id: 'New Competitor', live_id: '30', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 16', cutoff: '-', limit: '10:00' },
{ name: 'Matthew Ficarra', wca_id: 'New Competitor', live_id: '76', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Annabelle Sun', wca_id: 'New Competitor', live_id: '79', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Kallen Miller', wca_id: 'New Competitor', live_id: '47', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 17', cutoff: '-', limit: '10:00' },
{ name: 'Nathan Smith', wca_id: 'New Competitor', live_id: '61', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Brady Williams', wca_id: 'New Competitor', live_id: '80', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Kiawentsiawehon Elijah', wca_id: 'New Competitor', live_id: '42', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 18', cutoff: '-', limit: '10:00' },
{ name: 'Oliver Bender', wca_id: 'New Competitor', live_id: '50', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Brody Oleksyn', wca_id: '2019OLEK01', live_id: '63', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Oliver Bender', wca_id: 'New Competitor', live_id: '50', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 19', cutoff: '-', limit: '10:00' },
{ name: 'Owen Donnelly', wca_id: 'New Competitor', live_id: '13', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Bryce Oleksyn', wca_id: '2019OLEK02', live_id: '62', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Thayne Carlo', wca_id: '2017CARL07', live_id: '44', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 20', cutoff: '-', limit: '10:00' },
{ name: 'Shakohentehtha Elijah', wca_id: '2019ELIJ01', live_id: '17', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Liam Forth', wca_id: '2018FORT04', live_id: '49', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ line_1: 'Skewb', line_2: 'Round 1', line_3: 'Group 2 of 3'},
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 21', cutoff: '-', limit: '10:00' },
{ name: 'Thayne Carlo', wca_id: '2017CARL07', live_id: '44', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Tara Lenzo', wca_id: '2018LENZ01', live_id: '73', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Aiden Valentino', wca_id: '2019VALE20', live_id: '11', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 22', cutoff: '-', limit: '10:00' },
{ name: 'Tyler Malloy', wca_id: 'New Competitor', live_id: '75', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Tony Lenzo', wca_id: '2018LENZ02', live_id: '72', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Alexander Adamski', wca_id: 'New Competitor', live_id: '21', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 23', cutoff: '-', limit: '10:00' },
{ name: 'Zachary Flansburgh', wca_id: 'New Competitor', live_id: '24', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube', line_2: 'Round 1', line_3: 'Group 4 of 5'},
{ name: 'Andrea Mitchell', wca_id: '2018MITC05', live_id: '77', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 24', cutoff: '-', limit: '10:00' },
{ line_1: '2x2x2 Cube', line_2: 'Round 1', line_3: 'Group 2 of 4'},
{ name: 'Albert G. Tahan', wca_id: '2018TAHA01', live_id: '29', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Docité Oren Schandry', wca_id: '2019SCHA03', live_id: '70', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 25', cutoff: '-', limit: '10:00' },
{ name: 'Brady Williams', wca_id: 'New Competitor', live_id: '80', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Caleb Kearney', wca_id: '2018KEAR02', live_id: '68', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Ethan Cobos', wca_id: '2019COBO01', live_id: '7', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 26', cutoff: '-', limit: '10:00' },
{ name: 'Brandon Davis', wca_id: 'New Competitor', live_id: '71', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Chandler Scheurkogel', wca_id: '2019SCHE06', live_id: '54', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Ethan Coolidge', wca_id: '2017COOL02', live_id: '10', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 27', cutoff: '-', limit: '10:00' },
{ name: 'Brandt Davis', wca_id: 'New Competitor', live_id: '53', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Docité Oren Schandry', wca_id: '2019SCHA03', live_id: '70', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Everett Gorman', wca_id: '2019GORM04', live_id: '40', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 28', cutoff: '-', limit: '10:00' },
{ name: 'Brody Oleksyn', wca_id: '2019OLEK01', live_id: '63', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Ethan Cobos', wca_id: '2019COBO01', live_id: '7', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Holden Lester', wca_id: '2019LEST02', live_id: '9', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube', line_2: 'Round 2', line_3: 'Extras'},
{ name: 'Bryce Oleksyn', wca_id: '2019OLEK02', live_id: '62', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Ethan Coolidge', wca_id: '2017COOL02', live_id: '10', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Jack Ryan', wca_id: '2015RYAN02', live_id: '65', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Caleb Kearney', wca_id: '2018KEAR02', live_id: '68', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Everett Gorman', wca_id: '2019GORM04', live_id: '40', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Liam Forth', wca_id: '2018FORT04', live_id: '49', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Cali Oleksyn', wca_id: 'New Competitor', live_id: '64', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Holden Lester', wca_id: '2019LEST02', live_id: '9', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Samuel O\'Sullivan', wca_id: '2018OSUL02', live_id: '45', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Colden Buzzell', wca_id: 'New Competitor', live_id: '26', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Jack Ryan', wca_id: '2015RYAN02', live_id: '65', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Shakohentehtha Elijah', wca_id: '2019ELIJ01', live_id: '17', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Colin Miller', wca_id: '2019MILL07', live_id: '14', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Lucas Nieuwland', wca_id: '2018NIEU01', live_id: '41', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Vladimir Sahagun', wca_id: '2015SAHA01', live_id: '32', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Edward Caine', wca_id: 'New Competitor', live_id: '3', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Matthew Jacobs', wca_id: '2016JACO04', live_id: '43', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' },
{ line_1: 'Skewb', line_2: 'Round 1', line_3: 'Group 3 of 3'},
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Elijah Essig', wca_id: 'New Competitor', live_id: '20', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Noah Melita', wca_id: '2018MELI05', live_id: '4', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Alex Maass', wca_id: '2011MAAS01', live_id: '8', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Everett Gorman', wca_id: '2019GORM04', live_id: '40', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Samuel O\'Sullivan', wca_id: '2018OSUL02', live_id: '45', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Brennen Lin', wca_id: '2016LINB01', live_id: '46', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Finlay Bouffard Lima', wca_id: 'New Competitor', live_id: '66', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Shakohentehtha Elijah', wca_id: '2019ELIJ01', live_id: '17', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Caleb Kearney', wca_id: '2018KEAR02', live_id: '68', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube One-Handed', line_2: 'Final', line_3: 'Group 1 of 1'},
{ name: 'Forrest Li', wca_id: 'New Competitor', live_id: '22', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Vladimir Sahagun', wca_id: '2015SAHA01', live_id: '32', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Evan Liu', wca_id: '2009LIUE01', live_id: '6', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 1', cutoff: '-', limit: '10:00' },
{ name: 'Hunter Otis', wca_id: 'New Competitor', live_id: '35', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube', line_2: 'Round 1', line_3: 'Group 5 of 5'},
{ name: 'Jess Mitchell', wca_id: '2018MITC03', live_id: '67', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 2', cutoff: '-', limit: '10:00' },
{ line_1: '2x2x2 Cube', line_2: 'Round 1', line_3: 'Group 3 of 4'},
{ name: 'Alex Maass', wca_id: '2011MAAS01', live_id: '8', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Joaquin Abarca', wca_id: '2017ABAR02', live_id: '36', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 3', cutoff: '-', limit: '10:00' },
{ name: 'Aarush Anantha Prakash', wca_id: 'New Competitor', live_id: '57', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Brennen Lin', wca_id: '2016LINB01', live_id: '46', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Kobe Balin', wca_id: '2012BALI01', live_id: '28', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 4', cutoff: '-', limit: '10:00' },
{ name: 'Aiden Valentino', wca_id: '2019VALE20', live_id: '11', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Derek Bennett', wca_id: '2017BENN10', live_id: '18', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Lucas Nieuwland', wca_id: '2018NIEU01', live_id: '41', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 5', cutoff: '-', limit: '10:00' },
{ name: 'Alexander Adamski', wca_id: 'New Competitor', live_id: '21', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Evan Liu', wca_id: '2009LIUE01', live_id: '6', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Nima Bolourchian', wca_id: '2017BOLO01', live_id: '69', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 6', cutoff: '-', limit: '10:00' },
{ name: 'Andrea Mitchell', wca_id: '2018MITC05', live_id: '77', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Jess Mitchell', wca_id: '2018MITC03', live_id: '67', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Noah Melita', wca_id: '2018MELI05', live_id: '4', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 7', cutoff: '-', limit: '10:00' },
{ name: 'Andrew Miller', wca_id: '2019MILL06', live_id: '19', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Joaquin Abarca', wca_id: '2017ABAR02', live_id: '36', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Ryan Pin Harry', wca_id: '2015HARR01', live_id: '2', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 8', cutoff: '-', limit: '10:00' },
{ name: 'Chandler Scheurkogel', wca_id: '2019SCHE06', live_id: '54', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Kobe Balin', wca_id: '2012BALI01', live_id: '28', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Ryan Wu', wca_id: '2017WURY01', live_id: '39', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 9', cutoff: '-', limit: '10:00' },
{ name: 'Derek Bennett', wca_id: '2017BENN10', live_id: '18', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Matthew Rich', wca_id: '2015RICH02', live_id: '51', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Samuel Knoll', wca_id: '2015KNOL01', live_id: '48', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 10', cutoff: '-', limit: '10:00' },
{ name: 'Docité Oren Schandry', wca_id: '2019SCHA03', live_id: '70', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Nima Bolourchian', wca_id: '2017BOLO01', live_id: '69', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' },
{ line_1: 'Skewb', line_2: 'Round 1', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 11', cutoff: '-', limit: '10:00' },
{ name: 'Ethan Cobos', wca_id: '2019COBO01', live_id: '7', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Patrick Ponce', wca_id: '2012PONC02', live_id: '52', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 12', cutoff: '-', limit: '10:00' },
{ name: 'Jack Ryan', wca_id: '2015RYAN02', live_id: '65', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Ryan Pin Harry', wca_id: '2015HARR01', live_id: '2', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube One-Handed', line_2: 'Final', line_3: 'Extras'},
{ name: 'Liam Forth', wca_id: '2018FORT04', live_id: '49', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Ryan Wu', wca_id: '2017WURY01', live_id: '39', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Matthew Jacobs', wca_id: '2016JACO04', live_id: '43', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Samuel Knoll', wca_id: '2015KNOL01', live_id: '48', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Ryan Pin Harry', wca_id: '2015HARR01', live_id: '2', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Sarah Strong', wca_id: '2007STRO01', live_id: '5', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Samuel O\'Sullivan', wca_id: '2018OSUL02', live_id: '45', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube', line_2: 'Round 1', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Vladimir Sahagun', wca_id: '2015SAHA01', live_id: '32', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ line_1: '2x2x2 Cube', line_2: 'Round 1', line_3: 'Group 4 of 4'},
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ line_1: 'Skewb', line_2: 'Final', line_3: 'Group 1 of 1'},
{ name: 'Alex Maass', wca_id: '2011MAAS01', live_id: '8', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ line_1: 'Clock', line_2: 'Round 1', line_3: 'Group 1 of 2'},
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final', group: 'Seed 1', cutoff: '-', limit: '10:00' },
{ name: 'Brennen Lin', wca_id: '2016LINB01', live_id: '46', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Alex Maass', wca_id: '2011MAAS01', live_id: '8', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final', group: 'Seed 2', cutoff: '-', limit: '10:00' },
{ name: 'Ethan Coolidge', wca_id: '2017COOL02', live_id: '10', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Alexander Adamski', wca_id: 'New Competitor', live_id: '21', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final', group: 'Seed 3', cutoff: '-', limit: '10:00' },
{ name: 'Evan Liu', wca_id: '2009LIUE01', live_id: '6', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Andrea Mitchell', wca_id: '2018MITC05', live_id: '77', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final', group: 'Seed 4', cutoff: '-', limit: '10:00' },
{ name: 'Holden Lester', wca_id: '2019LEST02', live_id: '9', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Andrew Miller', wca_id: '2019MILL06', live_id: '19', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final', group: 'Seed 5', cutoff: '-', limit: '10:00' },
{ name: 'Jack Joseph Sliwka', wca_id: 'New Competitor', live_id: '37', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Elijah Essig', wca_id: 'New Competitor', live_id: '20', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final', group: 'Seed 6', cutoff: '-', limit: '10:00' },
{ name: 'Jess Mitchell', wca_id: '2018MITC03', live_id: '67', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube One-Handed', line_2: 'Round 1', line_3: 'Group 1 of 3'},
{ name: 'Ethan Cobos', wca_id: '2019COBO01', live_id: '7', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final', group: 'Seed 7', cutoff: '-', limit: '10:00' },
{ name: 'Joaquin Abarca', wca_id: '2017ABAR02', live_id: '36', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Alexander Adamski', wca_id: 'New Competitor', live_id: '21', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: 'Everett Gorman', wca_id: '2019GORM04', live_id: '40', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final', group: 'Seed 8', cutoff: '-', limit: '10:00' },
{ name: 'Kobe Balin', wca_id: '2012BALI01', live_id: '28', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Brandt Davis', wca_id: 'New Competitor', live_id: '53', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: 'Finlay Bouffard Lima', wca_id: 'New Competitor', live_id: '66', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final', group: 'Seed 9', cutoff: '-', limit: '10:00' },
{ name: 'Lucas Nieuwland', wca_id: '2018NIEU01', live_id: '41', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Colin Miller', wca_id: '2019MILL07', live_id: '14', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: 'Liam Forth', wca_id: '2018FORT04', live_id: '49', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final', group: 'Seed 10', cutoff: '-', limit: '10:00' },
{ name: 'Matthew Rich', wca_id: '2015RICH02', live_id: '51', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Ethan Cobos', wca_id: '2019COBO01', live_id: '7', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: 'Nima Bolourchian', wca_id: '2017BOLO01', live_id: '69', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final', group: 'Seed 11', cutoff: '-', limit: '10:00' },
{ name: 'Nima Bolourchian', wca_id: '2017BOLO01', live_id: '69', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Finlay Bouffard Lima', wca_id: 'New Competitor', live_id: '66', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ line_1: 'Clock', line_2: 'Round 1', line_3: 'Group 2 of 2'},
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final', group: 'Seed 12', cutoff: '-', limit: '10:00' },
{ name: 'Noah Melita', wca_id: '2018MELI05', live_id: '4', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Jacky Chen', wca_id: 'New Competitor', live_id: '58', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: 'Caleb Kearney', wca_id: '2018KEAR02', live_id: '68', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 2 of 2', cutoff: '1:00', limit: '10:00' },
{ line_1: 'Skewb', line_2: 'Final', line_3: 'Extras'},
{ name: 'Ryan Wu', wca_id: '2017WURY01', live_id: '39', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Joseph Tahan', wca_id: 'New Competitor', live_id: '23', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: 'Evan Liu', wca_id: '2009LIUE01', live_id: '6', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 2 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Samuel Knoll', wca_id: '2015KNOL01', live_id: '48', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Matthew Ficarra', wca_id: 'New Competitor', live_id: '76', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: 'Jess Mitchell', wca_id: '2018MITC03', live_id: '67', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 2 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ line_1: '2x2x2 Cube', line_2: 'Round 1', line_3: 'Extras'},
{ name: 'Shakohentehtha Elijah', wca_id: '2019ELIJ01', live_id: '17', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: 'Joaquin Abarca', wca_id: '2017ABAR02', live_id: '36', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 2 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Thayne Carlo', wca_id: '2017CARL07', live_id: '44', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: 'Kobe Balin', wca_id: '2012BALI01', live_id: '28', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 2 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Vladimir Sahagun', wca_id: '2015SAHA01', live_id: '32', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: 'Lucas Nieuwland', wca_id: '2018NIEU01', live_id: '41', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 2 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Zachary Flansburgh', wca_id: 'New Competitor', live_id: '24', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: 'Ryan Pin Harry', wca_id: '2015HARR01', live_id: '2', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 2 of 2', cutoff: '1:00', limit: '10:00' },
{ line_1: 'Clock', line_2: 'Final', line_3: 'Group 1 of 1'},
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube One-Handed', line_2: 'Round 1', line_3: 'Group 2 of 3'},
{ name: 'Ryan Wu', wca_id: '2017WURY01', live_id: '39', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 2 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 1', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Brody Oleksyn', wca_id: '2019OLEK01', live_id: '63', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: 'Samuel Knoll', wca_id: '2015KNOL01', live_id: '48', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 2 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 2', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Caleb Kearney', wca_id: '2018KEAR02', live_id: '68', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ line_1: 'Clock', line_2: 'Round 1', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Chandler Scheurkogel', wca_id: '2019SCHE06', live_id: '54', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 4', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Docité Oren Schandry', wca_id: '2019SCHA03', live_id: '70', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 5', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube', line_2: 'Round 1', line_3: 'Group 1 of 5'},
{ name: 'Ethan Coolidge', wca_id: '2017COOL02', live_id: '10', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 6', cutoff: '-', limit: '10:00' },
{ name: 'Jeremy Norbut', wca_id: 'New Competitor', live_id: '1', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Everett Gorman', wca_id: '2019GORM04', live_id: '40', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 7', cutoff: '-', limit: '10:00' },
{ name: 'Joseph Tahan', wca_id: 'New Competitor', live_id: '23', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Holden Lester', wca_id: '2019LEST02', live_id: '9', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 8', cutoff: '-', limit: '10:00' },
{ name: 'Kai Savage', wca_id: 'New Competitor', live_id: '30', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Jack Ryan', wca_id: '2015RYAN02', live_id: '65', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 9', cutoff: '-', limit: '10:00' },
{ name: 'Kallen Miller', wca_id: 'New Competitor', live_id: '47', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Jess Mitchell', wca_id: '2018MITC03', live_id: '67', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ line_1: '2x2x2 Cube', line_2: 'Final', line_3: 'Group 1 of 1'},
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 10', cutoff: '-', limit: '10:00' },
{ name: 'Kiawentsiawehon Elijah', wca_id: 'New Competitor', live_id: '42', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Liam Forth', wca_id: '2018FORT04', live_id: '49', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final', group: 'Seed 1', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 11', cutoff: '-', limit: '10:00' },
{ name: 'Maddox Stoughton', wca_id: 'New Competitor', live_id: '12', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Lucas Nieuwland', wca_id: '2018NIEU01', live_id: '41', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final', group: 'Seed 2', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 12', cutoff: '-', limit: '10:00' },
{ name: 'Matthew Ficarra', wca_id: 'New Competitor', live_id: '76', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Samuel O\'Sullivan', wca_id: '2018OSUL02', live_id: '45', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final', group: 'Seed 3', cutoff: '-', limit: '10:00' },
{ line_1: 'Clock', line_2: 'Final', line_3: 'Extras'},
{ name: 'Nathan Smith', wca_id: 'New Competitor', live_id: '61', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube One-Handed', line_2: 'Round 1', line_3: 'Group 3 of 3'},
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final', group: 'Seed 4', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Oliver Bender', wca_id: 'New Competitor', live_id: '50', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Alex Maass', wca_id: '2011MAAS01', live_id: '8', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final', group: 'Seed 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Owen Donnelly', wca_id: 'New Competitor', live_id: '13', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Brennen Lin', wca_id: '2016LINB01', live_id: '46', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final', group: 'Seed 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Simon Aguilar', wca_id: 'New Competitor', live_id: '34', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Derek Bennett', wca_id: '2017BENN10', live_id: '18', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final', group: 'Seed 7', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Thayne Carlo', wca_id: '2017CARL07', live_id: '44', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Evan Liu', wca_id: '2009LIUE01', live_id: '6', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final', group: 'Seed 8', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Tyler Lenzo', wca_id: 'New Competitor', live_id: '74', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Joaquin Abarca', wca_id: '2017ABAR02', live_id: '36', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final', group: 'Seed 9', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube', line_2: 'Final', line_3: 'Group 1 of 1'},
{ name: 'Tyler Malloy', wca_id: 'New Competitor', live_id: '75', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Kobe Balin', wca_id: '2012BALI01', live_id: '28', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final', group: 'Seed 10', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 1', cutoff: '-', limit: '10:00' },
{ name: 'Zachary Flansburgh', wca_id: 'New Competitor', live_id: '24', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Matthew Rich', wca_id: '2015RICH02', live_id: '51', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final', group: 'Seed 11', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 2', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube', line_2: 'Round 1', line_3: 'Group 2 of 5'},
{ name: 'Nima Bolourchian', wca_id: '2017BOLO01', live_id: '69', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final', group: 'Seed 12', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 3', cutoff: '-', limit: '10:00' },
{ name: 'Brandon Davis', wca_id: 'New Competitor', live_id: '71', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Patrick Ponce', wca_id: '2012PONC02', live_id: '52', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ line_1: '2x2x2 Cube', line_2: 'Final', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 4', cutoff: '-', limit: '10:00' },
{ name: 'Brandt Davis', wca_id: 'New Competitor', live_id: '53', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Ryan Pin Harry', wca_id: '2015HARR01', live_id: '2', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 5', cutoff: '-', limit: '10:00' },
{ name: 'Cali Oleksyn', wca_id: 'New Competitor', live_id: '64', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Ryan Wu', wca_id: '2017WURY01', live_id: '39', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 6', cutoff: '-', limit: '10:00' },
{ name: 'Colden Buzzell', wca_id: 'New Competitor', live_id: '26', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Samuel Knoll', wca_id: '2015KNOL01', live_id: '48', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 7', cutoff: '-', limit: '10:00' },
{ name: 'Colin Miller', wca_id: '2019MILL07', live_id: '14', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube One-Handed', line_2: 'Round 1', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 8', cutoff: '-', limit: '10:00' },
{ name: 'Edward Caine', wca_id: 'New Competitor', live_id: '3', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 9', cutoff: '-', limit: '10:00' },
{ name: 'Elijah Essig', wca_id: 'New Competitor', live_id: '20', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube', line_2: 'Round 2', line_3: 'Group 1 of 2'},
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 10', cutoff: '-', limit: '10:00' },
{ name: 'Finlay Bouffard Lima', wca_id: 'New Competitor', live_id: '66', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 1', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 11', cutoff: '-', limit: '10:00' },
{ name: 'Forrest Li', wca_id: 'New Competitor', live_id: '22', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 2', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 12', cutoff: '-', limit: '10:00' },
{ name: 'Heath Flick', wca_id: 'New Competitor', live_id: '33', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 3', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube', line_2: 'Final', line_3: 'Extras'},
{ name: 'Henry Cabezas', wca_id: 'New Competitor', live_id: '60', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 4', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Hunter Otis', wca_id: 'New Competitor', live_id: '35', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Jack Herrick', wca_id: 'New Competitor', live_id: '55', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Jack Nguyen', wca_id: 'New Competitor', live_id: '25', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' },
{ line_1: 'Skewb', line_2: 'Round 1', line_3: 'Group 1 of 3'},
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 7', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: 'Jacky Chen', wca_id: 'New Competitor', live_id: '58', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Brandt Davis', wca_id: 'New Competitor', live_id: '53', event: 'Skewb', logo: 'logo_skewb.png', round: 'Round 1', group: 'Group 1 of 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2', group: 'Seed 8', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed \xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
]