window.mo3events =['6x6x6 Cube', '7x7x7 Cube', '3x3x3 Blindfolded', '4x4x4 Blindfolded', '5x5x5 Blindfolded'];

window.bo1events = ['3x3x3 Multi-Blind'];

window.competitors = [
{ name: 'Aryan Ved', id: '2018VEDA02', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Blake Thompson', id: '2010THOM03', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Brady Metherall', id: '2009METH01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Brant Holbein', id: '2014HOLB01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Chi Wang', id: 'New Competitor', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Joshua Feran', id: '2011FERA01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Joshua Graham', id: '2013GRAH01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Louis Cormier', id: '2010CORM02', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Marcus Mosley', id: '2016MOSL01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Owen Bailey-Braun', id: '2019BAIL01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Peter Douthwright', id: '2007DOUT01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Roan Paone', id: '2017PAON01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Tin Huang', id: '2019HUAN05', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'William Fehr', id: '2018FEHR01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Abdullah Gulab', id: '2014GULA02', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Brandon Arnoldo Taylor', id: '2019TAYL03', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Brennen Lin', id: '2016LINB01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Dave Deriches', id: '2018DERI02', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Ethan Erez', id: '2017EREZ01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Leo Min-Bedford', id: '2014MINB01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Matthew Krawczyk', id: '2017KRAW02', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Ryan Wu', id: '2017WURY01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Sam Mogil', id: '2018MOGI01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Vivian Kay', id: '2019KAYV01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '10:00' },
{ name: 'Blake Thompson', id: '2010THOM03', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Brady Metherall', id: '2009METH01', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Brant Holbein', id: '2014HOLB01', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Chi Wang', id: 'New Competitor', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Craig Bouchard', id: '2005BOUC01', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Louis Cormier', id: '2010CORM02', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Roan Paone', id: '2017PAON01', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Abdullah Gulab', id: '2014GULA02', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Ben Rockman', id: '2014ROCK01', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Jonathan Esparaz', id: '2013ESPA01', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Joshua Feran', id: '2011FERA01', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Joshua Graham', id: '2013GRAH01', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Ryan Wu', id: '2017WURY01', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Sam Mogil', id: '2018MOGI01', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Ajay Saini', id: 'New Competitor', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Andrei Almeyda', id: 'New Competitor', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Chi Wang', id: 'New Competitor', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Diego Rodriguez-Ramirez', id: 'New Competitor', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Luka Bailey-Braun', id: 'New Competitor', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Nazar Sushkov', id: 'New Competitor', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Tristan Raycroft', id: 'New Competitor', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Émilie Millar Desjardins', id: 'New Competitor', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Alexander Marmora', id: 'New Competitor', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Brandon Arnoldo Taylor', id: '2019TAYL03', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Cristoff Joseph Barlis', id: 'New Competitor', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Docité Oren Schandry', id: 'New Competitor', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Joshua Jones', id: 'New Competitor', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Louise Cormier', id: '2013CORM01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Mannix Freyseng', id: 'New Competitor', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Sebastian Johnston', id: 'New Competitor', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Yash Sarap', id: 'New Competitor', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Abdullah Gulab', id: '2014GULA02', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Alain Cormier', id: '2011CORM02', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Aryan Ved', id: '2018VEDA02', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Joshua Graham', id: '2013GRAH01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Marcus Mosley', id: '2016MOSL01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Matthew Krawczyk', id: '2017KRAW02', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Owen Bailey-Braun', id: '2019BAIL01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Sam Mogil', id: '2018MOGI01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Vivian Kay', id: '2019KAYV01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Ben Rockman', id: '2014ROCK01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Brant Holbein', id: '2014HOLB01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Dave Deriches', id: '2018DERI02', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Krish Ved', id: '2018VEDK01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Peter Douthwright', id: '2007DOUT01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Tin Huang', id: '2019HUAN05', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'William Fehr', id: '2018FEHR01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Zhivko Radkov Dimitrov', id: '2017DIMI01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Brady Metherall', id: '2009METH01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Brennen Lin', id: '2016LINB01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Geoffrey Stevens', id: '2017STEV03', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jensen Belen-Brown', id: '2016BELE02', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Ray Vince Ong', id: '2012ONGR01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Roan Paone', id: '2017PAON01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Ryan Wu', id: '2017WURY01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Blake Thompson', id: '2010THOM03', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Craig Bouchard', id: '2005BOUC01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Ethan Erez', id: '2017EREZ01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jonathan Esparaz', id: '2013ESPA01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Joshua Feran', id: '2011FERA01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Leo Min-Bedford', id: '2014MINB01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Louis Cormier', id: '2010CORM02', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Sarah Strong', id: '2007STRO01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Shanglin Ye', id: '2013YESH01', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Andrei Almeyda', id: 'New Competitor', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '1 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Jensen Belen-Brown', id: '2016BELE02', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '1 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Marcus Mosley', id: '2016MOSL01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '1 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '1 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Sam Mogil', id: '2018MOGI01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '1 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Sebastian Johnston', id: 'New Competitor', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '1 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'William Fehr', id: '2018FEHR01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '1 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Émilie Millar Desjardins', id: 'New Competitor', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '1 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Docité Oren Schandry', id: 'New Competitor', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '2 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Ethan Erez', id: '2017EREZ01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '2 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Joshua Graham', id: '2013GRAH01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '2 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Nazar Sushkov', id: 'New Competitor', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '2 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Owen Bailey-Braun', id: '2019BAIL01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '2 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Peter Douthwright', id: '2007DOUT01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '2 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Vivian Kay', id: '2019KAYV01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '2 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Zhivko Radkov Dimitrov', id: '2017DIMI01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '2 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Abdullah Gulab', id: '2014GULA02', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '3 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Blake Thompson', id: '2010THOM03', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '3 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Dave Deriches', id: '2018DERI02', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '3 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Leo Min-Bedford', id: '2014MINB01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '3 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Matthew Krawczyk', id: '2017KRAW02', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '3 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Ryan Wu', id: '2017WURY01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '3 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Sarah Strong', id: '2007STRO01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '3 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Shanglin Ye', id: '2013YESH01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '3 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Brady Metherall', id: '2009METH01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '4 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Brant Holbein', id: '2014HOLB01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '4 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Brennen Lin', id: '2016LINB01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '4 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '4 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Joshua Feran', id: '2011FERA01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '4 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Louis Cormier', id: '2010CORM02', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '4 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '4 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Roan Paone', id: '2017PAON01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '4 of 4', cutoff: '5:00', limit: '10:00' },
{ name: 'Abdullah Gulab', id: '2014GULA02', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Blake Thompson', id: '2010THOM03', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Brady Metherall', id: '2009METH01', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Brant Holbein', id: '2014HOLB01', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Craig Bouchard', id: '2005BOUC01', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Joshua Feran', id: '2011FERA01', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Joshua Graham', id: '2013GRAH01', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Roan Paone', id: '2017PAON01', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Ryan Wu', id: '2017WURY01', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Abdullah Gulab', id: '2014GULA02', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Ben Rockman', id: '2014ROCK01', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Blake Thompson', id: '2010THOM03', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Brant Holbein', id: '2014HOLB01', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Chi Wang', id: 'New Competitor', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Jonathan Esparaz', id: '2013ESPA01', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Joshua Feran', id: '2011FERA01', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Joshua Graham', id: '2013GRAH01', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Louis Cormier', id: '2010CORM02', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Roan Paone', id: '2017PAON01', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Ryan Wu', id: '2017WURY01', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Andrei Almeyda', id: 'New Competitor', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '1 of 4', cutoff: '-', limit: '' },
{ name: 'Brandon Arnoldo Taylor', id: '2019TAYL03', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '1 of 4', cutoff: '-', limit: '' },
{ name: 'Cristoff Joseph Barlis', id: 'New Competitor', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '1 of 4', cutoff: '-', limit: '' },
{ name: 'Diego Rodriguez-Ramirez', id: 'New Competitor', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '1 of 4', cutoff: '-', limit: '' },
{ name: 'Geoffrey Stevens', id: '2017STEV03', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '1 of 4', cutoff: '-', limit: '' },
{ name: 'Krish Ved', id: '2018VEDK01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '1 of 4', cutoff: '-', limit: '' },
{ name: 'Marcus Mosley', id: '2016MOSL01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '1 of 4', cutoff: '-', limit: '' },
{ name: 'Nazar Sushkov', id: 'New Competitor', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '1 of 4', cutoff: '-', limit: '' },
{ name: 'Sam Mogil', id: '2018MOGI01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '1 of 4', cutoff: '-', limit: '' },
{ name: 'Vivian Kay', id: '2019KAYV01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '1 of 4', cutoff: '-', limit: '' },
{ name: 'Ajay Saini', id: 'New Competitor', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '2 of 4', cutoff: '-', limit: '' },
{ name: 'Aryan Ved', id: '2018VEDA02', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '2 of 4', cutoff: '-', limit: '' },
{ name: 'Chi Wang', id: 'New Competitor', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '2 of 4', cutoff: '-', limit: '' },
{ name: 'Dave Deriches', id: '2018DERI02', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '2 of 4', cutoff: '-', limit: '' },
{ name: 'Docité Oren Schandry', id: 'New Competitor', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '2 of 4', cutoff: '-', limit: '' },
{ name: 'Joshua Jones', id: 'New Competitor', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '2 of 4', cutoff: '-', limit: '' },
{ name: 'Mannix Freyseng', id: 'New Competitor', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '2 of 4', cutoff: '-', limit: '' },
{ name: 'Peter Douthwright', id: '2007DOUT01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '2 of 4', cutoff: '-', limit: '' },
{ name: 'Tin Huang', id: '2019HUAN05', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '2 of 4', cutoff: '-', limit: '' },
{ name: 'William Fehr', id: '2018FEHR01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '2 of 4', cutoff: '-', limit: '' },
{ name: 'Zhivko Radkov Dimitrov', id: '2017DIMI01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '2 of 4', cutoff: '-', limit: '' },
{ name: 'Blake Thompson', id: '2010THOM03', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '3 of 4', cutoff: '-', limit: '' },
{ name: 'Brady Metherall', id: '2009METH01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '3 of 4', cutoff: '-', limit: '' },
{ name: 'Brant Holbein', id: '2014HOLB01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '3 of 4', cutoff: '-', limit: '' },
{ name: 'Brennen Lin', id: '2016LINB01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '3 of 4', cutoff: '-', limit: '' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '3 of 4', cutoff: '-', limit: '' },
{ name: 'Joshua Feran', id: '2011FERA01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '3 of 4', cutoff: '-', limit: '' },
{ name: 'Joshua Graham', id: '2013GRAH01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '3 of 4', cutoff: '-', limit: '' },
{ name: 'Leo Min-Bedford', id: '2014MINB01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '3 of 4', cutoff: '-', limit: '' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '3 of 4', cutoff: '-', limit: '' },
{ name: 'Matthew Krawczyk', id: '2017KRAW02', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '3 of 4', cutoff: '-', limit: '' },
{ name: 'Shanglin Ye', id: '2013YESH01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '3 of 4', cutoff: '-', limit: '' },
{ name: 'Abdullah Gulab', id: '2014GULA02', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '4 of 4', cutoff: '-', limit: '' },
{ name: 'Ben Rockman', id: '2014ROCK01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '4 of 4', cutoff: '-', limit: '' },
{ name: 'Ethan Erez', id: '2017EREZ01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '4 of 4', cutoff: '-', limit: '' },
{ name: 'Jensen Belen-Brown', id: '2016BELE02', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '4 of 4', cutoff: '-', limit: '' },
{ name: 'Jonathan Esparaz', id: '2013ESPA01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '4 of 4', cutoff: '-', limit: '' },
{ name: 'Louis Cormier', id: '2010CORM02', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '4 of 4', cutoff: '-', limit: '' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '4 of 4', cutoff: '-', limit: '' },
{ name: 'Owen Bailey-Braun', id: '2019BAIL01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '4 of 4', cutoff: '-', limit: '' },
{ name: 'Ray Vince Ong', id: '2012ONGR01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '4 of 4', cutoff: '-', limit: '' },
{ name: 'Roan Paone', id: '2017PAON01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '4 of 4', cutoff: '-', limit: '' },
{ name: 'Ryan Wu', id: '2017WURY01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '4 of 4', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 3', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '1 of 6', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '2 of 6', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '1 of 6', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '2 of 6', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '1 of 6', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '2 of 6', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '1 of 6', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '2 of 6', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '1 of 6', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 3', group: '2 of 6', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '1 of 4', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '2 of 4', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '1 of 4', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '2 of 4', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '1 of 4', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '2 of 4', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '1 of 4', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '2 of 4', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '1 of 4', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1 of 2', group: '2 of 4', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '3x3x3 Blindfolded', logo: 'logo_333bf.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '1 of 4', cutoff: '5:00', limit: '10:00' },
{ name: '', id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '2 of 4', cutoff: '5:00', limit: '10:00' },
{ name: '', id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '1 of 4', cutoff: '5:00', limit: '10:00' },
{ name: '', id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '2 of 4', cutoff: '5:00', limit: '10:00' },
{ name: '', id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '1 of 4', cutoff: '5:00', limit: '10:00' },
{ name: '', id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '2 of 4', cutoff: '5:00', limit: '10:00' },
{ name: '', id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '1 of 4', cutoff: '5:00', limit: '10:00' },
{ name: '', id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '2 of 4', cutoff: '5:00', limit: '10:00' },
{ name: '', id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '1 of 4', cutoff: '5:00', limit: '10:00' },
{ name: '', id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Combined Final', group: '2 of 4', cutoff: '5:00', limit: '10:00' },
{ name: '', id: '', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '10:00' },
{ name: '', id: '', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '10:00' },
{ name: '', id: '', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '10:00' },
{ name: '', id: '', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '10:00' },
{ name: '', id: '', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '10:00' },
{ name: '', id: '', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '10:00' },
{ name: '', id: '', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '10:00' },
{ name: '', id: '', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '10:00' },
{ name: '', id: '', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '10:00' },
{ name: '', id: '', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '10:00' },
{ name: '', id: '', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: '', id: '', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: '', id: '', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: '', id: '', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: '', id: '', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Combined Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
]
