window.mo3events =['6x6x6 Cube', '7x7x7 Cube', '3x3x3 Blindfolded', '4x4x4 Blindfolded', '5x5x5 Blindfolded'];

window.cumulativeevents =['3x3x3 Blindfolded','5x5x5 Blindfolded'];

window.bo2events = ['3x3x3 Multi-Blind'];

window.competitors = [
{ line_1: 'Pyraminx', line_2: 'Final Round', line_3: 'Group 1 of 5'},
{ name: 'Aiden Zupancic', wca_id: '2021ZUPA01', live_id: '42', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Albert Liu', wca_id: 'New Competitor', live_id: '54', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Asher Olson', wca_id: '2021OLSO01', live_id: '26', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Carter Cieslewicz', wca_id: '2020CIES01', live_id: '24', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Ethan Simons', wca_id: '2019SIMO10', live_id: '40', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Jackson Dempsey', wca_id: '2021DEMP01', live_id: '47', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Jaxson Lee', wca_id: 'New Competitor', live_id: '36', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Kellan Butler', wca_id: 'New Competitor', live_id: '17', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Kole Hicok', wca_id: 'New Competitor', live_id: '20', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Logan Liu', wca_id: '2021LIUL05', live_id: '12', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ name: 'London Franckowiak', wca_id: 'New Competitor', live_id: '60', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ line_1: 'Pyraminx', line_2: 'Final Round', line_3: 'Group 2 of 5'},
{ name: 'Benjamin Phillips', wca_id: '2019PHIL05', live_id: '22', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Benjamin Simons', wca_id: '2019SIMO09', live_id: '39', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Caroline Naser', wca_id: '2021NASE01', live_id: '15', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Joshua Block', wca_id: '2021BLOC01', live_id: '56', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Kaden Thompson', wca_id: '2021THOM07', live_id: '33', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Matthew Johnson', wca_id: '2019JOHN15', live_id: '55', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Roshen Thomas', wca_id: '2018THOM02', live_id: '41', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Tanner Lee Haddock', wca_id: '2021HADD01', live_id: '19', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Trey Linski', wca_id: '2021LINS02', live_id: '28', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Ty Portzen', wca_id: '2018PORT10', live_id: '62', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Warren Shepard', wca_id: '2017SHEP01', live_id: '50', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ line_1: 'Pyraminx', line_2: 'Final Round', line_3: 'Group 3 of 5'},
{ name: 'Adam Schwenn', wca_id: '2019SCHW06', live_id: '16', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Alex Lamont', wca_id: '2018LAMO02', live_id: '18', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Avi Jain', wca_id: '2022JAIN02', live_id: '38', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Ben Edwards', wca_id: '2019EDWA01', live_id: '37', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Blake Byl', wca_id: '2017BYLB01', live_id: '34', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Harrison Flowers', wca_id: '2021FLOW01', live_id: '58', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Isak Danke', wca_id: '2018DANK01', live_id: '23', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ name: 'John Eppley', wca_id: '2014EPPL01', live_id: '21', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Lisa Kucala', wca_id: '2019KUCA01', live_id: '10', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Shain Longbehn', wca_id: '2020LONG05', live_id: '27', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Zachary Garber', wca_id: '2014GARB01', live_id: '3', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ line_1: 'Pyraminx', line_2: 'Final Round', line_3: 'Group 4 of 5'},
{ name: 'Aaron Stettner', wca_id: '2017STET01', live_id: '31', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Antonio Bonessi', wca_id: '2019BONE03', live_id: '5', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Cale Schoon', wca_id: '2014SCHO02', live_id: '44', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Carter Thomas', wca_id: '2018THOM29', live_id: '35', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ name: 'CJ Sheng', wca_id: '2012SHEN02', live_id: '52', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ name: 'David Jiang ', wca_id: '2016JIAN13', live_id: '57', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Jake Buckley', wca_id: '2017BUCK01', live_id: '51', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ name: 'James Elliott', wca_id: '2021ELLI02', live_id: '9', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ name: 'James Quinn', wca_id: '2016QUIN01', live_id: '45', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Sebastian Carrillo', wca_id: '2018CARR07', live_id: '4', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Stephen Griggs', wca_id: '2014GRIG01', live_id: '25', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ line_1: 'Pyraminx', line_2: 'Final Round', line_3: 'Group 5 of 5'},
{ name: 'Andrew Karbusicky', wca_id: '2015KARB02', live_id: '46', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Andy Denney', wca_id: '2013DENN01', live_id: '6', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Blake Thompson', wca_id: '2010THOM03', live_id: '32', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Brian Johnson', wca_id: '2013JOHN10', live_id: '1', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Carter Kucala', wca_id: '2015KUCA01', live_id: '8', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Luke Garrett', wca_id: '2017GARR05', live_id: '13', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Marcus Kamen', wca_id: '2015KAME02', live_id: '14', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Nathan Popov', wca_id: '2018POPO02', live_id: '29', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Simon Kellum', wca_id: '2016KELL12', live_id: '7', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Walker Welch', wca_id: '2011WELC01', live_id: '53', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Zeke Mackay', wca_id: '2015MACK06', live_id: '2', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ line_1: 'Pyraminx', line_2: 'Final Round', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: '', cutoff: '-', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: '', cutoff: '-', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: '', cutoff: '-', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: '', cutoff: '-', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final Round', group: '', cutoff: '-', limit: '1:00' },
{ line_1: 'Clock', line_2: 'Final Round', line_3: 'Group 1 of 4'},
{ name: 'Aiden Zupancic', wca_id: '2021ZUPA01', live_id: '42', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Benjamin Phillips', wca_id: '2019PHIL05', live_id: '22', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Benjamin Simons', wca_id: '2019SIMO09', live_id: '39', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Carter Cieslewicz', wca_id: '2020CIES01', live_id: '24', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'James Elliott', wca_id: '2021ELLI02', live_id: '9', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'John Eppley', wca_id: '2014EPPL01', live_id: '21', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Shain Longbehn', wca_id: '2020LONG05', live_id: '27', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Ty Portzen', wca_id: '2018PORT10', live_id: '62', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '0:20', limit: '1:00' },
{ line_1: 'Clock', line_2: 'Final Round', line_3: 'Group 2 of 4'},
{ name: 'Alex Lamont', wca_id: '2018LAMO02', live_id: '18', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Andy Denney', wca_id: '2013DENN01', live_id: '6', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Blake Byl', wca_id: '2017BYLB01', live_id: '34', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Caroline Naser', wca_id: '2021NASE01', live_id: '15', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'David Jiang ', wca_id: '2016JIAN13', live_id: '57', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Lisa Kucala', wca_id: '2019KUCA01', live_id: '10', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Trey Linski', wca_id: '2021LINS02', live_id: '28', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Zachary Garber', wca_id: '2014GARB01', live_id: '3', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '0:20', limit: '1:00' },
{ line_1: 'Clock', line_2: 'Final Round', line_3: 'Group 3 of 4'},
{ name: 'Blake Thompson', wca_id: '2010THOM03', live_id: '32', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Carter Thomas', wca_id: '2018THOM29', live_id: '35', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'CJ Sheng', wca_id: '2012SHEN02', live_id: '52', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Isak Danke', wca_id: '2018DANK01', live_id: '23', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'James Quinn', wca_id: '2016QUIN01', live_id: '45', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Marcus Kamen', wca_id: '2015KAME02', live_id: '14', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Sebastian Carrillo', wca_id: '2018CARR07', live_id: '4', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Simon Kellum', wca_id: '2016KELL12', live_id: '7', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Stephen Griggs', wca_id: '2014GRIG01', live_id: '25', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '0:20', limit: '1:00' },
{ line_1: 'Clock', line_2: 'Final Round', line_3: 'Group 4 of 4'},
{ name: 'Brian Johnson', wca_id: '2013JOHN10', live_id: '1', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 4 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Cale Schoon', wca_id: '2014SCHO02', live_id: '44', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 4 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Carter Kucala', wca_id: '2015KUCA01', live_id: '8', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 4 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Jake Buckley', wca_id: '2017BUCK01', live_id: '51', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 4 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Luke Garrett', wca_id: '2017GARR05', live_id: '13', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 4 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Nathan Popov', wca_id: '2018POPO02', live_id: '29', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 4 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Walker Welch', wca_id: '2011WELC01', live_id: '53', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 4 of 4', cutoff: '0:20', limit: '1:00' },
{ name: 'Zeke Mackay', wca_id: '2015MACK06', live_id: '2', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: 'Group 4 of 4', cutoff: '0:20', limit: '1:00' },
{ line_1: 'Clock', line_2: 'Final Round', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: '', cutoff: '0:20', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: '', cutoff: '0:20', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: '', cutoff: '0:20', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: '', cutoff: '0:20', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final Round', group: '', cutoff: '0:20', limit: '1:00' },
{ line_1: 'Skewb', line_2: 'Final Round', line_3: 'Group 1 of 5'},
{ name: 'Adam Schwenn', wca_id: '2019SCHW06', live_id: '16', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Benjamin Simons', wca_id: '2019SIMO09', live_id: '39', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Jackson Dempsey', wca_id: '2021DEMP01', live_id: '47', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Joshua Block', wca_id: '2021BLOC01', live_id: '56', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Kaden Thompson', wca_id: '2021THOM07', live_id: '33', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Kellan Butler', wca_id: 'New Competitor', live_id: '17', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Kole Hicok', wca_id: 'New Competitor', live_id: '20', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Nicholas Grove', wca_id: '2019GROV03', live_id: '30', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Roshen Thomas', wca_id: '2018THOM02', live_id: '41', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Tanner Lee Haddock', wca_id: '2021HADD01', live_id: '19', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' },
{ line_1: 'Skewb', line_2: 'Final Round', line_3: 'Group 2 of 5'},
{ name: 'Aiden Zupancic', wca_id: '2021ZUPA01', live_id: '42', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Ben Edwards', wca_id: '2019EDWA01', live_id: '37', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Caroline Naser', wca_id: '2021NASE01', live_id: '15', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Carter Cieslewicz', wca_id: '2020CIES01', live_id: '24', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ name: 'John Eppley', wca_id: '2014EPPL01', live_id: '21', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Lisa Kucala', wca_id: '2019KUCA01', live_id: '10', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Logan Liu', wca_id: '2021LIUL05', live_id: '12', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Matthew Johnson', wca_id: '2019JOHN15', live_id: '55', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Trey Linski', wca_id: '2021LINS02', live_id: '28', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Warren Shepard', wca_id: '2017SHEP01', live_id: '50', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' },
{ line_1: 'Skewb', line_2: 'Final Round', line_3: 'Group 3 of 5'},
{ name: 'Alex Lamont', wca_id: '2018LAMO02', live_id: '18', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Antonio Bonessi', wca_id: '2019BONE03', live_id: '5', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Benjamin Phillips', wca_id: '2019PHIL05', live_id: '22', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Blake Byl', wca_id: '2017BYLB01', live_id: '34', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ name: 'David Jiang ', wca_id: '2016JIAN13', live_id: '57', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Harrison Flowers', wca_id: '2021FLOW01', live_id: '58', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Jake Buckley', wca_id: '2017BUCK01', live_id: '51', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Nathan Popov', wca_id: '2018POPO02', live_id: '29', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Ty Portzen', wca_id: '2018PORT10', live_id: '62', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Zachary Garber', wca_id: '2014GARB01', live_id: '3', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' },
{ line_1: 'Skewb', line_2: 'Final Round', line_3: 'Group 4 of 5'},
{ name: 'Aaron Stettner', wca_id: '2017STET01', live_id: '31', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Andrew Karbusicky', wca_id: '2015KARB02', live_id: '46', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Blake Thompson', wca_id: '2010THOM03', live_id: '32', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Carter Thomas', wca_id: '2018THOM29', live_id: '35', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ name: 'CJ Sheng', wca_id: '2012SHEN02', live_id: '52', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Isak Danke', wca_id: '2018DANK01', live_id: '23', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ name: 'James Elliott', wca_id: '2021ELLI02', live_id: '9', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Sebastian Carrillo', wca_id: '2018CARR07', live_id: '4', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Shain Longbehn', wca_id: '2020LONG05', live_id: '27', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Stephen Griggs', wca_id: '2014GRIG01', live_id: '25', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' },
{ line_1: 'Skewb', line_2: 'Final Round', line_3: 'Group 5 of 5'},
{ name: 'Andy Denney', wca_id: '2013DENN01', live_id: '6', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Brian Johnson', wca_id: '2013JOHN10', live_id: '1', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Cale Schoon', wca_id: '2014SCHO02', live_id: '44', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Carter Kucala', wca_id: '2015KUCA01', live_id: '8', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ name: 'James Quinn', wca_id: '2016QUIN01', live_id: '45', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Luke Garrett', wca_id: '2017GARR05', live_id: '13', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Marcus Kamen', wca_id: '2015KAME02', live_id: '14', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Simon Kellum', wca_id: '2016KELL12', live_id: '7', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Walker Welch', wca_id: '2011WELC01', live_id: '53', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ name: 'Zeke Mackay', wca_id: '2015MACK06', live_id: '2', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' },
{ line_1: 'Skewb', line_2: 'Final Round', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: '', cutoff: '-', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: '', cutoff: '-', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: '', cutoff: '-', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: '', cutoff: '-', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: 'Skewb', logo: 'logo_skewb.png', round: 'Final Round', group: '', cutoff: '-', limit: '1:00' },
{ line_1: '3x3x3 Cube', line_2: 'First Round', line_3: 'Group 1 of 5'},
{ name: 'Adam Schwenn', wca_id: '2019SCHW06', live_id: '16', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Aiden Zupancic', wca_id: '2021ZUPA01', live_id: '42', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Avi Jain', wca_id: '2022JAIN02', live_id: '38', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Eli Block', wca_id: 'New Competitor', live_id: '61', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Ethan Simons', wca_id: '2019SIMO10', live_id: '40', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Jaxson Lee', wca_id: 'New Competitor', live_id: '36', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Kaden Thompson', wca_id: '2021THOM07', live_id: '33', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Kellan Butler', wca_id: 'New Competitor', live_id: '17', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Kole Hicok', wca_id: 'New Competitor', live_id: '20', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'London Franckowiak', wca_id: 'New Competitor', live_id: '60', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Michael Sparks', wca_id: 'New Competitor', live_id: '49', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Ryan Adkins', wca_id: 'New Competitor', live_id: '59', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '10:00' }, 
{ line_1: '3x3x3 Cube', line_2: 'First Round', line_3: 'Group 2 of 5'},
{ name: 'Benjamin Simons', wca_id: '2019SIMO09', live_id: '39', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Caroline Naser', wca_id: '2021NASE01', live_id: '15', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Carter Cieslewicz', wca_id: '2020CIES01', live_id: '24', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Harrison Flowers', wca_id: '2021FLOW01', live_id: '58', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Jackson Dempsey', wca_id: '2021DEMP01', live_id: '47', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Lisa Kucala', wca_id: '2019KUCA01', live_id: '10', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Logan Liu', wca_id: '2021LIUL05', live_id: '12', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Matthew Johnson', wca_id: '2019JOHN15', live_id: '55', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Nicholas Grove', wca_id: '2019GROV03', live_id: '30', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Roshen Thomas', wca_id: '2018THOM02', live_id: '41', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Ty Portzen', wca_id: '2018PORT10', live_id: '62', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Warren Shepard', wca_id: '2017SHEP01', live_id: '50', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '10:00' }, 
{ line_1: '3x3x3 Cube', line_2: 'First Round', line_3: 'Group 3 of 5'},
{ name: 'Alex Lamont', wca_id: '2018LAMO02', live_id: '18', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Asher Olson', wca_id: '2021OLSO01', live_id: '26', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Austin Worley', wca_id: '2021WORL01', live_id: '11', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Benjamin Phillips', wca_id: '2019PHIL05', live_id: '22', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Blake Byl', wca_id: '2017BYLB01', live_id: '34', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Isak Danke', wca_id: '2018DANK01', live_id: '23', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Joshua Block', wca_id: '2021BLOC01', live_id: '56', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Sebastian Carrillo', wca_id: '2018CARR07', live_id: '4', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Shain Longbehn', wca_id: '2020LONG05', live_id: '27', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Tanner Lee Haddock', wca_id: '2021HADD01', live_id: '19', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Trey Linski', wca_id: '2021LINS02', live_id: '28', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ name: 'Zachary Garber', wca_id: '2014GARB01', live_id: '3', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube', line_2: 'First Round', line_3: 'Group 4 of 5'},
{ name: 'Aaron Stettner', wca_id: '2017STET01', live_id: '31', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Andrew Karbusicky', wca_id: '2015KARB02', live_id: '46', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Antonio Bonessi', wca_id: '2019BONE03', live_id: '5', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Ben Edwards', wca_id: '2019EDWA01', live_id: '37', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Carter Thomas', wca_id: '2018THOM29', live_id: '35', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'CJ Sheng', wca_id: '2012SHEN02', live_id: '52', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'David Jiang ', wca_id: '2016JIAN13', live_id: '57', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Jake Buckley', wca_id: '2017BUCK01', live_id: '51', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'James Elliott', wca_id: '2021ELLI02', live_id: '9', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'John Eppley', wca_id: '2014EPPL01', live_id: '21', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Nathan Popov', wca_id: '2018POPO02', live_id: '29', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Stephen Griggs', wca_id: '2014GRIG01', live_id: '25', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '10:00' }, 
{ line_1: '3x3x3 Cube', line_2: 'First Round', line_3: 'Group 5 of 5'},
{ name: 'Andy Denney', wca_id: '2013DENN01', live_id: '6', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Blake Thompson', wca_id: '2010THOM03', live_id: '32', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Brian Johnson', wca_id: '2013JOHN10', live_id: '1', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Cale Schoon', wca_id: '2014SCHO02', live_id: '44', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Carter Kucala', wca_id: '2015KUCA01', live_id: '8', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'James Quinn', wca_id: '2016QUIN01', live_id: '45', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Luke Garrett', wca_id: '2017GARR05', live_id: '13', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Marcus Kamen', wca_id: '2015KAME02', live_id: '14', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Simon Kellum', wca_id: '2016KELL12', live_id: '7', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Walker Welch', wca_id: '2011WELC01', live_id: '53', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' }, 
{ name: 'Zeke Mackay', wca_id: '2015MACK06', live_id: '2', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '10:00' }, 
{ line_1: '3x3x3 Cube', line_2: 'Round 1 of 2', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: '', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: '', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: '', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: '', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1 of 2', group: '', cutoff: '-', limit: '10:00' },
{ line_1: '2x2x2 Cube', line_2: 'First Round', line_3: 'Group 1 of 5'},
{ name: 'Benjamin Simons', wca_id: '2019SIMO09', live_id: '39', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Eli Block', wca_id: 'New Competitor', live_id: '61', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Ethan Simons', wca_id: '2019SIMO10', live_id: '40', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Jackson Dempsey', wca_id: '2021DEMP01', live_id: '47', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'James Elliott', wca_id: '2021ELLI02', live_id: '9', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Jaxson Lee', wca_id: 'New Competitor', live_id: '36', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Joshua Block', wca_id: '2021BLOC01', live_id: '56', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Kaden Thompson', wca_id: '2021THOM07', live_id: '33', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Kellan Butler', wca_id: 'New Competitor', live_id: '17', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Kole Hicok', wca_id: 'New Competitor', live_id: '20', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'London Franckowiak', wca_id: 'New Competitor', live_id: '60', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 1 of 5', cutoff: '-', limit: '1:00' }, 
{ line_1: '2x2x2 Cube', line_2: 'First Round', line_3: 'Group 2 of 5'},
{ name: 'Aiden Zupancic', wca_id: '2021ZUPA01', live_id: '42', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Avi Jain', wca_id: '2022JAIN02', live_id: '38', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Caroline Naser', wca_id: '2021NASE01', live_id: '15', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Lisa Kucala', wca_id: '2019KUCA01', live_id: '10', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Logan Liu', wca_id: '2021LIUL05', live_id: '12', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Matthew Johnson', wca_id: '2019JOHN15', live_id: '55', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Roshen Thomas', wca_id: '2018THOM02', live_id: '41', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Tanner Lee Haddock', wca_id: '2021HADD01', live_id: '19', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Trey Linski', wca_id: '2021LINS02', live_id: '28', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Ty Portzen', wca_id: '2018PORT10', live_id: '62', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Warren Shepard', wca_id: '2017SHEP01', live_id: '50', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 2 of 5', cutoff: '-', limit: '1:00' }, 
{ line_1: '2x2x2 Cube', line_2: 'First Round', line_3: 'Group 3 of 5'},
{ name: 'Aaron Stettner', wca_id: '2017STET01', live_id: '31', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Adam Schwenn', wca_id: '2019SCHW06', live_id: '16', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Alex Lamont', wca_id: '2018LAMO02', live_id: '18', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Asher Olson', wca_id: '2021OLSO01', live_id: '26', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Benjamin Phillips', wca_id: '2019PHIL05', live_id: '22', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Carter Cieslewicz', wca_id: '2020CIES01', live_id: '24', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Harrison Flowers', wca_id: '2021FLOW01', live_id: '58', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Isak Danke', wca_id: '2018DANK01', live_id: '23', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Nicholas Grove', wca_id: '2019GROV03', live_id: '30', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Shain Longbehn', wca_id: '2020LONG05', live_id: '27', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Zachary Garber', wca_id: '2014GARB01', live_id: '3', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 3 of 5', cutoff: '-', limit: '1:00' }, 
{ line_1: '2x2x2 Cube', line_2: 'First Round', line_3: 'Group 4 of 5'},
{ name: 'Andrew Karbusicky', wca_id: '2015KARB02', live_id: '46', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Ben Edwards', wca_id: '2019EDWA01', live_id: '37', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Blake Byl', wca_id: '2017BYLB01', live_id: '34', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Carter Thomas', wca_id: '2018THOM29', live_id: '35', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'CJ Sheng', wca_id: '2012SHEN02', live_id: '52', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'David Jiang ', wca_id: '2016JIAN13', live_id: '57', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Jake Buckley', wca_id: '2017BUCK01', live_id: '51', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'John Eppley', wca_id: '2014EPPL01', live_id: '21', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Marcus Kamen', wca_id: '2015KAME02', live_id: '14', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Nathan Popov', wca_id: '2018POPO02', live_id: '29', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Sebastian Carrillo', wca_id: '2018CARR07', live_id: '4', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Stephen Griggs', wca_id: '2014GRIG01', live_id: '25', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 4 of 5', cutoff: '-', limit: '1:00' }, 
{ line_1: '2x2x2 Cube', line_2: 'First Round', line_3: 'Group 5 of 5'},
{ name: 'Andy Denney', wca_id: '2013DENN01', live_id: '6', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Antonio Bonessi', wca_id: '2019BONE03', live_id: '5', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Blake Thompson', wca_id: '2010THOM03', live_id: '32', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Brian Johnson', wca_id: '2013JOHN10', live_id: '1', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Cale Schoon', wca_id: '2014SCHO02', live_id: '44', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Carter Kucala', wca_id: '2015KUCA01', live_id: '8', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'James Quinn', wca_id: '2016QUIN01', live_id: '45', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Luke Garrett', wca_id: '2017GARR05', live_id: '13', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Simon Kellum', wca_id: '2016KELL12', live_id: '7', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Walker Welch', wca_id: '2011WELC01', live_id: '53', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' }, 
{ name: 'Zeke Mackay', wca_id: '2015MACK06', live_id: '2', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: 'Group 5 of 5', cutoff: '-', limit: '1:00' }, 
{ line_1: '2x2x2 Cube', line_2: 'Round 1 of 2', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: '', cutoff: '-', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: '', cutoff: '-', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: '', cutoff: '-', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: '', cutoff: '-', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 1 of 2', group: '', cutoff: '-', limit: '1:00' },
{ line_1: 'Megaminx', line_2: 'Final Round', line_3: 'Group 1 of 3'},
{ name: 'Alex Lamont', wca_id: '2018LAMO02', live_id: '18', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 1 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Austin Worley', wca_id: '2021WORL01', live_id: '11', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 1 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Ben Edwards', wca_id: '2019EDWA01', live_id: '37', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 1 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Benjamin Phillips', wca_id: '2019PHIL05', live_id: '22', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 1 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'David Jiang ', wca_id: '2016JIAN13', live_id: '57', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 1 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Isak Danke', wca_id: '2018DANK01', live_id: '23', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 1 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'James Elliott', wca_id: '2021ELLI02', live_id: '9', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 1 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Matthew Johnson', wca_id: '2019JOHN15', live_id: '55', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 1 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Sebastian Carrillo', wca_id: '2018CARR07', live_id: '4', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 1 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Tanner Lee Haddock', wca_id: '2021HADD01', live_id: '19', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 1 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Trey Linski', wca_id: '2021LINS02', live_id: '28', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 1 of 3', cutoff: '1:30', limit: '3:00' },
{ line_1: 'Megaminx', line_2: 'Final Round', line_3: 'Group 2 of 3'},
{ name: 'Aaron Stettner', wca_id: '2017STET01', live_id: '31', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 2 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Andrew Karbusicky', wca_id: '2015KARB02', live_id: '46', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 2 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Antonio Bonessi', wca_id: '2019BONE03', live_id: '5', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 2 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Cale Schoon', wca_id: '2014SCHO02', live_id: '44', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 2 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Carter Kucala', wca_id: '2015KUCA01', live_id: '8', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 2 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Carter Thomas', wca_id: '2018THOM29', live_id: '35', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 2 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Jake Buckley', wca_id: '2017BUCK01', live_id: '51', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 2 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'John Eppley', wca_id: '2014EPPL01', live_id: '21', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 2 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Marcus Kamen', wca_id: '2015KAME02', live_id: '14', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 2 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Nathan Popov', wca_id: '2018POPO02', live_id: '29', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 2 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Zachary Garber', wca_id: '2014GARB01', live_id: '3', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 2 of 3', cutoff: '1:30', limit: '3:00' },
{ line_1: 'Megaminx', line_2: 'Final Round', line_3: 'Group 3 of 3'},
{ name: 'Andy Denney', wca_id: '2013DENN01', live_id: '6', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 3 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Blake Thompson', wca_id: '2010THOM03', live_id: '32', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 3 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Brian Johnson', wca_id: '2013JOHN10', live_id: '1', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 3 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'CJ Sheng', wca_id: '2012SHEN02', live_id: '52', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 3 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'James Quinn', wca_id: '2016QUIN01', live_id: '45', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 3 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Luke Garrett', wca_id: '2017GARR05', live_id: '13', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 3 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Simon Kellum', wca_id: '2016KELL12', live_id: '7', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 3 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Stephen Griggs', wca_id: '2014GRIG01', live_id: '25', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 3 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Walker Welch', wca_id: '2011WELC01', live_id: '53', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 3 of 3', cutoff: '1:30', limit: '3:00' },
{ name: 'Zeke Mackay', wca_id: '2015MACK06', live_id: '2', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: 'Group 3 of 3', cutoff: '1:30', limit: '3:00' },
{ line_1: 'Megaminx', line_2: 'Final Round', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: '', cutoff: '1:30', limit: '3:00' },
{ name: '', wca_id: '', live_id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: '', cutoff: '1:30', limit: '3:00' },
{ name: '', wca_id: '', live_id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: '', cutoff: '1:30', limit: '3:00' },
{ name: '', wca_id: '', live_id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: '', cutoff: '1:30', limit: '3:00' },
{ name: '', wca_id: '', live_id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final Round', group: '', cutoff: '1:30', limit: '3:00' },
{ line_1: '4x4x4 Cube', line_2: 'Final Round', line_3: 'Group 1 of 4'},
{ name: 'Asher Olson', wca_id: '2021OLSO01', live_id: '26', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Austin Worley', wca_id: '2021WORL01', live_id: '11', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Benjamin Phillips', wca_id: '2019PHIL05', live_id: '22', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Harrison Flowers', wca_id: '2021FLOW01', live_id: '58', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Jackson Dempsey', wca_id: '2021DEMP01', live_id: '47', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'James Elliott', wca_id: '2021ELLI02', live_id: '9', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Kaden Thompson', wca_id: '2021THOM07', live_id: '33', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Kellan Butler', wca_id: 'New Competitor', live_id: '17', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Kole Hicok', wca_id: 'New Competitor', live_id: '20', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Tanner Lee Haddock', wca_id: '2021HADD01', live_id: '19', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Trey Linski', wca_id: '2021LINS02', live_id: '28', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Warren Shepard', wca_id: '2017SHEP01', live_id: '50', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 1 of 4', cutoff: '1:15', limit: '3:00' }, 
{ line_1: '4x4x4 Cube', line_2: 'Final Round', line_3: 'Group 2 of 4'},
{ name: 'Alex Lamont', wca_id: '2018LAMO02', live_id: '18', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Ben Edwards', wca_id: '2019EDWA01', live_id: '37', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Benjamin Simons', wca_id: '2019SIMO09', live_id: '39', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Blake Byl', wca_id: '2017BYLB01', live_id: '34', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Caroline Naser', wca_id: '2021NASE01', live_id: '15', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Carter Cieslewicz', wca_id: '2020CIES01', live_id: '24', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Isak Danke', wca_id: '2018DANK01', live_id: '23', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Logan Liu', wca_id: '2021LIUL05', live_id: '12', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Matthew Johnson', wca_id: '2019JOHN15', live_id: '55', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Roshen Thomas', wca_id: '2018THOM02', live_id: '41', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Shain Longbehn', wca_id: '2020LONG05', live_id: '27', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Ty Portzen', wca_id: '2018PORT10', live_id: '62', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 2 of 4', cutoff: '1:15', limit: '3:00' }, 
{ line_1: '4x4x4 Cube', line_2: 'Final Round', line_3: 'Group 3 of 4'},
{ name: 'Aaron Stettner', wca_id: '2017STET01', live_id: '31', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Antonio Bonessi', wca_id: '2019BONE03', live_id: '5', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Carter Kucala', wca_id: '2015KUCA01', live_id: '8', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Carter Thomas', wca_id: '2018THOM29', live_id: '35', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'David Jiang ', wca_id: '2016JIAN13', live_id: '57', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Jake Buckley', wca_id: '2017BUCK01', live_id: '51', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'John Eppley', wca_id: '2014EPPL01', live_id: '21', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Marcus Kamen', wca_id: '2015KAME02', live_id: '14', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Nathan Popov', wca_id: '2018POPO02', live_id: '29', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Sebastian Carrillo', wca_id: '2018CARR07', live_id: '4', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Simon Kellum', wca_id: '2016KELL12', live_id: '7', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Zachary Garber', wca_id: '2014GARB01', live_id: '3', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 3 of 4', cutoff: '1:15', limit: '3:00' }, 
{ line_1: '4x4x4 Cube', line_2: 'Final Round', line_3: 'Group 4 of 4'},
{ name: 'Andrew Karbusicky', wca_id: '2015KARB02', live_id: '46', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 4 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Andy Denney', wca_id: '2013DENN01', live_id: '6', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 4 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Blake Thompson', wca_id: '2010THOM03', live_id: '32', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 4 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Brian Johnson', wca_id: '2013JOHN10', live_id: '1', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 4 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Cale Schoon', wca_id: '2014SCHO02', live_id: '44', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 4 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'CJ Sheng', wca_id: '2012SHEN02', live_id: '52', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 4 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'James Quinn', wca_id: '2016QUIN01', live_id: '45', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 4 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Luke Garrett', wca_id: '2017GARR05', live_id: '13', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 4 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Stephen Griggs', wca_id: '2014GRIG01', live_id: '25', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 4 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Walker Welch', wca_id: '2011WELC01', live_id: '53', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 4 of 4', cutoff: '1:15', limit: '3:00' }, 
{ name: 'Zeke Mackay', wca_id: '2015MACK06', live_id: '2', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: 'Group 4 of 4', cutoff: '1:15', limit: '3:00' }, 
{ line_1: '4x4x4 Cube', line_2: 'Final Round', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: '', cutoff: '1:15', limit: '3:00' },
{ name: '', wca_id: '', live_id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: '', cutoff: '1:15', limit: '3:00' },
{ name: '', wca_id: '', live_id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: '', cutoff: '1:15', limit: '3:00' },
{ name: '', wca_id: '', live_id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: '', cutoff: '1:15', limit: '3:00' },
{ name: '', wca_id: '', live_id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final Round', group: '', cutoff: '1:15', limit: '3:00' },
{ line_1: '2x2x2 Cube', line_2: 'Final Round', line_3: 'Group 1 of 1'},
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 2 of 2', group: 'Seed 1 of 12', cutoff: '-', limit: '1:00' }, 
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 2 of 2', group: 'Seed 2 of 12', cutoff: '-', limit: '1:00' }, 
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 2 of 2', group: 'Seed 3 of 12', cutoff: '-', limit: '1:00' }, 
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 2 of 2', group: 'Seed 4 of 12', cutoff: '-', limit: '1:00' }, 
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 2 of 2', group: 'Seed 5 of 12', cutoff: '-', limit: '1:00' }, 
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 2 of 2', group: 'Seed 6 of 12', cutoff: '-', limit: '1:00' }, 
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 2 of 2', group: 'Seed 7 of 12', cutoff: '-', limit: '1:00' }, 
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 2 of 2', group: 'Seed 8 of 12', cutoff: '-', limit: '1:00' }, 
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 2 of 2', group: 'Seed 9 of 12', cutoff: '-', limit: '1:00' }, 
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 2 of 2', group: 'Seed 10 of 12', cutoff: '-', limit: '1:00' }, 
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 2 of 2', group: 'Seed 11 of 12', cutoff: '-', limit: '1:00' }, 
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Round 2 of 2', group: 'Seed 12 of 12', cutoff: '-', limit: '1:00' }, 
{ line_1: '2x2x2 Cube', line_2: 'Final Round', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final Round', group: 'Seed \xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0', cutoff: '-', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final Round', group: 'Seed \xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0', cutoff: '-', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final Round', group: 'Seed \xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0', cutoff: '-', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final Round', group: 'Seed \xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0', cutoff: '-', limit: '1:00' },
{ name: '', wca_id: '', live_id: '', event: '2x2x2 Cube', logo: 'logo_222.png', round: 'Final Round', group: 'Seed \xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0', cutoff: '-', limit: '1:00' },
{ line_1: '3x3x3 Cube', line_2: 'Final Round', line_3: 'Group 1 of 1'},
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 1 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 2 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 3 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 4 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 5 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 6 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 7 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 8 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 9 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 10 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 11 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 12 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 13 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 14 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 15 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 16 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 17 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 18 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 19 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 20 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 21 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 22 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 23 of 24', cutoff: '-', limit: '10:00' }, 
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 2 of 2', group: 'Seed 24 of 24', cutoff: '-', limit: '10:00' }, 
{ line_1: '3x3x3 Cube', line_2: 'Final Round', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final Round', group: 'Seed \xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final Round', group: 'Seed \xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final Round', group: 'Seed \xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final Round', group: 'Seed \xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final Round', group: 'Seed \xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0', cutoff: '-', limit: '10:00' },
];