window.mo3events =['6x6x6 Cube', '7x7x7 Cube', '3x3x3 Blindfolded', '4x4x4 Blindfolded', '5x5x5 Blindfolded', 'Team Blindfolded'];

window.bo1events = ['3x3x3 Multiple Blindfolded'];

window.competitors = [
{ name: 'Aiden Bassenden Brazeau', id: 'New Competitor', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Brady Metherall', id: '2009METH01', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Brady Walintschek', id: '2019WALI01', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Briar Barron', id: '2016BARR15', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Daniel Pavelich', id: '2015PAVE01', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'David Drobner', id: '2018DROB01', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Jess Mitchell', id: '2018MITC03', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Joshua Graham', id: '2013GRAH01', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Louis Cormier', id: '2010CORM02', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Matthew Liu', id: '2018LIUM06', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Michael MacDonald Bradley', id: '2018BRAD08', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Nicholas Patterson', id: '2016PATT02', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Roan Paone', id: '2017PAON01', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Ryan Minjun Cho', id: '2014CHOR01', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Thomas Imada', id: '2018IMAD01', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Ben Madison', id: '2016MADI02', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Brant Holbein', id: '2014HOLB01', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Colin Cayen', id: '2015CAYE02', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Daniel Daoust', id: '2017DAOU01', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Dave Campbell', id: '2005CAMP01', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Devin Russell MacInnis', id: '2017MACI07', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Kevin Xu', id: '2018XUKE03', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Liam Orovec', id: '2014OROV01', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'LianCheng Guo', id: '2016GUOL01', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Matthew Lee', id: '2017LEEM03', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Max Murphy', id: '2016MURP05', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Max Xiong (熊锐明)', id: '2015XION03', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Ryan Wu', id: '2017WURY01', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Sebastian Desaulniers', id: '2018DESA05', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: 'Andrea Mitchell', id: '2018MITC05', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Brady Walintschek', id: '2019WALI01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Briar Barron', id: '2016BARR15', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Daniel Pavelich', id: '2015PAVE01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Dave Deriches', id: '2018DERI02', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Derek Walker', id: '2019WALK02', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Joshua Graham', id: '2013GRAH01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Liam Hohertz', id: 'New Competitor', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Matthew Liu', id: '2018LIUM06', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Ryan Pin Harry', id: '2015HARR01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Thomas Imada', id: '2018IMAD01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Aiden Bassenden Brazeau', id: 'New Competitor', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Arhaan Sareen', id: '2017SARE03', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Ben Bergen', id: '2015BERG10', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Brant Holbein', id: '2014HOLB01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Danny Li', id: '2018LIDA01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'David Drobner', id: '2018DROB01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Emile Compion', id: '2007COMP01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Kevin Xu', id: '2018XUKE03', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Matthew Krawczyk', id: '2017KRAW02', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Michael MacDonald Bradley', id: '2018BRAD08', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Sam Mogil', id: '2018MOGI01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Ben Madison', id: '2016MADI02', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Brady Metherall', id: '2009METH01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Daniel Daoust', id: '2017DAOU01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Ian Yeh', id: '2017YEHI01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Jess Mitchell', id: '2018MITC03', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Liam Orovec', id: '2014OROV01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Matthew Lee', id: '2017LEEM03', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Nicholas Patterson', id: '2016PATT02', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Richard Madison', id: '2017MADI03', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Roan Paone', id: '2017PAON01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Ryan Minjun Cho', id: '2014CHOR01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Gabrielle Morasse', id: '2013MORA08', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'LianCheng Guo', id: '2016GUOL01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Louis Cormier', id: '2010CORM02', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Max Murphy', id: '2016MURP05', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Max Xiong', id: '2015XION03', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Peter Douthwright', id: '2007DOUT01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Ryan Wu', id: '2017WURY01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Sascha Pugar', id: '2015PUGA01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Tommy Madison', id: '2017MADI01', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:30', limit: '5:00' },
{ name: 'Colin Cayen', id: '2015CAYE02', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Daniel Daoust', id: '2017DAOU01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'David Drobner', id: '2018DROB01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Joshua Graham', id: '2013GRAH01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Mathew Niznansky', id: '2018NIZN01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Max Murphy', id: '2016MURP05', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Omar Ellabban', id: '2018ELLA01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Ryan Hinds', id: '2018HIND01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Saro Vanayan', id: '2019VANA01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Sebastian Desaulniers', id: '2018DESA05', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Aiden Bassenden Brazeau', id: 'New Competitor', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Ben Madison', id: '2016MADI02', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Danny Li', id: '2018LIDA01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Devin Russell MacInnis', id: '2017MACI07', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Kevin Xu', id: '2018XUKE03', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Nazar Sushkov', id: '2019SUSH02', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Peter Stevens', id: '2019STEV01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Ryan Pin Harry', id: '2015HARR01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Sascha Pugar', id: '2015PUGA01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'William Fehr', id: '2018FEHR01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Brady Metherall', id: '2009METH01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Dave Campbell', id: '2005CAMP01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'LianCheng Guo', id: '2016GUOL01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Matthew Lee', id: '2017LEEM03', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Matthew Liu', id: '2018LIUM06', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Nicholas Patterson', id: '2016PATT02', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Ryan Minjun Cho', id: '2014CHOR01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Ryan Wu', id: '2017WURY01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Thomas Imada', id: '2018IMAD01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Alan Jia', id: '2017JIAA01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Brant Holbein', id: '2014HOLB01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Briar Barron', id: '2016BARR15', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Daniel Pavelich', id: '2015PAVE01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Gabrielle Morasse', id: '2013MORA08', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Jess Mitchell', id: '2018MITC03', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Liam Orovec', id: '2014OROV01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Louis Cormier', id: '2010CORM02', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Max Xiong', id: '2015XION03', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Michael MacDonald Bradley', id: '2018BRAD08', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Roan Paone', id: '2017PAON01', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '10:00' },
{ name: 'Aiden Bassenden Brazeau', id: 'New Competitor', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Andrii Denysenko', id: '2017DENY01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Dave Deriches', id: '2018DERI02', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'David Drobner', id: '2018DROB01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Josiah Smits', id: '2018SMIT30', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Kairui Huang', id: '2015HUAN51', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Liam Hohertz', id: 'New Competitor', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Matthew Jennings', id: '2018JENN02', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Omar Ellabban', id: '2018ELLA01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Ryan Pin Harry', id: '2015HARR01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Sebastian Desaulniers', id: '2018DESA05', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Alex Jung', id: '2018JUNG02', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Arhaan Sareen', id: '2017SARE03', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Daniel Daoust', id: '2017DAOU01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Danny Li', id: '2018LIDA01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Derek Walker', id: '2019WALK02', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Kevin Xu', id: '2018XUKE03', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Mathew Niznansky', id: '2018NIZN01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Michael MacDonald Bradley', id: '2018BRAD08', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Peter Douthwright', id: '2007DOUT01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Peter Stevens', id: '2019STEV01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Saro Vanayan', id: '2019VANA01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Thomas Imada', id: '2018IMAD01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Ben Bergen', id: '2015BERG10', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Brant Holbein', id: '2014HOLB01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Joshua Graham', id: '2013GRAH01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'LianCheng Guo', id: '2016GUOL01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Matthew Krawczyk', id: '2017KRAW02', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Matthew Lee', id: '2017LEEM03', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Max Xiong', id: '2015XION03', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Nicholas Patterson', id: '2016PATT02', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Roan Paone', id: '2017PAON01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Ryan Wu', id: '2017WURY01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Sam Mogil', id: '2018MOGI01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Samuel Moran', id: '2015MORA08', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '3 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Ben Madison', id: '2016MADI02', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Brady Metherall', id: '2009METH01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Briar Barron', id: '2016BARR15', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Daniel Pavelich', id: '2015PAVE01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Ethan Erez', id: '2017EREZ01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Ian Yeh', id: '2017YEHI01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Jess Mitchell', id: '2018MITC03', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Liam Orovec', id: '2014OROV01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Louis Cormier', id: '2010CORM02', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Max Murphy', id: '2016MURP05', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Owen Bailey-Braun', id: '2019BAIL01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Sascha Pugar', id: '2015PUGA01', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '4 of 4', cutoff: '0:45', limit: '5:00' },
{ name: 'Andrea Mitchell', id: '2018MITC05', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Ben Worden', id: 'New Competitor', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Daniel Papernov', id: '2019PAPE01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'David Drobner', id: '2018DROB01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Derek Walker', id: '2019WALK02', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Docité Oren Schandry', id: '2019SCHA03', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Jason Nguyen', id: 'New Competitor', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Liam Hohertz', id: 'New Competitor', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Matthew Jennings', id: '2018JENN02', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Michael Russell', id: 'New Competitor', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Peter Stevens', id: '2019STEV01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Vera Beal', id: '2018BEAL02', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Andrii Denysenko', id: '2017DENY01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Brady Walintschek', id: '2019WALI01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Brant Holbein', id: '2014HOLB01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Brian Ignacio', id: '2019IGNA01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Danny Li', id: '2018LIDA01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Erik Lee', id: '2018LEEE05', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Joseph Rouben', id: '2018ROUB01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Mathew Niznansky', id: '2018NIZN01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Matthew Liu', id: '2018LIUM06', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Nazar Sushkov', id: '2019SUSH02', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Tin Huang', id: '2019HUAN05', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'William Fehr', id: '2018FEHR01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Daniel Daoust', id: '2017DAOU01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Daniel Pavelich', id: '2015PAVE01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Devin Russell MacInnis', id: '2017MACI07', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Jensen Belen-Brown', id: '2016BELE02', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Matthew Krawczyk', id: '2017KRAW02', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Omar Ellabban', id: '2018ELLA01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Owen Bailey-Braun', id: '2019BAIL01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Sam Mogil', id: '2018MOGI01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Saro Vanayan', id: '2019VANA01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Thomas Imada', id: '2018IMAD01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Alex Jung', id: '2018JUNG02', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Ben Bergen', id: '2015BERG10', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Dave Deriches', id: '2018DERI02', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Joshua Graham', id: '2013GRAH01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Josiah Smits', id: '2018SMIT30', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Kevin Xu', id: '2018XUKE03', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'LianCheng Guo', id: '2016GUOL01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Michael MacDonald Bradley', id: '2018BRAD08', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Peter Douthwright', id: '2007DOUT01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Ryan Hinds', id: '2018HIND01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Samuel Moran', id: '2015MORA08', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Sascha Pugar', id: '2015PUGA01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Sebastian Desaulniers', id: '2018DESA05', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Alex Knegt', id: '2018KNEG01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Briar Barron', id: '2016BARR15', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Ethan Erez', id: '2017EREZ01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Ian Yeh', id: '2017YEHI01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Jess Mitchell', id: '2018MITC03', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Kairui Huang', id: '2015HUAN51', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Liam Orovec', id: '2014OROV01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Louis Cormier', id: '2010CORM02', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Matthew Lee', id: '2017LEEM03', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Nicholas Patterson', id: '2016PATT02', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Roan Paone', id: '2017PAON01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Ryan Pin Harry', id: '2015HARR01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Ryan Wu', id: '2017WURY01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Alan Jia', id: '2017JIAA01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Arhaan Sareen', id: '2017SARE03', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Ben Madison', id: '2016MADI02', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Brady Metherall', id: '2009METH01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Colin Cayen', id: '2015CAYE02', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Dave Campbell', id: '2005CAMP01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Emile Compion', id: '2007COMP01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Gabrielle Morasse', id: '2013MORA08', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Max Murphy', id: '2016MURP05', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Max Xiong', id: '2015XION03', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Ryan Minjun Cho', id: '2014CHOR01', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Wenda Jiang', id: '2013JIAN11', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Alex Jung', id: '2018JUNG02', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Brian Ignacio', id: '2019IGNA01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Danny Li', id: '2018LIDA01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Erik Lee', id: '2018LEEE05', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Ian Yeh', id: '2017YEHI01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Joshua Graham', id: '2013GRAH01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Kevin Xu', id: '2018XUKE03', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Mathew Niznansky', id: '2018NIZN01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Matthew Liu', id: '2018LIUM06', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Peter Douthwright', id: '2007DOUT01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Ryan Hinds', id: '2018HIND01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Ryan Pin Harry', id: '2015HARR01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Sascha Pugar', id: '2015PUGA01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Aiden Bassenden Brazeau', id: 'New Competitor', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Brady Walintschek', id: '2019WALI01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Daniel Daoust', id: '2017DAOU01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '5:00' },
{ name: 'David Drobner', id: '2018DROB01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Docité Oren Schandry', id: '2019SCHA03', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Joseph Rouben', id: '2018ROUB01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Josiah Smits', id: '2018SMIT30', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '5:00' },
{ name: 'LianCheng Guo', id: '2016GUOL01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Matthew Jennings', id: '2018JENN02', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Nazar Sushkov', id: '2019SUSH02', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Peter Stevens', id: '2019STEV01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Saro Vanayan', id: '2019VANA01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Sebastian Desaulniers', id: '2018DESA05', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Vera Beal', id: '2018BEAL02', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Ben Bergen', id: '2015BERG10', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Briar Barron', id: '2016BARR15', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Colin Cayen', id: '2015CAYE02', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Daniel Pavelich', id: '2015PAVE01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Dave Deriches', id: '2018DERI02', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Matthew Krawczyk', id: '2017KRAW02', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Matthew Lee', id: '2017LEEM03', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Michael MacDonald Bradley', id: '2018BRAD08', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Nicholas Patterson', id: '2016PATT02', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Roan Paone', id: '2017PAON01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Ryan Wu', id: '2017WURY01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Sam Mogil', id: '2018MOGI01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '5:00' },
{ name: 'William Fehr', id: '2018FEHR01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '3 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Arhaan Sareen', id: '2017SARE03', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Ben Madison', id: '2016MADI02', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Brady Metherall', id: '2009METH01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Brant Holbein', id: '2014HOLB01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Gabrielle Morasse', id: '2013MORA08', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Jensen Belen-Brown', id: '2016BELE02', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Jess Mitchell', id: '2018MITC03', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Liam Orovec', id: '2014OROV01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Louis Cormier', id: '2010CORM02', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Max Murphy', id: '2016MURP05', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Max Xiong', id: '2015XION03', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Omar Ellabban', id: '2018ELLA01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Owen Bailey-Braun', id: '2019BAIL01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Sarah Strong', id: '2007STRO01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Thomas Imada', id: '2018IMAD01', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '4 of 4', cutoff: '-', limit: '5:00' },
{ name: 'Alex Jung', id: '2018JUNG02', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'David Drobner', id: '2018DROB01', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Gabrielle Morasse', id: '2013MORA08', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Jess Mitchell', id: '2018MITC03', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'LianCheng Guo', id: '2016GUOL01', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Matthew Lee', id: '2017LEEM03', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Nicholas Patterson', id: '2016PATT02', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Sam Mogil', id: '2018MOGI01', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Sebastian Desaulniers', id: '2018DESA05', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Aiden Bassenden Brazeau', id: 'New Competitor', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Daniel Daoust', id: '2017DAOU01', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Kevin Xu', id: '2018XUKE03', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Louis Cormier', id: '2010CORM02', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Matthew Krawczyk', id: '2017KRAW02', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Max Murphy', id: '2016MURP05', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Max Xiong', id: '2015XION03', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Michael MacDonald Bradley', id: '2018BRAD08', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Roan Paone', id: '2017PAON01', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Ryan Wu', id: '2017WURY01', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Samuel Moran', id: '2015MORA08', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'William Fehr', id: '2018FEHR01', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '5:00' },
{ name: 'Aiden Bassenden Brazeau', id: 'New Competitor', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Alex Knegt', id: '2018KNEG01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Daniel Papernov', id: '2019PAPE01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Danny Li', id: '2018LIDA01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'David Drobner', id: '2018DROB01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Hisham Ahmed Khan', id: 'New Competitor', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Jesse Hek', id: 'New Competitor', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Josiah Smits', id: '2018SMIT30', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Mathew Niznansky', id: '2018NIZN01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Matthew Liu', id: '2018LIUM06', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Michael Russell', id: 'New Competitor', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Ryan Hinds', id: '2018HIND01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Brady Walintschek', id: '2019WALI01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Derek Walker', id: '2019WALK02', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Devin Russell MacInnis', id: '2017MACI07', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Jason Nguyen', id: 'New Competitor', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Joseph Rouben', id: '2018ROUB01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Liam Hohertz', id: 'New Competitor', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Peter Douthwright', id: '2007DOUT01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Peter Stevens', id: '2019STEV01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Sascha Pugar', id: '2015PUGA01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Tommy Madison', id: '2017MADI01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Vera Beal', id: '2018BEAL02', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Alex Jung', id: '2018JUNG02', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Andrii Denysenko', id: '2017DENY01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Briar Barron', id: '2016BARR15', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Colin Cayen', id: '2015CAYE02', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Dave Deriches', id: '2018DERI02', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Jess Mitchell', id: '2018MITC03', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Joshua Graham', id: '2013GRAH01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Kevin Xu', id: '2018XUKE03', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'LianCheng Guo', id: '2016GUOL01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Nazar Sushkov', id: '2019SUSH02', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Sam Mogil', id: '2018MOGI01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '3 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Brady Metherall', id: '2009METH01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Daniel Daoust', id: '2017DAOU01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Docité Oren Schandry', id: '2019SCHA03', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Erik Lee', id: '2018LEEE05', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Matthew Krawczyk', id: '2017KRAW02', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Michael MacDonald Bradley', id: '2018BRAD08', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Omar Ellabban', id: '2018ELLA01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Owen Bailey-Braun', id: '2019BAIL01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Samuel Moran', id: '2015MORA08', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Sebastian Desaulniers', id: '2018DESA05', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Tin Huang', id: '2019HUAN05', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'William Fehr', id: '2018FEHR01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '4 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Arhaan Sareen', id: '2017SARE03', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Ben Madison', id: '2016MADI02', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Gabrielle Morasse', id: '2013MORA08', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Kairui Huang', id: '2015HUAN51', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Liam Orovec', id: '2014OROV01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Louis Cormier', id: '2010CORM02', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Max Murphy', id: '2016MURP05', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Nicholas Patterson', id: '2016PATT02', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Nima Bolourchian', id: '2017BOLO01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Ryan Wu', id: '2017WURY01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Thomas Imada', id: '2018IMAD01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '5 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Alan Jia', id: '2017JIAA01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Ben Bergen', id: '2015BERG10', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Brant Holbein', id: '2014HOLB01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Daniel Pavelich', id: '2015PAVE01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Dave Campbell', id: '2005CAMP01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Ethan Erez', id: '2017EREZ01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Ian Yeh', id: '2017YEHI01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Jensen Belen-Brown', id: '2016BELE02', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Matthew Lee', id: '2017LEEM03', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Max Xiong', id: '2015XION03', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Roan Paone', id: '2017PAON01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Ryan Pin Harry', id: '2015HARR01', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '6 of 6', cutoff: '-', limit: '5:00' },
{ name: 'Salty Bois', id: 'Joaquin Abarca & Nima Bolourchian', event: 'Team Blindfolded', logo: 'logo_333bf.png', round: 'Unofficial', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: 'Heston Bois', id: 'Matthew Lee	& Roan Paone', event: 'Team Blindfolded', logo: 'logo_333bf.png', round: 'Unofficial', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: 'DNF', id: 'Sebastian Desaulniers & Max Murphy', event: 'Team Blindfolded', logo: 'logo_333bf.png', round: 'Unofficial', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: 'DABlind', id: 'Alex Jung & Dave Deriches', event: 'Team Blindfolded', logo: 'logo_333bf.png', round: 'Unofficial', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: 'Lí', id: 'Thomas Imada & Kevin Xu', event: 'Team Blindfolded', logo: 'logo_333bf.png', round: 'Unofficial', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: 'Egg', id: 'Tin Huang & Parantap Bhatt', event: 'Team Blindfolded', logo: 'logo_333bf.png', round: 'Unofficial', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: 'Team Blindfolded', logo: 'logo_333bf.png', round: 'Unofficial', group: '1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: '', id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: '', id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: '', id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: '', id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: '', id: '', event: '4x4x4 Cube', logo: 'logo_444.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: '', id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '5:00' },
{ name: '', id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '5:00' },
{ name: '', id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '5:00' },
{ name: '', id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '5:00' },
{ name: '', id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '5:00' },
{ name: '', id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '5:00' },
{ name: '', id: '', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '5:00' },
{ name: '', id: '', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '5:00' },
{ name: '', id: '', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '5:00' },
{ name: '', id: '', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '5:00' },
{ name: '', id: '', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '1 of 2', cutoff: '3:00', limit: '5:00' },
{ name: '', id: '', event: '3x3x3 With Feet', logo: 'logo_333ft.png', round: 'Combined Final', group: '2 of 2', cutoff: '3:00', limit: '5:00' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '1 of 6', cutoff: '-', limit: '5:00' },
{ name: '', id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '2 of 6', cutoff: '-', limit: '5:00' },
{ name: '', id: '', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:45', limit: '5:00' },
{ name: '', id: '', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:45', limit: '5:00' },
{ name: '', id: '', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:45', limit: '5:00' },
{ name: '', id: '', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:45', limit: '5:00' },
{ name: '', id: '', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:45', limit: '5:00' },
{ name: '', id: '', event: 'Square-1', logo: 'logo_sq1.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:45', limit: '5:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:30', limit: '5:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:30', limit: '5:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:30', limit: '5:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:30', limit: '5:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '1 of 4', cutoff: '0:30', limit: '5:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Combined Final', group: '2 of 4', cutoff: '0:30', limit: '5:00' },
{ name: '', id: '', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '1 of 4', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '6x6x6 Cube', logo: 'logo_666.png', round: 'Final', group: '2 of 4', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '2 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '1 of 2', cutoff: '-', limit: '10:00' },
{ name: '', id: '', event: '7x7x7 Cube', logo: 'logo_777.png', round: 'Final', group: '2 of 2', cutoff: '-', limit: '10:00' },
]
