window.mo3events =['6x6x6 Cube', '7x7x7 Cube', '3x3x3 Blindfolded', '4x4x4 Blindfolded', '5x5x5 Blindfolded', 'Unofficial Team Relay'];

window.cumulativeevents =['3x3x3 Blindfolded', '4x4x4 Blindfolded', '5x5x5 Blindfolded'];

window.bo1events = ['3x3x3 Multi-Blind'];

window.bo2events = ['3x3x3 Multi-Blind'];

window.bo3events = ['3x3x3 Multi-Blind'];

window.sizeChanges = {
	'David Ignacio Gonzalez Lugo': '38px',
}

window.competitors = [
{ line_1: '3x3x3 Cube', line_2: 'Round 1', line_3: 'Group 1 of 6'},
{ name: 'Alex Ning', wca_id: 'New Competitor', live_id: '102', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Christian Aiello', wca_id: '2017AIEL01', live_id: '134', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Dave Deriches', wca_id: '2018DERI02', live_id: '15', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'David Burchill', wca_id: 'New Competitor', live_id: '86', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Devin Russell MacInnis', wca_id: '2017MACI07', live_id: '73', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Iain Holla', wca_id: '2019HOLL05', live_id: '70', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jesse Wang', wca_id: 'New Competitor', live_id: '114', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jessica Ying', wca_id: '2017YING02', live_id: '120', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Joaquin Abarca', wca_id: '2017ABAR02', live_id: '17', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Keegan Phillips', wca_id: '2019PHIL06', live_id: '27', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Kevin Xu', wca_id: '2018XUKE03', live_id: '127', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Matthew Garcia', wca_id: 'New Competitor', live_id: '128', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Michael Zheng', wca_id: '2015ZHEN17', live_id: '36', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Nihaas Kotni', wca_id: 'New Competitor', live_id: '12', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Pramathaditya Pathak', wca_id: '2018PATH02', live_id: '55', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Ray Vince Ong', wca_id: '2012ONGR01', live_id: '33', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Robert Nelson', wca_id: '2011NELS01', live_id: '65', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Samson Wu', wca_id: '2015WUSA01', live_id: '41', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Sarah Strong', wca_id: '2007STRO01', live_id: '1', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Stefano Coulter', wca_id: '2018COUL01', live_id: '13', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Vaishnav SriSai Ravulaparthi', wca_id: 'New Competitor', live_id: '84', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube', line_2: 'Round 1', line_3: 'Group 2 of 6'},
{ name: 'Aiden Yim', wca_id: '2019YIMA01', live_id: '60', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Andrew Yeung', wca_id: 'New Competitor', live_id: '99', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Callum Smith', wca_id: '2019SMIT09', live_id: '124', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Derrick Ha', wca_id: 'New Competitor', live_id: '89', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Ian Yeh', wca_id: '2017YEHI01', live_id: '123', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jack Costa', wca_id: '2019COST11', live_id: '80', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'John Travolo', wca_id: 'New Competitor', live_id: '5', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jonathan Esparaz', wca_id: '2013ESPA01', live_id: '18', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Koda Arthur Cobierski', wca_id: '2019COBI01', live_id: '8', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Lucas Jacobs', wca_id: '2018JACO10', live_id: '23', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Mathew Niznansky', wca_id: '2018NIZN01', live_id: '56', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Matthew Karunakaran', wca_id: 'New Competitor', live_id: '126', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Nicole Wang', wca_id: '2018WANN03', live_id: '115', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Nima Bolourchian', wca_id: '2017BOLO01', live_id: '100', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Noah Tremblay', wca_id: '2019TREM02', live_id: '118', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Prosper Huang', wca_id: '2018HUAP02', live_id: '104', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Ronan William Odell', wca_id: 'New Competitor', live_id: '45', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Setu Marathe', wca_id: '2017MARA04', live_id: '82', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Thomas Imada', wca_id: '2018IMAD01', live_id: '64', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Viswathiha Mylashan', wca_id: 'New Competitor', live_id: '136', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'William Fehr', wca_id: '2018FEHR01', live_id: '16', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube', line_2: 'Round 1', line_3: 'Group 3 of 6'},
{ name: 'Aryan Ved', wca_id: '2018VEDA02', live_id: '2', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Branavan Keethabaskaran', wca_id: 'New Competitor', live_id: '137', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Brandon Chu', wca_id: '2018CHUB06', live_id: '105', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Emily Hu', wca_id: 'New Competitor', live_id: '122', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jacky Chen', wca_id: '2020CHEN04', live_id: '117', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jensen Belen-Brown', wca_id: '2016BELE02', live_id: '35', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Joon Song', wca_id: '2019SONG21', live_id: '46', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jude Wheeler-Dee', wca_id: 'New Competitor', live_id: '78', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Kai Savage', wca_id: '2020SAVA04', live_id: '76', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Louis Cormier', wca_id: '2010CORM02', live_id: '24', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Louise Cormier', wca_id: '2013CORM01', live_id: '25', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Max Murphy', wca_id: '2016MURP05', live_id: '20', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Michael Bradley', wca_id: '2018BRAD08', live_id: '3', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Minjae Kim', wca_id: 'New Competitor', live_id: '101', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Mohammedreza Moghaddam', wca_id: '2019MOGH01', live_id: '131', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Owen Muldoon', wca_id: '2018MULD01', live_id: '48', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Parker Piekosz', wca_id: 'New Competitor', live_id: '95', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Rose Zheng', wca_id: 'New Competitor', live_id: '71', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Ryan Wu', wca_id: '2017WURY01', live_id: '14', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Sebastian Virág', wca_id: '2019VIRA01', live_id: '59', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Youssef Ali', wca_id: 'New Competitor', live_id: '116', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube', line_2: 'Round 1', line_3: 'Group 4 of 6'},
{ name: 'Alyssa Esparaz', wca_id: '2014ESPA01', live_id: '38', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Atharva Medihala', wca_id: '2019MEDI09', live_id: '111', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Austin Collins', wca_id: '2019COLL08', live_id: '72', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Brennen Lin', wca_id: '2016LINB01', live_id: '75', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Brian Fudem', wca_id: 'New Competitor', live_id: '113', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Dylan Yihan Dai', wca_id: '2018DAID01', live_id: '58', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Elliot Mauricette', wca_id: '2019MAUR04', live_id: '74', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Evan Rowland', wca_id: 'New Competitor', live_id: '28', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Hongda Wu', wca_id: '2017WUHO01', live_id: '31', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jess Mitchell', wca_id: '2018MITC03', live_id: '57', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Larry Shi', wca_id: '2019SHIL03', live_id: '88', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Leon Qian', wca_id: 'New Competitor', live_id: '30', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Myles David Suchma', wca_id: 'New Competitor', live_id: '79', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Orion Donovan', wca_id: '2016DONO02', live_id: '61', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Owen Bailey-Braun', wca_id: '2019BAIL01', live_id: '63', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Prahaas Kotni', wca_id: 'New Competitor', live_id: '7', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Roan Paone', wca_id: '2017PAON01', live_id: '10', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Rymand Moarefi', wca_id: 'New Competitor', live_id: '29', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Shanglin Ye', wca_id: '2013YESH01', live_id: '22', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Toyo Witzmann', wca_id: '2018WITZ01', live_id: '66', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube', line_2: 'Round 1', line_3: 'Group 5 of 6'},
{ name: 'Abdullah Gulab', wca_id: '2014GULA02', live_id: '44', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Adithya Medihala', wca_id: '2019MEDI16', live_id: '112', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Andry Rakoto', wca_id: '2016RAKO02', live_id: '19', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Caleb Chang', wca_id: 'New Competitor', live_id: '40', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Derek Kong', wca_id: '2017KONG08', live_id: '39', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Docité Oren Schandry', wca_id: '2019SCHA03', live_id: '53', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Emmanuel Intac', wca_id: '2018INTA01', live_id: '62', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Ethan Yeung', wca_id: '2019YEUN02', live_id: '90', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Garrett Banks', wca_id: 'New Competitor', live_id: '47', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Joey Saia', wca_id: '2017SAIA01', live_id: '130', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jonathan Ferraioli', wca_id: '2017FERR12', live_id: '6', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Krish Ved', wca_id: '2018VEDK01', live_id: '107', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Lucas Nieuwland', wca_id: '2018NIEU01', live_id: '11', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Marco Yang', wca_id: '2017YANG62', live_id: '37', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Marko Young', wca_id: 'New Competitor', live_id: '68', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Nathan Terpstra', wca_id: '2019TERP03', live_id: '85', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Rene Desaulniers', wca_id: 'New Competitor', live_id: '98', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Shelby Russell', wca_id: 'New Competitor', live_id: '132', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Stanley Wang', wca_id: '2017WANS05', live_id: '108', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Zhivko Radkov Dimitrov', wca_id: '2017DIMI01', live_id: '81', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube', line_2: 'Round 1', line_3: 'Group 6 of 6'},
{ name: 'Alan Diaz', wca_id: '2018DIAZ29', live_id: '106', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Chang Shi', wca_id: 'New Competitor', live_id: '110', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Colin Gawthroupe', wca_id: '2019GAWT01', live_id: '103', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Harry George', wca_id: 'New Competitor', live_id: '77', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Isaac Lau', wca_id: '2016LAUI01', live_id: '34', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jack Smith', wca_id: '2019SMIT10', live_id: '125', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'James Hocevar', wca_id: '2016HOCE02', live_id: '54', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'James Wang', wca_id: '2019WANJ15', live_id: '4', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Liam Forth', wca_id: '2018FORT04', live_id: '97', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Liam Savarino', wca_id: '2018SAVA01', live_id: '32', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Lin Salvo', wca_id: '2019SALV05', live_id: '129', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Massimo Corrado Caia', wca_id: '2019CAIA01', live_id: '109', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Matthew Lee', wca_id: '2017LEEM03', live_id: '51', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Max Xiong', wca_id: '2015XION03', live_id: '119', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Nathan Wang', wca_id: 'New Competitor', live_id: '9', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Omar Ellabban', wca_id: '2018ELLA01', live_id: '94', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Richard Li', wca_id: 'New Competitor', live_id: '83', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Tarandeep Mittal', wca_id: '2014MITT02', live_id: '21', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Tin Huang', wca_id: '2019HUAN05', live_id: '42', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Tristan Beaulne', wca_id: 'New Competitor', live_id: '87', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 Cube', line_2: 'Round 1', line_3: 'Extras' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ line_1: 'Pyraminx', line_2: 'Round 1', line_3: 'Group 1 of 6'},
{ name: 'Alan Diaz', wca_id: '2018DIAZ29', live_id: '106', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Emily Hu', wca_id: 'New Competitor', live_id: '122', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Iain Holla', wca_id: '2019HOLL05', live_id: '70', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'James Hocevar', wca_id: '2016HOCE02', live_id: '54', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Joon Song', wca_id: '2019SONG21', live_id: '46', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Kai Savage', wca_id: '2020SAVA04', live_id: '76', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Lucas Nieuwland', wca_id: '2018NIEU01', live_id: '11', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Massimo Corrado Caia', wca_id: '2019CAIA01', live_id: '109', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Matthew Lee', wca_id: '2017LEEM03', live_id: '51', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Nihaas Kotni', wca_id: 'New Competitor', live_id: '12', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Owen Bailey-Braun', wca_id: '2019BAIL01', live_id: '63', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Roan Paone', wca_id: '2017PAON01', live_id: '10', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Rose Zheng', wca_id: 'New Competitor', live_id: '71', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Samson Wu', wca_id: '2015WUSA01', live_id: '41', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Toyo Witzmann', wca_id: '2018WITZ01', live_id: '66', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Zhivko Radkov Dimitrov', wca_id: '2017DIMI01', live_id: '81', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ line_1: 'Pyraminx', line_2: 'Round 1', line_3: 'Group 2 of 6'},
{ name: 'Andrew Yeung', wca_id: 'New Competitor', live_id: '99', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Colin Gawthroupe', wca_id: '2019GAWT01', live_id: '103', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Dave Deriches', wca_id: '2018DERI02', live_id: '15', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Evan Rowland', wca_id: 'New Competitor', live_id: '28', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Ian Yeh', wca_id: '2017YEHI01', live_id: '123', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Joey Saia', wca_id: '2017SAIA01', live_id: '130', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Keegan Phillips', wca_id: '2019PHIL06', live_id: '27', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Krish Ved', wca_id: '2018VEDK01', live_id: '107', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Marco Yang', wca_id: '2017YANG62', live_id: '37', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Mathew Niznansky', wca_id: '2018NIZN01', live_id: '56', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Mohammedreza Moghaddam', wca_id: '2019MOGH01', live_id: '131', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Noah Tremblay', wca_id: '2019TREM02', live_id: '118', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Prosper Huang', wca_id: '2018HUAP02', live_id: '104', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Rymand Moarefi', wca_id: 'New Competitor', live_id: '29', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Stefano Coulter', wca_id: '2018COUL01', live_id: '13', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: 'William Fehr', wca_id: '2018FEHR01', live_id: '16', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ line_1: 'Pyraminx', line_2: 'Round 1', line_3: 'Group 3 of 6'},
{ name: 'Abdullah Gulab', wca_id: '2014GULA02', live_id: '44', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Adithya Medihala', wca_id: '2019MEDI16', live_id: '112', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Aryan Ved', wca_id: '2018VEDA02', live_id: '2', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Austin Collins', wca_id: '2019COLL08', live_id: '72', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Docité Oren Schandry', wca_id: '2019SCHA03', live_id: '53', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Dylan Yihan Dai', wca_id: '2018DAID01', live_id: '58', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Elliot Mauricette', wca_id: '2019MAUR04', live_id: '74', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Harry George', wca_id: 'New Competitor', live_id: '77', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Isaac Lau', wca_id: '2016LAUI01', live_id: '34', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jess Mitchell', wca_id: '2018MITC03', live_id: '57', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Louis Cormier', wca_id: '2010CORM02', live_id: '24', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Marko Young', wca_id: 'New Competitor', live_id: '68', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Max Murphy', wca_id: '2016MURP05', live_id: '20', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Nima Bolourchian', wca_id: '2017BOLO01', live_id: '100', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Prahaas Kotni', wca_id: 'New Competitor', live_id: '7', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Scotty Watkins', wca_id: 'New Competitor', live_id: '50', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '-', limit: '10:00' },
{ line_1: 'Pyraminx', line_2: 'Round 1', line_3: 'Group 4 of 6'},
{ name: 'Atharva Medihala', wca_id: '2019MEDI09', live_id: '111', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Brandon Chu', wca_id: '2018CHUB06', live_id: '105', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Devin Russell MacInnis', wca_id: '2017MACI07', live_id: '73', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Ethan Yeung', wca_id: '2019YEUN02', live_id: '90', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jacky Chen', wca_id: '2020CHEN04', live_id: '117', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Larry Shi', wca_id: '2019SHIL03', live_id: '88', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Liam Savarino', wca_id: '2018SAVA01', live_id: '32', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Matthew Garcia', wca_id: 'New Competitor', live_id: '128', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Max Xiong', wca_id: '2015XION03', live_id: '119', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Nathan Terpstra', wca_id: '2019TERP03', live_id: '85', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Nicole Wang', wca_id: '2018WANN03', live_id: '115', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Owen Muldoon', wca_id: '2018MULD01', live_id: '48', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Rene Desaulniers', wca_id: 'New Competitor', live_id: '98', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Ryan Wu', wca_id: '2017WURY01', live_id: '14', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Sébastien Bernard', wca_id: 'New Competitor', live_id: '93', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Thomas Imada', wca_id: '2018IMAD01', live_id: '64', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '-', limit: '10:00' },
{ line_1: 'Pyraminx', line_2: 'Round 1', line_3: 'Group 5 of 6'},
{ name: 'Andry Rakoto', wca_id: '2016RAKO02', live_id: '19', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Brennen Lin', wca_id: '2016LINB01', live_id: '75', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Brian Fudem', wca_id: 'New Competitor', live_id: '113', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Callum Smith', wca_id: '2019SMIT09', live_id: '124', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jack Smith', wca_id: '2019SMIT10', live_id: '125', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'James Wang', wca_id: '2019WANJ15', live_id: '4', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Joaquin Abarca', wca_id: '2017ABAR02', live_id: '17', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Liam Forth', wca_id: '2018FORT04', live_id: '97', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Lin Salvo', wca_id: '2019SALV05', live_id: '129', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Matthew Karunakaran', wca_id: 'New Competitor', live_id: '126', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Michael Bradley', wca_id: '2018BRAD08', live_id: '3', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Michael Zheng', wca_id: '2015ZHEN17', live_id: '36', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Robert Nelson', wca_id: '2011NELS01', live_id: '65', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Setu Marathe', wca_id: '2017MARA04', live_id: '82', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Shelby Russell', wca_id: 'New Competitor', live_id: '132', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Tin Huang', wca_id: '2019HUAN05', live_id: '42', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '-', limit: '10:00' },
{ line_1: 'Pyraminx', line_2: 'Round 1', line_3: 'Group 6 of 6'},
{ name: 'Derek Kong', wca_id: '2017KONG08', live_id: '39', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Derrick Ha', wca_id: 'New Competitor', live_id: '89', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jack Costa', wca_id: '2019COST11', live_id: '80', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jensen Belen-Brown', wca_id: '2016BELE02', live_id: '35', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jesse Wang', wca_id: 'New Competitor', live_id: '114', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jessica Ying', wca_id: '2017YING02', live_id: '120', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Jonathan Ferraioli', wca_id: '2017FERR12', live_id: '6', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Kevin Xu', wca_id: '2018XUKE03', live_id: '127', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Koda Arthur Cobierski', wca_id: '2019COBI01', live_id: '8', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Lucas Jacobs', wca_id: '2018JACO10', live_id: '23', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Myles David Suchma', wca_id: 'New Competitor', live_id: '79', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Omar Ellabban', wca_id: '2018ELLA01', live_id: '94', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Orion Donovan', wca_id: '2016DONO02', live_id: '61', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Ronan William Odell', wca_id: 'New Competitor', live_id: '45', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Sebastian Virág', wca_id: '2019VIRA01', live_id: '59', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ name: 'Viswathiha Mylashan', wca_id: 'New Competitor', live_id: '136', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '-', limit: '10:00' },
{ line_1: 'Pyraminx', line_2: 'Round 1', line_3: 'Extras' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '-', limit: '10:00' },
{ line_1: 'Unofficial Team Relay', line_2: 'Final', line_3: 'Group 1 of 1'},
{ name: '', wca_id: '', live_id: '', event: 'Team Relay', logo: 'logo_333.png', round: 'Final', group: 'Group 1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Team Relay', logo: 'logo_333.png', round: 'Final', group: 'Group 1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Team Relay', logo: 'logo_333.png', round: 'Final', group: 'Group 1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Team Relay', logo: 'logo_333.png', round: 'Final', group: 'Group 1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Team Relay', logo: 'logo_333.png', round: 'Final', group: 'Group 1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Team Relay', logo: 'logo_333.png', round: 'Final', group: 'Group 1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Team Relay', logo: 'logo_333.png', round: 'Final', group: 'Group 1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Team Relay', logo: 'logo_333.png', round: 'Final', group: 'Group 1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Team Relay', logo: 'logo_333.png', round: 'Final', group: 'Group 1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Team Relay', logo: 'logo_333.png', round: 'Final', group: 'Group 1 of 1', cutoff: '-', limit: '10:00' },
{ line_1: 'Unofficial Team Relay', line_2: 'Final', line_3: 'Extras'},
{ name: '', wca_id: '', live_id: '', event: 'Team Relay', logo: 'logo_333.png', round: 'Final', group: 'Group 1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Team Relay', logo: 'logo_333.png', round: 'Final', group: 'Group 1 of 1', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Team Relay', logo: 'logo_333.png', round: 'Final', group: 'Group 1 of 1', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 One-Handed', line_2: 'Round 1', line_3: 'Group 1 of 4'},
{ name: 'Abdullah Gulab', wca_id: '2014GULA02', live_id: '44', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Andry Rakoto', wca_id: '2016RAKO02', live_id: '19', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Austin Collins', wca_id: '2019COLL08', live_id: '72', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Derrick Ha', wca_id: 'New Competitor', live_id: '89', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Dylan Yihan Dai', wca_id: '2018DAID01', live_id: '58', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Harry George', wca_id: 'New Competitor', live_id: '77', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Jacky Chen', wca_id: '2020CHEN04', live_id: '117', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Jess Mitchell', wca_id: '2018MITC03', live_id: '57', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Jonathan Esparaz', wca_id: '2013ESPA01', live_id: '18', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Keegan Phillips', wca_id: '2019PHIL06', live_id: '27', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Larry Shi', wca_id: '2019SHIL03', live_id: '88', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Lucas Jacobs', wca_id: '2018JACO10', live_id: '23', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Massimo Corrado Caia', wca_id: '2019CAIA01', live_id: '109', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Matthew Lee', wca_id: '2017LEEM03', live_id: '51', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Nicole Wang', wca_id: '2018WANN03', live_id: '115', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Orion Donovan', wca_id: '2016DONO02', live_id: '61', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Prahaas Kotni', wca_id: 'New Competitor', live_id: '7', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Roan Paone', wca_id: '2017PAON01', live_id: '10', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Rymand Moarefi', wca_id: 'New Competitor', live_id: '29', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Shanglin Ye', wca_id: '2013YESH01', live_id: '22', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ line_1: '3x3x3 One-Handed', line_2: 'Round 1', line_3: 'Group 2 of 4'},
{ name: 'Aryan Ved', wca_id: '2018VEDA02', live_id: '2', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Brandon Chu', wca_id: '2018CHUB06', live_id: '105', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Dave Deriches', wca_id: '2018DERI02', live_id: '15', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Elliot Mauricette', wca_id: '2019MAUR04', live_id: '74', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Ian Yeh', wca_id: '2017YEHI01', live_id: '123', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Jack Costa', wca_id: '2019COST11', live_id: '80', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Jack Smith', wca_id: '2019SMIT10', live_id: '125', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'James Hocevar', wca_id: '2016HOCE02', live_id: '54', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Joaquin Abarca', wca_id: '2017ABAR02', live_id: '17', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Krish Ved', wca_id: '2018VEDK01', live_id: '107', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Liam Forth', wca_id: '2018FORT04', live_id: '97', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Max Xiong', wca_id: '2015XION03', live_id: '119', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Michael Bradley', wca_id: '2018BRAD08', live_id: '3', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Nihaas Kotni', wca_id: 'New Competitor', live_id: '12', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Nima Bolourchian', wca_id: '2017BOLO01', live_id: '100', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Prosper Huang', wca_id: '2018HUAP02', live_id: '104', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Ray Vince Ong', wca_id: '2012ONGR01', live_id: '33', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Samson Wu', wca_id: '2015WUSA01', live_id: '41', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Setu Marathe', wca_id: '2017MARA04', live_id: '82', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Stefano Coulter', wca_id: '2018COUL01', live_id: '13', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ line_1: '3x3x3 One-Handed', line_2: 'Round 1', line_3: 'Group 3 of 4'},
{ name: 'Andrew Yeung', wca_id: 'New Competitor', live_id: '99', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Brennen Lin', wca_id: '2016LINB01', live_id: '75', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Callum Smith', wca_id: '2019SMIT09', live_id: '124', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Colin Gawthroupe', wca_id: '2019GAWT01', live_id: '103', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Docité Oren Schandry', wca_id: '2019SCHA03', live_id: '53', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Ethan Yeung', wca_id: '2019YEUN02', live_id: '90', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Jensen Belen-Brown', wca_id: '2016BELE02', live_id: '35', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Kevin Xu', wca_id: '2018XUKE03', live_id: '127', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Koda Arthur Cobierski', wca_id: '2019COBI01', live_id: '8', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Lin Salvo', wca_id: '2019SALV05', live_id: '129', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Lucas Nieuwland', wca_id: '2018NIEU01', live_id: '11', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Marco Yang', wca_id: '2017YANG62', live_id: '37', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Max Murphy', wca_id: '2016MURP05', live_id: '20', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Michael Zheng', wca_id: '2015ZHEN17', live_id: '36', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Noah Tremblay', wca_id: '2019TREM02', live_id: '118', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Omar Ellabban', wca_id: '2018ELLA01', live_id: '94', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Rene Desaulniers', wca_id: 'New Competitor', live_id: '98', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Ryan Wu', wca_id: '2017WURY01', live_id: '14', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'William Fehr', wca_id: '2018FEHR01', live_id: '16', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 3 of 4', cutoff: '1:00', limit: '10:00' },
{ line_1: '3x3x3 One-Handed', line_2: 'Round 1', line_3: 'Group 4 of 4'},
{ name: 'Atharva Medihala', wca_id: '2019MEDI09', live_id: '111', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Christian Aiello', wca_id: '2017AIEL01', live_id: '134', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Derek Kong', wca_id: '2017KONG08', live_id: '39', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Devin Russell MacInnis', wca_id: '2017MACI07', live_id: '73', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Evan Rowland', wca_id: 'New Competitor', live_id: '28', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Joey Saia', wca_id: '2017SAIA01', live_id: '130', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Joon Song', wca_id: '2019SONG21', live_id: '46', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Louis Cormier', wca_id: '2010CORM02', live_id: '24', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Marko Young', wca_id: 'New Competitor', live_id: '68', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Mathew Niznansky', wca_id: '2018NIZN01', live_id: '56', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Owen Bailey-Braun', wca_id: '2019BAIL01', live_id: '63', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Owen Muldoon', wca_id: '2018MULD01', live_id: '48', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Robert Nelson', wca_id: '2011NELS01', live_id: '65', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Sebastian Virág', wca_id: '2019VIRA01', live_id: '59', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Stanley Wang', wca_id: '2017WANS05', live_id: '108', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Tarandeep Mittal', wca_id: '2014MITT02', live_id: '21', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Thomas Imada', wca_id: '2018IMAD01', live_id: '64', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Tin Huang', wca_id: '2019HUAN05', live_id: '42', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '1:00', limit: '10:00' },
{ name: 'Zhivko Radkov Dimitrov', wca_id: '2017DIMI01', live_id: '81', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 4 of 4', cutoff: '1:00', limit: '10:00' },
{ line_1: '3x3x3 One-Handed', line_2: 'Round 1', line_3: 'Extras' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 1 of 4', cutoff: '1:00', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Round 1', group: 'Group 2 of 4', cutoff: '1:00', limit: '10:00' },
{ line_1: 'Clock', line_2: 'Round 1', line_3: 'Group 1 of 6'},
{ name: 'Callum Smith', wca_id: '2019SMIT09', live_id: '124', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Jack Smith', wca_id: '2019SMIT10', live_id: '125', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Joaquin Abarca', wca_id: '2017ABAR02', live_id: '17', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Lucas Nieuwland', wca_id: '2018NIEU01', live_id: '11', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Max Murphy', wca_id: '2016MURP05', live_id: '20', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Thomas Imada', wca_id: '2018IMAD01', live_id: '64', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '0:45', limit: '10:00' },
{ line_1: 'Clock', line_2: 'Round 1', line_3: 'Group 2 of 6'},
{ name: 'Liam Savarino', wca_id: '2018SAVA01', live_id: '32', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Lucas Jacobs', wca_id: '2018JACO10', live_id: '23', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Marco Yang', wca_id: '2017YANG62', live_id: '37', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Nicole Wang', wca_id: '2018WANN03', live_id: '115', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Orion Donovan', wca_id: '2016DONO02', live_id: '61', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Roan Paone', wca_id: '2017PAON01', live_id: '10', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '0:45', limit: '10:00' },
{ line_1: 'Clock', line_2: 'Round 1', line_3: 'Group 3 of 6'},
{ name: 'Aryan Ved', wca_id: '2018VEDA02', live_id: '2', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Jess Mitchell', wca_id: '2018MITC03', live_id: '57', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Louis Cormier', wca_id: '2010CORM02', live_id: '24', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Matthew Garcia', wca_id: 'New Competitor', live_id: '128', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Max Xiong', wca_id: '2015XION03', live_id: '119', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Michael Bradley', wca_id: '2018BRAD08', live_id: '3', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 3 of 6', cutoff: '0:45', limit: '10:00' },
{ line_1: 'Clock', line_2: 'Round 1', line_3: 'Group 4 of 6'},
{ name: 'Brandon Chu', wca_id: '2018CHUB06', live_id: '105', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Dave Deriches', wca_id: '2018DERI02', live_id: '15', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Derek Kong', wca_id: '2017KONG08', live_id: '39', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Matthew Lee', wca_id: '2017LEEM03', live_id: '51', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Nima Bolourchian', wca_id: '2017BOLO01', live_id: '100', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Prosper Huang', wca_id: '2018HUAP02', live_id: '104', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 4 of 6', cutoff: '0:45', limit: '10:00' },
{ line_1: 'Clock', line_2: 'Round 1', line_3: 'Group 5 of 6'},
{ name: 'Abdullah Gulab', wca_id: '2014GULA02', live_id: '44', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Docité Oren Schandry', wca_id: '2019SCHA03', live_id: '53', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Joon Song', wca_id: '2019SONG21', live_id: '46', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Mathew Niznansky', wca_id: '2018NIZN01', live_id: '56', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Ryan Wu', wca_id: '2017WURY01', live_id: '14', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Rymand Moarefi', wca_id: 'New Competitor', live_id: '29', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 5 of 6', cutoff: '0:45', limit: '10:00' },
{ line_1: 'Clock', line_2: 'Round 1', line_3: 'Group 6 of 6'},
{ name: 'Andry Rakoto', wca_id: '2016RAKO02', live_id: '19', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Jack Costa', wca_id: '2019COST11', live_id: '80', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Joey Saia', wca_id: '2017SAIA01', live_id: '130', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Kevin Xu', wca_id: '2018XUKE03', live_id: '127', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '0:45', limit: '10:00' },
{ name: 'Tin Huang', wca_id: '2019HUAN05', live_id: '42', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 6 of 6', cutoff: '0:45', limit: '10:00' },
{ line_1: 'Clock', line_2: 'Round 1', line_3: 'Extras' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '0:45', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '0:45', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '0:45', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '0:45', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '0:45', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '0:45', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 1 of 6', cutoff: '0:45', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1', group: 'Group 2 of 6', cutoff: '0:45', limit: '10:00' },
{ line_1: '3x3x3', line_2: 'Round 2', line_3: 'Group 1 of 4' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 21', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 22', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 23', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 24', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 25', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 26', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 27', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 28', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 29', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 30', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3', line_2: 'Round 2', line_3: 'Group 2 of 4' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 31', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 32', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 33', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 34', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 35', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 36', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 37', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 38', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 39', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 40', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3', line_2: 'Round 2', line_3: 'Group 3 of 4' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 1', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 2', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 4', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 7', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 8', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 9', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 10', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3', line_2: 'Round 2', line_3: 'Group 4 of 4' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 11', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 12', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 13', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 14', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 15', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 16', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 17', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 18', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 19', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 20', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3', line_2: 'Round 2', line_3: 'Extras' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: '', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: '', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: '', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: '', cutoff: '-', limit: '10:00' },
{ line_1: 'Megaminx', line_2: 'Final', line_3: 'Group 1 of 6'},
{ name: 'Branavan Keethabaskaran', wca_id: 'New Competitor', live_id: '137', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 1 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Dave Deriches', wca_id: '2018DERI02', live_id: '15', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 1 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Dylan Yihan Dai', wca_id: '2018DAID01', live_id: '58', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 1 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Joey Saia', wca_id: '2017SAIA01', live_id: '130', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 1 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Joon Song', wca_id: '2019SONG21', live_id: '46', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 1 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Louis Cormier', wca_id: '2010CORM02', live_id: '24', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 1 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Marco Yang', wca_id: '2017YANG62', live_id: '37', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 1 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Thomas Imada', wca_id: '2018IMAD01', live_id: '64', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 1 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Toyo Witzmann', wca_id: '2018WITZ01', live_id: '66', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 1 of 6', cutoff: '3:30', limit: '10:00' },
{ line_1: 'Megaminx', line_2: 'Final', line_3: 'Group 2 of 6'},
{ name: 'Brandon Chu', wca_id: '2018CHUB06', live_id: '105', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 2 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Jensen Belen-Brown', wca_id: '2016BELE02', live_id: '35', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 2 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Jess Mitchell', wca_id: '2018MITC03', live_id: '57', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 2 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Koda Arthur Cobierski', wca_id: '2019COBI01', live_id: '8', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 2 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Nicole Wang', wca_id: '2018WANN03', live_id: '115', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 2 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Omar Ellabban', wca_id: '2018ELLA01', live_id: '94', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 2 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Ryan Wu', wca_id: '2017WURY01', live_id: '14', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 2 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Stefano Coulter', wca_id: '2018COUL01', live_id: '13', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 2 of 6', cutoff: '3:30', limit: '10:00' },
{ line_1: 'Megaminx', line_2: 'Final', line_3: 'Group 3 of 6'},
{ name: 'Abdullah Gulab', wca_id: '2014GULA02', live_id: '44', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 3 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Callum Smith', wca_id: '2019SMIT09', live_id: '124', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 3 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Docité Oren Schandry', wca_id: '2019SCHA03', live_id: '53', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 3 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Larry Shi', wca_id: '2019SHIL03', live_id: '88', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 3 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Lucas Nieuwland', wca_id: '2018NIEU01', live_id: '11', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 3 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Owen Bailey-Braun', wca_id: '2019BAIL01', live_id: '63', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 3 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Roan Paone', wca_id: '2017PAON01', live_id: '10', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 3 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Shanglin Ye', wca_id: '2013YESH01', live_id: '22', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 3 of 6', cutoff: '3:30', limit: '10:00' },
{ line_1: 'Megaminx', line_2: 'Final', line_3: 'Group 4 of 6'},
{ name: 'Brennen Lin', wca_id: '2016LINB01', live_id: '75', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 4 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Derrick Ha', wca_id: 'New Competitor', live_id: '89', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 4 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Ian Yeh', wca_id: '2017YEHI01', live_id: '123', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 4 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Max Xiong', wca_id: '2015XION03', live_id: '119', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 4 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Noah Tremblay', wca_id: '2019TREM02', live_id: '118', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 4 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Prosper Huang', wca_id: '2018HUAP02', live_id: '104', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 4 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Sarah Strong', wca_id: '2007STRO01', live_id: '1', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 4 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Sebastian Virág', wca_id: '2019VIRA01', live_id: '59', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 4 of 6', cutoff: '3:30', limit: '10:00' },
{ line_1: 'Megaminx', line_2: 'Final', line_3: 'Group 5 of 6'},
{ name: 'Derek Kong', wca_id: '2017KONG08', live_id: '39', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 5 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Ethan Yeung', wca_id: '2019YEUN02', live_id: '90', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 5 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Harry George', wca_id: 'New Competitor', live_id: '77', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 5 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Joaquin Abarca', wca_id: '2017ABAR02', live_id: '17', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 5 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Jonathan Esparaz', wca_id: '2013ESPA01', live_id: '18', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 5 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Kevin Xu', wca_id: '2018XUKE03', live_id: '127', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 5 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Prahaas Kotni', wca_id: 'New Competitor', live_id: '7', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 5 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Zhivko Radkov Dimitrov', wca_id: '2017DIMI01', live_id: '81', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 5 of 6', cutoff: '3:30', limit: '10:00' },
{ line_1: 'Megaminx', line_2: 'Final', line_3: 'Group 6 of 6'},
{ name: 'Aryan Ved', wca_id: '2018VEDA02', live_id: '2', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 6 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Jack Smith', wca_id: '2019SMIT10', live_id: '125', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 6 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Lucas Jacobs', wca_id: '2018JACO10', live_id: '23', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 6 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Mathew Niznansky', wca_id: '2018NIZN01', live_id: '56', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 6 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Matthew Lee', wca_id: '2017LEEM03', live_id: '51', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 6 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Max Murphy', wca_id: '2016MURP05', live_id: '20', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 6 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Michael Bradley', wca_id: '2018BRAD08', live_id: '3', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 6 of 6', cutoff: '3:30', limit: '10:00' },
{ name: 'Shelby Russell', wca_id: 'New Competitor', live_id: '132', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 6 of 6', cutoff: '3:30', limit: '10:00' },
{ line_1: 'Megaminx', line_2: 'Final', line_3: 'Extras' },
{ name: '', wca_id: '', live_id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 1 of 6', cutoff: '3:30', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 2 of 6', cutoff: '3:30', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 1 of 6', cutoff: '3:30', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 2 of 6', cutoff: '3:30', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 1 of 6', cutoff: '3:30', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 2 of 6', cutoff: '3:30', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 1 of 6', cutoff: '3:30', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Megaminx', logo: 'logo_minx.png', round: 'Final', group: 'Group 2 of 6', cutoff: '3:30', limit: '10:00' },
{ line_1: 'Pyraminx', line_2: 'Final', line_3: 'Group 1 of 2' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final', group: 'Seed 1', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final', group: 'Seed 2', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final', group: 'Seed 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final', group: 'Seed 4', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final', group: 'Seed 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final', group: 'Seed 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final', group: 'Seed 7', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final', group: 'Seed 8', cutoff: '-', limit: '10:00' },
{ line_1: 'Pyraminx', line_2: 'Final', line_3: 'Group 2 of 2' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final', group: 'Seed 9', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final', group: 'Seed 10', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final', group: 'Seed 11', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final', group: 'Seed 12', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final', group: 'Seed 13', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final', group: 'Seed 14', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final', group: 'Seed 15', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final', group: 'Seed 16', cutoff: '-', limit: '10:00' },
{ line_1: 'Pyraminx', line_2: 'Final', line_3: 'Extras' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final', group: '', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Pyraminx', logo: 'logo_pyram.png', round: 'Final', group: '', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 One-Handed', line_2: 'Final', line_3: 'Group 1 of 2' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 1', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 2', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 4', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 7', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 8', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 One-Handed', line_2: 'Final', line_3: 'Group 2 of 2' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 9', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 10', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 11', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 12', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 13', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 14', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 15', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: 'Seed 16', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3 One-Handed', line_2: 'Final', line_3: 'Extras' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 One-Handed', logo: 'logo_333oh.png', round: 'Final', group: '', cutoff: '-', limit: '10:00' },
{ line_1: 'Clock', line_2: 'Final', line_3: 'Group 1 of 2' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 1', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 2', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 4', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 7', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 8', cutoff: '-', limit: '10:00' },
{ line_1: 'Clock', line_2: 'Final', line_3: 'Group 2 of 2' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 9', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 10', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 11', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 12', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 13', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 14', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 15', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: 'Seed 16', cutoff: '-', limit: '10:00' },
{ line_1: 'Clock', line_2: 'Final', line_3: 'Extras' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: '', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: '', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3', line_2: 'Final', line_3: 'Group 1 of 2' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 1', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 2', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 3', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 4', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 5', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 6', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 7', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 8', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3', line_2: 'Final', line_3: 'Group 1 of 2' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 9', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 10', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 11', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 12', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 13', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 14', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 15', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: 'Seed 16', cutoff: '-', limit: '10:00' },
{ line_1: '3x3x3', line_2: 'Final', line_3: 'Extras' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: '', cutoff: '-', limit: '10:00' },
{ name: '', wca_id: '', live_id: '', event: '3x3x3 Cube', logo: 'logo_333.png', round: 'Final', group: '', cutoff: '-', limit: '10:00' },
]
