window.competitors = [
{ name: 'Adrian Stan', id: '2016STAN12', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Alan Jia', id: '2017JIAA01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Alex Jung', id: '2018JUNG02', country: 'Korea' ,title: 'COMPETITOR' },
{ name: 'Alex Keats', id: '2012KEAT01', country: 'Canada' ,title: 'STAFF' },
{ name: 'Alexander Au', id: '2018AUAL01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Alyssa Esparaz', id: '2014ESPA01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Arhaan Sareen', id: '2017SARE03', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Askar Dakeshov', id: 'New Competitor', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Ben Bergen', id: '2015BERG10', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Ben Madison', id: '2016MADI02', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Bill Wang', id: '2010WANG68', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Brady Metherall', id: '2009METH01', country: 'Canada' ,title: 'STAFF' },
{ name: 'Bram Ogus', id: 'New Competitor', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Brendan Chan', id: 'New Competitor', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Colin Cayen', id: '2015CAYE02', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Craig Bouchard', id: '2005BOUC01', country: 'Canada' ,title: 'STAFF' },
{ name: 'Daniel Pavelich', id: '2015PAVE01', country: 'USA' ,title: 'COMPETITOR' },
{ name: 'Derek Kong', id: '2017KONG08', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Dimitri Huinink ', id: 'New Competitor', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Edward Wu', id: '2015WUED01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Einsten Augustine', id: 'New Competitor', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Emile Compion', id: '2007COMP01', country: 'South Africa' ,title: 'STAFF' },
{ name: 'Ethan Erez', id: '2017EREZ01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Finn Noel', id: '2017NOEL05', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Fred Quong', id: '2015QUON01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Gabrielle Morasse', id: '2013MORA08', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Isak Falk', id: 'New Competitor', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Jack Boos', id: '2016BOOS01', country: 'Canada' ,title: 'STAFF' },
{ name: 'Jeffrey Draper', id: '2014DRAP01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Jeremie Notebaert', id: 'New Competitor', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Joaquin Abarca', id: '2017ABAR02', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Jonathan Esparaz', id: '2013ESPA01', country: 'Canada' ,title: 'STAFF' },
{ name: 'Jonathan Tan', id: '2009XIAT02', country: 'Malaysia' ,title: 'STAFF' },
{ name: 'Julian David', id: '2010DAVI06', country: 'Canada' ,title: 'STAFF' },
{ name: 'Kael Scarlett', id: '2018SCAR01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Karina Nemirovski', id: '2018NEMI02', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Kyle Corbin', id: '2018CORB01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Leo Min-Bedford', id: '2014MINB01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Liam Henderson', id: 'New Competitor', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'LianCheng Guo', id: '2016GUOL01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Louis Cormier', id: '2010CORM02', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Luke MacDonald', id: '2018MACD02', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Malcolm Peeters', id: '2017PEET01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Marco Yang', id: '2017YANG62', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Mathieu Preston', id: '2014PRES03', country: 'Canada' ,title: 'STAFF' },
{ name: 'Matteo Hosdil', id: '2017HOSD01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Max Xiong', id: '2015XION03', country: 'China' ,title: 'STAFF' },
{ name: 'Michael Fisher', id: '2017FISH03', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Michael Rose', id: '2011ROSE03', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Michael Zheng', id: '2018ZHEN04', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Nastia Patrice', id: '2017PATR03', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Nestor Sokhan', id: '2016SOKH01', country: 'USA' ,title: 'COMPETITOR' },
{ name: 'Nicholas Patterson', id: '2016PATT02', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Noah Martin', id: '2018MART29', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Oliver Boyes', id: '2017BOYE01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Owen Berg', id: '2018BERG03', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Paul Ellement', id: '2016ELLE01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Peter Douthwright', id: '2007DOUT01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Ranran Zhao', id: '2017ZHAO44', country: 'China' ,title: 'COMPETITOR' },
{ name: 'Ray Vince Ong', id: '2012ONGR01', country: 'Canada' ,title: 'STAFF' },
{ name: 'Richard Madison', id: '2017MADI03', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Roan Paone', id: '2017PAON01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Ryan Hinds', id: '2018HIND01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Ryan Minjun Cho', id: '2014CHOR01', country: 'Canada' ,title: 'STAFF' },
{ name: 'Ryan S. Woods', id: '2016WOOD08', country: 'USA' ,title: 'COMPETITOR' },
{ name: 'Ryan Wu', id: '2017WURY01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Samuel Moran', id: '2015MORA08', country: 'USA' ,title: 'COMPETITOR' },
{ name: 'Samuel Pakulat', id: '2018PAKU01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Sascha Pugar', id: '2015PUGA01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Sehaj Dhillon', id: 'New Competitor', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Seth Huygen', id: 'New Competitor', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Seungmin Hong', id: '2017HONG09', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Shanglin Ye', id: '2013YESH01', country: 'Canada' ,title: 'STAFF' },
{ name: 'Taha Ben Salah', id: '2015SALA03', country: 'Tunisia' ,title: 'COMPETITOR' },
{ name: 'Tarandeep Mittal', id: '2014MITT02', country: 'Canada' ,title: 'STAFF' },
{ name: 'Tommy Madison', id: '2017MADI01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Wenda Jiang', id: '2013JIAN11', country: 'China' ,title: 'COMPETITOR' },
{ name: 'Wesley Pakulat', id: '2018PAKU02', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Yexing Li', id: '2015LIYE01', country: 'China' ,title: 'COMPETITOR' },
{ name: 'Young He', id: '2014HEYO01', country: 'China' ,title: 'COMPETITOR' },
{ name: 'Zachary Beitel', id: '2017BEIT01', country: 'Canada' ,title: 'COMPETITOR' },
{ name: 'Michael Strong', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: 'Chris Thomson', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: '', id: '', country: '' ,title: 'COMPETITOR' },
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: '', id: '', country: '' ,title: 'COMPETITOR' },
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: '', id: '', country: '' ,title: 'COMPETITOR' },
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: '', id: '', country: '' ,title: 'COMPETITOR' },
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: '', id: '', country: '' ,title: 'COMPETITOR' },
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: '', id: '', country: '' ,title: 'COMPETITOR' },
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: '', id: '', country: '' ,title: 'COMPETITOR' },
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: '', id: '', country: '' ,title: 'COMPETITOR' },
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: '', id: '', country: '' ,title: 'COMPETITOR' },
{ name: '', id: '', country: '' ,title: 'VOLUNTEER' },
{ name: '', id: '', country: '' ,title: 'COMPETITOR' },
{ name: 'Colleen Geerlinks', id: '2014GEER01', country: 'Canada' ,title: 'VOLUNTEER' },
{ name: 'Sarah Strong', id: '2007STRO01', country: 'Canada' ,title: 'ORGANIZER' },
{ name: 'Dave Campbell', id: '2005CAMP01', country: 'Canada' ,title: 'DELEGATE' },
]
