window.mo3events =['6x6x6 Cube', '7x7x7 Cube', '3x3x3 Blindfolded', '4x4x4 Blindfolded', '5x5x5 Blindfolded'];

window.cumulativeevents =['3x3x3 Blindfolded', '4x4x4 Blindfolded', '5x5x5 Blindfolded'];

window.bo3events = ['3x3x3 Multi-Blind'];

window.competitors = [
{ blank: '4x4x4 Blindfolded Final Group 1' },
{ name: 'Abdullah Gulab', id: '2014GULA02', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Brant Holbein', id: '2014HOLB01', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Chen-Pin Sun (孫振斌)', id: '2017SUNC03', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Derek Kong', id: '2017KONG08', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Emile Compion', id: '2007COMP01', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Eric Limeback', id: '2007LIME01', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Jonathan Esparaz', id: '2013ESPA01', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Joshua Graham', id: '2013GRAH01', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Marco Yang', id: '2017YANG62', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Nicholas Patterson', id: '2016PATT02', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: 'Roan Paone', id: '2017PAON01', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ blank: '5x5x5 Blindfolded Final Group 1' },
{ name: 'Abdullah Gulab', id: '2014GULA02', event: '5x5x5 Blindfolded', logo: 'logo_555bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '90:00' },
{ name: 'Brant Holbein', id: '2014HOLB01', event: '5x5x5 Blindfolded', logo: 'logo_555bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '90:00' },
{ name: 'Chen-Pin Sun (孫振斌)', id: '2017SUNC03', event: '5x5x5 Blindfolded', logo: 'logo_555bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '90:00' },
{ name: 'Emile Compion', id: '2007COMP01', event: '5x5x5 Blindfolded', logo: 'logo_555bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '90:00' },
{ name: 'Joshua Graham', id: '2013GRAH01', event: '5x5x5 Blindfolded', logo: 'logo_555bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '90:00' },
{ name: 'Marco Yang', id: '2017YANG62', event: '5x5x5 Blindfolded', logo: 'logo_555bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '90:00' },
{ name: 'Nicholas Patterson', id: '2016PATT02', event: '5x5x5 Blindfolded', logo: 'logo_555bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '90:00' },
{ name: 'Roan Paone', id: '2017PAON01', event: '5x5x5 Blindfolded', logo: 'logo_555bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '90:00' },
{ blank: '3x3x3 Multi-Blind Final Group 1' },
{ name: 'Abdullah Gulab', id: '2014GULA02', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: 'Ben Rockman', id: '2014ROCK01', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: 'Brant Holbein', id: '2014HOLB01', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: 'Chen-Pin Sun (孫振斌)', id: '2017SUNC03', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: 'Derek Kong', id: '2017KONG08', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: 'Emile Compion', id: '2007COMP01', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: 'Eric Limeback', id: '2007LIME01', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: 'Jonathan Esparaz', id: '2013ESPA01', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: 'Joshua Graham', id: '2013GRAH01', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: 'Marco Yang', id: '2017YANG62', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: 'Nicholas Patterson', id: '2016PATT02', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: 'Roan Paone', id: '2017PAON01', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: 'Ryan Pin Harry', id: '2015HARR01', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ blank: 'Clock Round 1 Group 1' },
{ name: 'Andrew Nguyen', id: '2011NGUY03', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: 'Brant Holbein', id: '2014HOLB01', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: 'Dave Deriches', id: '2018DERI02', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: 'Derek Kong', id: '2017KONG08', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: 'Marco Yang', id: '2017YANG62', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: 'Nicholas Patterson', id: '2016PATT02', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: 'Roan Paone', id: '2017PAON01', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: 'Ryan Pin Harry', id: '2015HARR01', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '1:00', limit: '10:00' },
{ blank: 'Clock Round 1 Group 2' },
{ name: 'Abdullah Gulab', id: '2014GULA02', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '1:00', limit: '10:00' },
{ name: 'Ben Rockman', id: '2014ROCK01', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '1:00', limit: '10:00' },
{ name: 'Emile Compion', id: '2007COMP01', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '1:00', limit: '10:00' },
{ name: 'Jonathan Esparaz', id: '2013ESPA01', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '1:00', limit: '10:00' },
{ name: 'Joshua Graham', id: '2013GRAH01', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '1:00', limit: '10:00' },
{ name: 'Kyria Sztainbok', id: '2018SZTA01', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '1:00', limit: '10:00' },
{ name: 'Lucas Nieuwland', id: '2018NIEU01', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '1:00', limit: '10:00' },
{ name: 'Sarah Strong', id: '2007STRO01', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '1:00', limit: '10:00' },
{ blank: 'Clock Round 1 Extras' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '1 of 2', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Round 1 of 2', group: '2 of 2', cutoff: '1:00', limit: '10:00' },
{ blank: '3x3x3 Multi-Blind Final Extras' },
{ name: '', id: '', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ name: '', id: '', event: '3x3x3 Multi-Blind', logo: 'logo_333mbf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '' },
{ blank: '4x4x4 Blindfolded Final Extras' },
{ name: '', id: '', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: '', id: '', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: '', id: '', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: '', id: '', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: '', id: '', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: '', id: '', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: '', id: '', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: '', id: '', event: '4x4x4 Blindfolded', logo: 'logo_444bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ blank: '5x5x5 Blindfolded Final Extras' },
{ name: '', id: '', event: '5x5x5 Blindfolded', logo: 'logo_555bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: '', id: '', event: '5x5x5 Blindfolded', logo: 'logo_555bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: '', id: '', event: '5x5x5 Blindfolded', logo: 'logo_555bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: '', id: '', event: '5x5x5 Blindfolded', logo: 'logo_555bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: '', id: '', event: '5x5x5 Blindfolded', logo: 'logo_555bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: '', id: '', event: '5x5x5 Blindfolded', logo: 'logo_555bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: '', id: '', event: '5x5x5 Blindfolded', logo: 'logo_555bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ name: '', id: '', event: '5x5x5 Blindfolded', logo: 'logo_555bf.png', round: 'Final', group: '1 of 1', cutoff: '-', limit: '60:00' },
{ blank: 'Clock Final and Extras' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: '1 of 1', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: '1 of 1', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: '1 of 1', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: '1 of 1', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: '1 of 1', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: '1 of 1', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: '1 of 1', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: '1 of 1', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: '1 of 1', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: '1 of 1', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: '1 of 1', cutoff: '1:00', limit: '10:00' },
{ name: '', id: '', event: 'Clock', logo: 'logo_clock.png', round: 'Final', group: '1 of 1', cutoff: '1:00', limit: '10:00' },
]
